package io.ruin.model.activities.perktree;


import io.ruin.cache.ItemID;
import io.ruin.cache.NpcID;
import io.ruin.model.skills.construction.Buildable;
import io.ruin.model.skills.slayer.SlayerMaster;
import io.ruin.model.stat.StatType;

//@formatter:off
public enum PerkTasks {
	STRONGHOLD_COURSE("Complete ", " laps of the stronghold agility course", TaskTiers.EASY, TaskType.SKILLING, 7, 14, StatType.Agility, 1, 1, 0),
	DRAYNOR_COURSE("Complete ", " laps of the draynor rooftop agility course", TaskTiers.EASY, TaskType.SKILLING, 7, 14, StatType.Agility, 10, 2, 0),
	ALKHARID_COURSE("Complete ", " laps of the al kharid rooftop agility course", TaskTiers.EASY, TaskType.SKILLING, 7, 14, StatType.Agility, 20, 3, 0),
	VARROCK_COURSE("Complete ", " laps of the varrock rooftop agility course", TaskTiers.EASY, TaskType.SKILLING, 7, 14, StatType.Agility, 30, 4, 0),
	CANIFIS_COURSE("Complete ", " laps of the canifis rooftop agility course", TaskTiers.MEDIUM, TaskType.SKILLING, 9, 15, StatType.Agility, 40, 5, 0),
	FALADOR_COURSE("Complete ", " laps of the falador rooftop agility course", TaskTiers.MEDIUM, TaskType.SKILLING, 9, 15, StatType.Agility, 50, 6, 0),
	WILDERNESS_COURSE("Complete ", " laps of the wilderness agility course", TaskTiers.MEDIUM, TaskType.WILDERNESS, 9, 13, StatType.Agility, 52, 7, 0),
	SEERS_COURSE("Complete ", " laps of the seers' rooftop agility course", TaskTiers.HARD, TaskType.SKILLING, 11, 17, StatType.Agility, 60, 8, 0),
	POLLNIVNEACH_COURSE("Complete ", " laps of the pollnivneach rooftop agility course", TaskTiers.HARD, TaskType.SKILLING, 11, 17, StatType.Agility, 70, 9, 0),
	RELLEKA_COURSE("Complete ", " laps of the relleka rooftop agility course", TaskTiers.ELITE, TaskType.SKILLING, 13, 20, StatType.Agility, 80, 10, 0),
	ARDOUGNE_COURSE("Complete ", " laps of the ardougne rooftop agility course", TaskTiers.ELITE, TaskType.SKILLING, 13, 20, StatType.Agility, 90, 11, 0),
	CRAFT_AIR("Runecraft ", " air runes", TaskTiers.EASY, TaskType.SKILLING, 100, 200, StatType.Runecrafting, 1, ItemID.AIR_RUNE, 0),
	CRAFT_MIND("Runecraft ", " mind runes", TaskTiers.EASY, TaskType.SKILLING, 100, 200, StatType.Runecrafting, 2, ItemID.MIND_RUNE, 0),
	CRAFT_WATER("Runecraft ", " water runes", TaskTiers.EASY, TaskType.SKILLING, 100, 180, StatType.Runecrafting, 5, ItemID.WATER_RUNE, 0),
	CRAFT_EARTH("Runecraft ", " earth runes", TaskTiers.EASY, TaskType.SKILLING, 100, 180, StatType.Runecrafting, 9, ItemID.EARTH_RUNE, 0),
	CRAFT_FIRE("Runecraft ", " fire runes", TaskTiers.EASY, TaskType.SKILLING, 75, 150, StatType.Runecrafting, 14, ItemID.FIRE_RUNE, 0),
	CRAFT_LAVA("Runecraft ", " lava runes", TaskTiers.MEDIUM, TaskType.SKILLING, 50, 150, StatType.Runecrafting, 23, ItemID.LAVA_RUNE, 0),
	CRAFT_COSMIC("Runecraft ", " cosmic runes", TaskTiers.MEDIUM, TaskType.SKILLING, 75, 150, StatType.Runecrafting, 27, ItemID.COSMIC_RUNE, 0),
	CRAFT_CHAOS("Runecraft ", " chaos runes", TaskTiers.MEDIUM, TaskType.SKILLING, 75, 150, StatType.Runecrafting, 35, ItemID.CHAOS_RUNE, 0),
	CRAFT_ASTRAL("Runecraft ", " astral runes", TaskTiers.MEDIUM, TaskType.SKILLING, 75, 150, StatType.Runecrafting, 40, ItemID.ASTRAL_RUNE, 0),
	CRAFT_NATURE("Runecraft ", " nature runes", TaskTiers.MEDIUM, TaskType.SKILLING, 75, 150, StatType.Runecrafting, 44, ItemID.NATURE_RUNE, 0),
	CRAFT_LAW("Runecraft ", " law runes", TaskTiers.HARD, TaskType.SKILLING, 90, 210, StatType.Runecrafting, 54, ItemID.LAW_RUNE, 0),
	CRAFT_DEATH("Runecraft ", " death runes", TaskTiers.HARD, TaskType.SKILLING, 90, 210, StatType.Runecrafting, 65, ItemID.DEATH_RUNE, 0),
	CRAFT_BLOOD("Runecraft ", " blood runes", TaskTiers.ELITE, TaskType.SKILLING, 90, 210, StatType.Runecrafting, 77, ItemID.BLOOD_RUNE, 0),
	CRAFT_SOUL("Runecraft ", " soul runes", TaskTiers.ELITE, TaskType.SKILLING, 180, 350, StatType.Runecrafting, 90, ItemID.SOUL_RUNE, 0),
	CRAFT_WRATH("Runecraft ", " wrath runes", TaskTiers.ELITE, TaskType.SKILLING, 180, 350, StatType.Runecrafting, 95, ItemID.WRATH_RUNE, 0),
	BUILD_CRUDE_WOODEN_CHAIR("Build ", " crude wooden chairs", TaskTiers.EASY, TaskType.SKILLING, 4, 12, StatType.Construction, 1, Buildable.CRUDE_WOODEN_CHAIR.ordinal(), 0),
	BUILD_WOODEN_CHAIR("Build ", " wooden chairs", TaskTiers.EASY, TaskType.SKILLING, 4, 12, StatType.Construction, 8, Buildable.WOODEN_CHAIR.ordinal(), 0),
	BUILD_OAK_CHAIR("Build ", " oak chairs", TaskTiers.EASY, TaskType.SKILLING, 4, 12, StatType.Construction, 19, Buildable.OAK_CHAIR.ordinal(), 0),
	BUILD_TEAK_ARMCHAIR("Build ", " teak armchairs", TaskTiers.MEDIUM, TaskType.SKILLING, 6, 18, StatType.Construction, 35, Buildable.TEAK_ARMCHAIR.ordinal(), 0),
	BUILD_TEAK_DINING_TABLE("Build ", " teak dining tables", TaskTiers.MEDIUM, TaskType.SKILLING, 6, 18, StatType.Construction, 38, Buildable.TEAK_DINING_TABLE.ordinal(), 0),
	BUILD_OAK_LARDER("Build ", " oak larders", TaskTiers.MEDIUM, TaskType.SKILLING, 6, 18, StatType.Construction, 33, Buildable.OAK_LARDER.ordinal(), 0),
	BUILD_MAHOGANY_ARMCHAIR("Build ", " mahogany armchairs", TaskTiers.MEDIUM, TaskType.SKILLING, 6, 18, StatType.Construction, 50, Buildable.MAHOGANY_ARMCHAIR.ordinal(), 0),
	BUILD_MAHOGANY_DINING_TABLE("Build ", " teak dining tables", TaskTiers.MEDIUM, TaskType.SKILLING, 6, 18, StatType.Construction, 52, Buildable.MAHOGANY_DINING_TABLE.ordinal(), 0),
	BUILD_OAK_THRONE("Build ", " oak thrones", TaskTiers.HARD, TaskType.SKILLING, 9, 21, StatType.Construction, 60, Buildable.OAK_THRONE.ordinal(), 0),
	BUILD_TEAK_THRONE("Build ", " teak thrones", TaskTiers.HARD, TaskType.SKILLING, 9, 21, StatType.Construction, 67, Buildable.TEAK_THRONE.ordinal(), 0),
	BUILD_MAHOGANY_THRONE("Build ", " mahogany thrones", TaskTiers.ELITE, TaskType.SKILLING, 15, 30, StatType.Construction, 74, Buildable.MAHOGANY_THRONE.ordinal(), 0),
	MIX_ATTACK("Mix ", " attack potions", TaskTiers.EASY, TaskType.SKILLING, 20, 30, StatType.Herblore, 1, ItemID.ATTACK_POTION3, 0),
	MIX_ANTIPOISON("Mix ", " anti-poison potions", TaskTiers.EASY, TaskType.SKILLING, 20,	30, StatType.Herblore, 5, ItemID.ANTIPOISON3, 0),
	MIX_STRENGTH("Mix ", " strength potions", TaskTiers.EASY, TaskType.SKILLING, 20, 30, StatType.Herblore, 12, ItemID.STRENGTH_POTION3, 0),
	MIX_RESTORE_POTION("Mix ", " restore potions", TaskTiers.EASY, TaskType.SKILLING, 20, 30, StatType.Herblore, 22, ItemID.RESTORE_POTION3, 0),
	MIX_ENERGY_POTION("Mix ", " energy potions", TaskTiers.EASY, TaskType.SKILLING, 20, 30, StatType.Herblore, 26, ItemID.ENERGY_POTION3, 0),
	MIX_AGILITY_POTION("Mix ", " agility potions", TaskTiers.EASY, TaskType.SKILLING, 20, 30, StatType.Herblore, 34, ItemID.AGILITY_POTION3, 0),
	MIX_PRAYER_POTION("Mix ", " prayer potions", TaskTiers.MEDIUM, TaskType.SKILLING, 30, 40, StatType.Herblore, 38, ItemID.PRAYER_POTION3, 0),
	MIX_SUPER_ATTACK("Mix ", " super attack potions", TaskTiers.MEDIUM, TaskType.SKILLING, 30, 40, StatType.Herblore, 45, ItemID.SUPER_ATTACK3, 0),
	MIX_SUPER_ANTI("Mix ", " super attack potions", TaskTiers.MEDIUM, TaskType.SKILLING, 30, 40, StatType.Herblore, 48, ItemID.SUPERANTIPOISON3, 0),
	MIX_SUPER_ENERGY("Mix ", " super energy potions", TaskTiers.MEDIUM, TaskType.SKILLING, 30, 40, StatType.Herblore, 52, ItemID.SUPERANTIPOISON3, 0),
	MIX_SUPER_STRENGTH("Mix ", " super strength potions", TaskTiers.MEDIUM, TaskType.SKILLING, 30, 40, StatType.Herblore, 55, ItemID.SUPER_STRENGTH3, 0),
	MIX_SUPER_RESTORE("Mix ", " super restore potions", TaskTiers.HARD, TaskType.SKILLING, 40, 60, StatType.Herblore, 63, ItemID.SUPER_RESTORE3, 0),
	MIX_SUPER_DEFENCE("Mix ", " super defence potions", TaskTiers.HARD, TaskType.SKILLING, 40, 60, StatType.Herblore, 68, ItemID.SUPER_DEFENCE3, 0),
	MIX_ANTIFIRE("Mix ", " antifire potions", TaskTiers.HARD, TaskType.SKILLING, 40, 60, StatType.Herblore, 69, ItemID.ANTIFIRE_POTION3, 0),
	MIX_RANGING_POTION("Mix ", " ranging potions", TaskTiers.HARD, TaskType.SKILLING, 40, 60, StatType.Herblore, 72, ItemID.RANGING_POTION3, 0),
	MIX_DIVINE_RANGE("Mix ", " divine ranging potions (4)", TaskTiers.HARD, TaskType.SKILLING, 40, 60, StatType.Herblore, 74, ItemID.DIVINE_RANGING_POTION4, 0),
	MIX_MAGIC_POTION("Mix ", " magic potions", TaskTiers.HARD, TaskType.SKILLING, 30, 60, StatType.Herblore, 76, ItemID.MAGIC_POTION3, 0),
	MIX_SARA_BREW("Mix ", " saradomin brews", TaskTiers.ELITE, TaskType.SKILLING, 30,
		60, StatType.Herblore, 81, ItemID.SARADOMIN_BREW3, 0),
	PICKPOCKET_MAN("Pickpocket a man ", " times", TaskTiers.EASY,
		TaskType.SKILLING, 12, 32, StatType.Thieving, 1, 13, 0),
	PICKPOCKET_FARMER("Pickpocket a farmer ", " times", TaskTiers.EASY,
		TaskType.SKILLING, 12, 32, StatType.Thieving, 10, 14, 0),
	PICKPOCKET_MASTER_FARMER("Pickpocket a farmer ", " times", TaskTiers.MEDIUM,
		TaskType.SKILLING, 16, 42, StatType.Thieving, 38, 15, 0),
	PICKPOCKET_GUARD("Pickpocket a guard ", " times", TaskTiers.MEDIUM,
		TaskType.SKILLING, 16, 42, StatType.Thieving, 40, 16, 0),
	PICKPOCKET_DESERT_BANDIT("Pickpocket a desert bandit (bandit camp)", " times", TaskTiers.MEDIUM,
		TaskType.SKILLING, 16, 42, StatType.Thieving, 53, 18, 0),
	//PICKPOCKET_ARDY_KNIGHT("pickpocket an ardougne knight ", " times", TaskTiers.HARD,
	//TaskType.SKILLING, 30, 65, StatType.Thieving, 55, 19, 0),
	PICKPOCKET_PALADIN("Pickpocket a paladin ", " times", TaskTiers.HARD,
		TaskType.SKILLING, 40, 75, StatType.Thieving, 70, 21, 0),
	PICKPOCKET_GNOME("Pickpocket a gnome ", " times", TaskTiers.ELITE,
		TaskType.SKILLING, 90, 110, StatType.Thieving, 75, 22, 0),
	PICKPOCKET_HERO("Pickpocket a hero ", " times", TaskTiers.ELITE,
		TaskType.SKILLING, 90, 110, StatType.Thieving, 80, 23, 0),
	PICKPOCKET_TZHAAR("Pickpocket a Tzhaar ", " times", TaskTiers.ELITE,
		TaskType.SKILLING, 90, 110, StatType.Thieving, 90, 26, 0),
	CRAFT_LEATHER_GLOVES("Craft ", " leather gloves", TaskTiers.EASY, TaskType.SKILLING,
		12, 25, StatType.Crafting, 1, ItemID.LEATHER_GLOVES, 0),
	CRAFT_LEATHER_BOOTS("Craft ", " leather boots", TaskTiers.EASY, TaskType.SKILLING,
		12, 25, StatType.Crafting, 7, ItemID.LEATHER_BOOTS, 0),
	CRAFT_LEATHER_COWL("Craft ", " leather cowls", TaskTiers.EASY, TaskType.SKILLING,
		12, 25, StatType.Crafting, 9, ItemID.LEATHER_BOOTS, 0),
	CRAFT_LEATHER_VAMBS("Craft ", " leather vambraces", TaskTiers.EASY, TaskType.SKILLING,
		12, 25, StatType.Crafting, 11, ItemID.LEATHER_VAMBRACES, 0),
	CRAFT_LEATHER_BODY("Craft ", " leather bodies", TaskTiers.EASY, TaskType.SKILLING,
		9, 25, StatType.Crafting, 14, ItemID.LEATHER_BODY, 0),
	CRAFT_LEATHER_CHAPS("Craft ", " leather chaps", TaskTiers.EASY, TaskType.SKILLING,
		9, 25, StatType.Crafting, 18, ItemID.LEATHER_CHAPS, 0),
	CRAFT_COIF("Craft ", " coifs", TaskTiers.MEDIUM, TaskType.SKILLING,
		15, 35, StatType.Crafting, 38, ItemID.COIF, 0),
	CRAFT_SNAKESKIN_BOOTS("Craft ", " snakeskin boots", TaskTiers.MEDIUM, TaskType.SKILLING,
		15, 35, StatType.Crafting, 45, ItemID.SNAKESKIN_BOOTS, 0),
	CRAFT_GREEN_VAMBS("Craft ", " green d'hide vambs", TaskTiers.MEDIUM, TaskType.SKILLING,
		20, 30, StatType.Crafting, 57, ItemID.GREEN_DHIDE_VAMB, 0),
	CRAFT_GREEN_CHAPS("Craft ", " green d'hide chaps", TaskTiers.MEDIUM, TaskType.SKILLING,
		15, 25, StatType.Crafting, 60, ItemID.GREEN_DHIDE_CHAPS, 0),
	CRAFT_GREEN_BODY("Craft ", " green d'hide body's", TaskTiers.MEDIUM, TaskType.SKILLING,
		10, 20, StatType.Crafting, 63, ItemID.GREEN_DHIDE_BODY, 0),
	CRAFT_BLUE_VAMBS("Craft ", " blue d'hide vambs", TaskTiers.HARD, TaskType.SKILLING,
		20, 40, StatType.Crafting, 66, ItemID.BLUE_DHIDE_VAMB, 0),
	CRAFT_BLUE_CHAPS("Craft ", " blue d'hide chaps", TaskTiers.HARD, TaskType.SKILLING,
		20, 35, StatType.Crafting, 68, ItemID.BLUE_DHIDE_CHAPS, 0),
	CRAFT_BLUE_BODY("Craft ", " blue d'hide body's", TaskTiers.HARD, TaskType.SKILLING,
		15, 30, StatType.Crafting, 71, ItemID.BLUE_DHIDE_BODY, 0),
	CRAFT_RED_VAMBS("Craft ", " red d'hide vambs", TaskTiers.HARD, TaskType.SKILLING,
		25, 40, StatType.Crafting, 73, ItemID.RED_DHIDE_VAMB, 0),
	CRAFT_RED_CHAPS("Craft ", " red d'hide chaps", TaskTiers.HARD, TaskType.SKILLING,
		20, 35, StatType.Crafting, 75, ItemID.RED_DHIDE_CHAPS, 0),
	CRAFT_RED_BODY("Craft ", " red d'hide body's", TaskTiers.HARD, TaskType.SKILLING,
		15, 30, StatType.Crafting, 77, ItemID.RED_DHIDE_BODY, 0),
	CRAFT_BLACK_VAMBS("Craft ", " black d'hide vambs", TaskTiers.ELITE, TaskType.SKILLING,
		25, 40, StatType.Crafting, 79, ItemID.BLACK_DHIDE_VAMB, 0),
	CRAFT_BLACK_CHAPS("Craft ", " black d'hide chaps", TaskTiers.ELITE, TaskType.SKILLING,
		20, 35, StatType.Crafting, 82, ItemID.BLACK_DHIDE_CHAPS, 0),
	CRAFT_BLACK_BODY("Craft ", " black d'hide body's", TaskTiers.ELITE, TaskType.SKILLING,
		15, 30, StatType.Crafting, 84, ItemID.BLACK_DHIDE_BODY, 0),
	CRAFT_WATER_BSTAFF("Craft ", " water battle staves", TaskTiers.MEDIUM, TaskType.SKILLING,
		9, 20, StatType.Crafting, 54, ItemID.WATER_BATTLESTAFF, 0),
	CRAFT_EARTH_BSTAFF("Craft ", " earth battle staves", TaskTiers.HARD, TaskType.SKILLING,
		12, 26, StatType.Crafting, 58, ItemID.EARTH_BATTLESTAFF, 0),
	CRAFT_FIRE_BSTAFF("Craft ", " fire battle staves", TaskTiers.HARD, TaskType.SKILLING,
		12, 26, StatType.Crafting, 62, ItemID.FIRE_BATTLESTAFF, 0),
	CRAFT_AIR_BSTAFF("Craft ", " air battle staves", TaskTiers.HARD, TaskType.SKILLING,
		12, 26, StatType.Crafting, 66, ItemID.AIR_BATTLESTAFF, 0),
	FLETCH_BRONZE_ARROW("Fletch ", " bronze arrows", TaskTiers.EASY, TaskType.SKILLING,
		150, 300, StatType.Fletching, 1, ItemID.BRONZE_ARROW, 0),
	FLETCH_IRON_ARROW("Fletch ", " iron arrows", TaskTiers.EASY, TaskType.SKILLING,
		150, 300, StatType.Fletching, 15, ItemID.IRON_ARROW, 0),
	FLETCH_STEEL_ARROW("Fletch ", " steel arrows", TaskTiers.MEDIUM, TaskType.SKILLING,
		300, 600, StatType.Fletching, 30, ItemID.STEEL_ARROW, 0),
	FLETCH_MITHRIL_ARROW("Fletch ", " mithril arrows", TaskTiers.MEDIUM, TaskType.SKILLING,
		300, 600, StatType.Fletching, 45, ItemID.MITHRIL_ARROW, 0),
	FLETCH_ADAMANT_ARROW("Fletch ", " adamant arrows", TaskTiers.HARD, TaskType.SKILLING,
		600, 900, StatType.Fletching, 60, ItemID.ADAMANT_ARROW, 0),
	FLETCH_RUNE_ARROW("Fletch ", " rune arrows", TaskTiers.ELITE, TaskType.SKILLING,
		1200, 2500, StatType.Fletching, 75, ItemID.RUNE_ARROW, 0),
	FLETCH_AMETHYST_ARROW("Fletch ", " amethyst arrows", TaskTiers.ELITE, TaskType.SKILLING,
		900, 2000, StatType.Fletching, 82, ItemID.AMETHYST_ARROW, 0),
	FLETCH_SHORTBOW("String ", " shortbows", TaskTiers.EASY, TaskType.SKILLING,
		10, 20, StatType.Fletching, 5, ItemID.SHORTBOW, 0),
	FLETCH_OAK_SHORTBOW("String ", " oak shortbows", TaskTiers.EASY, TaskType.SKILLING,
		10, 20, StatType.Fletching, 20, ItemID.OAK_SHORTBOW, 0),
	FLETCH_WILLOW_SHORTBOW("String ", " willow shortbows", TaskTiers.MEDIUM, TaskType.SKILLING,
		12, 26, StatType.Fletching, 35, ItemID.WILLOW_SHORTBOW, 0),
	FLETCH_MAPLE_SHORTBOW("String ", " maple shortbows", TaskTiers.MEDIUM, TaskType.SKILLING,
		15, 30, StatType.Fletching, 50, ItemID.MAPLE_SHORTBOW, 0),
	FLETCH_YEW_SHORTBOW("String ", " yew shortbows", TaskTiers.HARD, TaskType.SKILLING,
		20, 40, StatType.Fletching, 65, ItemID.YEW_SHORTBOW, 0),
	FLETCH_MAGIC_SHORTBOW("String ", " magic shortbows", TaskTiers.ELITE, TaskType.SKILLING,
		25, 49, StatType.Fletching, 80, ItemID.MAGIC_SHORTBOW, 0),
	COMPLETE_A_TURAEL("Complete ", " task(s) assigned by the master Turael", TaskTiers.EASY, TaskType.PVM,
		1, 3, StatType.Slayer, 1, 0, SlayerMaster.TURAEL_ID),
	COMPLETE_A_WILDY("Complete ", " wilderness slayer tasks assigned by the master Krystilia", TaskTiers.HARD, TaskType.WILDERNESS,
		2, 4, StatType.Slayer, 1, 0, SlayerMaster.KRYSTILIA_ID),
	COMPLETE_A_NIEVE("Complete ", " task(s) assigned by the master Nieve", TaskTiers.MEDIUM, TaskType.PVM,
		1, 3, null, 85, 0, SlayerMaster.STEVE_ID),
	COMPLETE_A_KONAR("Complete ", " konar slayer task(s)", TaskTiers.MEDIUM, TaskType.PVM,
		1, 3, null, 75, 0, SlayerMaster.KONAR_ID),
	COMPLETE_A_DURADEL("Complete ", " task(s) assigned by the master Duradel", TaskTiers.MEDIUM, TaskType.PVM,
		1, 3, null, 100, 0, SlayerMaster.DURADEL_ID),
	KILL_JELLY("Kill ", " warped jellies in the catacombs", TaskTiers.MEDIUM, TaskType.PVM,
		20, 42, StatType.Slayer, 52, 0, NpcID.WARPED_JELLY),

	KILL_HYDRA("Kill ", " alchemical hydra", TaskTiers.ELITE, TaskType.PVM,
		8, 20, StatType.Slayer, 95, 0, NpcID.ALCHEMICAL_HYDRA_8622),
	KILL_CERBERUS("Kill ", " cerberus", TaskTiers.ELITE, TaskType.PVM,
		10, 25, StatType.Slayer, 91, 0, NpcID.CERBERUS),
	KILL_KRAKEN("Kill the kraken ", " times", TaskTiers.MEDIUM, TaskType.PVM,
		20, 42, StatType.Slayer, 87, 0, NpcID.KRAKEN),
	KILL_SIRE("Kill the abyssal sire ", " times", TaskTiers.HARD, TaskType.PVM,
		15, 30, StatType.Slayer, 85, 0, NpcID.ABYSSAL_SIRE_5908),
	HUNT_CRIMSON_SWIFT("Hunt ", " crimson swifts", TaskTiers.EASY, TaskType.SKILLING,
		6, 17, StatType.Hunter, 1, 0, NpcID.CRIMSON_SWIFT),
	HUNT_GOLDEN_WARBER("Hunt ", " golden warbers", TaskTiers.EASY, TaskType.SKILLING,
		6, 17, StatType.Hunter, 5, 0, NpcID.CRIMSON_SWIFT),
	HUNT_COPPER_LONGTAIL("Hunt ", " copper longtails", TaskTiers.EASY, TaskType.SKILLING,
		6, 17, StatType.Hunter, 9, 0, NpcID.COPPER_LONGTAIL),
	HUNT_TROPICAL_WAGTAIL("Hunt ", " tropical wagtails", TaskTiers.EASY, TaskType.SKILLING,
		6, 17, StatType.Hunter, 19, 0, NpcID.TROPICAL_WAGTAIL),
	HUNT_GOURMET_IMPLING("Catch ", " gourmet implings", TaskTiers.MEDIUM, TaskType.SKILLING,
		7, 18, StatType.Hunter, 38, 0, NpcID.GOURMET_IMPLING),
	HUNT_ECLECTRIC_IMPLINGS("Catch ", " eclectic implings", TaskTiers.MEDIUM, TaskType.SKILLING,
		7, 18, StatType.Hunter, 50, 0, NpcID.ECLECTIC_IMPLING),
	HUNT_NATURE_IMPLINGS("Catch ", " nature implings", TaskTiers.HARD, TaskType.SKILLING,
		10, 18, StatType.Hunter, 58, 0, NpcID.NATURE_IMPLING),
	HUNT_MAGPIE_IMPLINGS("Catch ", " magpie implings", TaskTiers.HARD, TaskType.SKILLING,
		10, 18, StatType.Hunter, 50, 0, NpcID.MAGPIE_IMPLING),
	HUNT_CHINCHOMPA("Hunt ", " grey chinchompas", TaskTiers.HARD, TaskType.SKILLING,
		25, 35, StatType.Hunter, 53, 0, NpcID.CHINCHOMPA),
	HUNT_RED_CHINCHOMPA("Hunt ", " red chinchompas", TaskTiers.HARD, TaskType.SKILLING,
		30, 50, StatType.Hunter, 63, 0, NpcID.CARNIVOROUS_CHINCHOMPA),
	HUNT_BLACK_CHINCHOMPA("Hunt ", " black chinchompas", TaskTiers.ELITE, TaskType.WILDERNESS,
		35, 60, StatType.Hunter, 73, 0, NpcID.BLACK_CHINCHOMPA),
	HUNT_SWAMP_LIZARD("Hunt ", " swamp lizards", TaskTiers.MEDIUM, TaskType.SKILLING,
		12, 20, StatType.Hunter, 29, 0, NpcID.SWAMP_LIZARD),
	HUNT_ORANGE_SALAMANDER("Hunt ", " orange salamanders", TaskTiers.MEDIUM, TaskType.SKILLING,
		12, 20, StatType.Hunter, 47, 0, NpcID.ORANGE_SALAMANDER),
	HUNT_RED_SALAMANDER("Hunt ", " red salamanders", TaskTiers.HARD, TaskType.SKILLING,
		12, 35, StatType.Hunter, 59, 0, NpcID.RED_SALAMANDER),
	HUNT_BLACK_SALAMANDER("Hunt ", " black salamanders", TaskTiers.HARD, TaskType.WILDERNESS,
		15, 39, StatType.Hunter, 67, 0, NpcID.ORANGE_SALAMANDER),
	MINE_COPPER("Mine ", " copper ore", TaskTiers.EASY, TaskType.SKILLING,
		14, 20, StatType.Mining, 1, ItemID.COPPER_ORE, 0),
	MINE_TIN("Mine ", " tin ore", TaskTiers.EASY, TaskType.SKILLING,
		14, 20, StatType.Mining, 1, ItemID.TIN_ORE, 0),
	MINE_IRON("Mine ", " iron ore", TaskTiers.EASY, TaskType.SKILLING,
		14, 25, StatType.Mining, 15, ItemID.IRON_ORE, 0),
	MINE_COAL("Mine ", " coal", TaskTiers.MEDIUM, TaskType.SKILLING,
		21, 30, StatType.Mining, 30, ItemID.COAL, 0),
	MINE_SILVER("Mine ", " silver ore", TaskTiers.MEDIUM, TaskType.SKILLING,
		21, 32, StatType.Mining, 20, ItemID.SILVER_ORE, 0),
	MINE_GOLD("Mine ", " gold ore", TaskTiers.MEDIUM, TaskType.SKILLING,
		21, 35, StatType.Mining, 1, ItemID.GOLD_ORE, 0),
	MINE_MITHRIL("Mine ", " mithril ore", TaskTiers.HARD, TaskType.SKILLING,
		30, 40, StatType.Mining, 55, ItemID.MITHRIL_ORE, 0),
	MINE_ADAMANTITE("Mine ", " adamantite ore", TaskTiers.HARD, TaskType.SKILLING,
		30, 40, StatType.Mining, 70, ItemID.ADAMANTITE_ORE, 0),

	MINE_RUNITE("Mine ", " runite ore", TaskTiers.ELITE, TaskType.SKILLING,
		15, 30, StatType.Mining, 85, ItemID.RUNITE_ORE, 0),
	MINE_AMETHYST("Mine ", " amethyst crystals", TaskTiers.ELITE, TaskType.SKILLING,
		40, 60, StatType.Mining, 92, ItemID.AMETHYST, 0),
	// Easy Smithing Tasks
	SMITH_BRONZE_BAR("Smelt ", " bronze bars", TaskTiers.EASY, TaskType.SKILLING,
		10, 17, StatType.Smithing, 1, ItemID.BRONZE_BAR, 0),
	SMITH_IRON_BAR("Smelt ", " iron bars", TaskTiers.EASY, TaskType.SKILLING,
		10, 17, StatType.Smithing, 15, ItemID.IRON_BAR, 0),
	SMITH_SILVER_BAR("Smelt ", " silver bars", TaskTiers.EASY, TaskType.SKILLING,
		11, 19, StatType.Smithing, 20, ItemID.SILVER_BAR, 0),
	SMITH_BRONZE_MED("Smith ", " bronze med helms", TaskTiers.EASY, TaskType.SKILLING,
		28, 36, StatType.Smithing, 3, ItemID.BRONZE_MED_HELM, 0),
	SMITH_BRONZE_FULL_HELM("Smith ", " bronze full helms", TaskTiers.EASY, TaskType.SKILLING,
		14, 18, StatType.Smithing, 7, ItemID.BRONZE_FULL_HELM, 0),
	SMITH_BRONZE_SCIMITAR("Smith ", " bronze scimitars", TaskTiers.EASY, TaskType.SKILLING,
		14, 18, StatType.Smithing, 5, ItemID.BRONZE_SCIMITAR, 0),
	SMITH_BRONZE_PLATEBODY("Smith ", " bronze platebodies", TaskTiers.EASY, TaskType.SKILLING,
		7, 9, StatType.Smithing, 18, ItemID.BRONZE_PLATEBODY, 0),
	SMITH_BRONZE_PLATELEG("Smith ", " bronze platelegs", TaskTiers.EASY, TaskType.SKILLING,
		9, 12, StatType.Smithing, 16, ItemID.BRONZE_PLATELEGS, 0),
	SMITH_BRONZE_KITESHIELD("Smith ", " bronze kiteshields", TaskTiers.EASY, TaskType.SKILLING,
		9, 12, StatType.Smithing, 12, ItemID.BRONZE_KITESHIELD, 0),
	SMITH_IRON_MED("Smith ", " iron med helms", TaskTiers.EASY, TaskType.SKILLING,
		28, 36, StatType.Smithing, 18, ItemID.IRON_MED_HELM, 0),
	SMITH_IRON_FULL_HELM("Smith ", " iron full helms", TaskTiers.EASY, TaskType.SKILLING,
		14, 18, StatType.Smithing, 22, ItemID.IRON_FULL_HELM, 0),
	SMITH_IRON_SCIMITAR("Smith ", " iron scimitars", TaskTiers.EASY, TaskType.SKILLING,
		14, 18, StatType.Smithing, 20, ItemID.IRON_SCIMITAR, 0),
	SMITH_IRON_PLATEBODY("Smith ", " iron platebodies", TaskTiers.EASY, TaskType.SKILLING,
		7, 9, StatType.Smithing, 33, ItemID.IRON_PLATEBODY, 0),
	SMITH_IRON_PLATELEG("Smith ", " iron platelegs", TaskTiers.EASY, TaskType.SKILLING,
		9, 12, StatType.Smithing, 31, ItemID.IRON_PLATELEGS, 0),
	SMITH_IRON_KITESHIELD("Smith ", " iron kiteshields", TaskTiers.EASY, TaskType.SKILLING,
		9, 12, StatType.Smithing, 27, ItemID.IRON_KITESHIELD, 0),
	// Medium Smithing Tasks
	SMITH_GOLD_BAR("Smelt ", " gold bars", TaskTiers.MEDIUM, TaskType.SKILLING,
		10, 17, StatType.Smithing, 40, ItemID.GOLD_BAR, 0),
	SMITH_MITH_BAR("Smelt ", " mithril bars", TaskTiers.MEDIUM, TaskType.SKILLING,
		10, 17, StatType.Smithing, 50, ItemID.MITHRIL_BAR, 0),
	SMITH_STEEL_MED("Smith ", " steel med helms", TaskTiers.MEDIUM, TaskType.SKILLING,
		28, 36, StatType.Smithing, 33, ItemID.STEEL_MED_HELM, 0),
	SMITH_STEEL_FULL_HELM("Smith ", " steel full helms", TaskTiers.MEDIUM, TaskType.SKILLING,
		14, 18, StatType.Smithing, 37, ItemID.STEEL_FULL_HELM, 0),
	SMITH_STEEL_SCIMITAR("Smith ", " steel scimitars", TaskTiers.MEDIUM, TaskType.SKILLING,
		14, 18, StatType.Smithing, 35, ItemID.STEEL_SCIMITAR, 0),
	SMITH_STEEL_PLATEBODY("Smith ", " steel platebodies", TaskTiers.MEDIUM, TaskType.SKILLING,
		7, 9, StatType.Smithing, 48, ItemID.STEEL_PLATEBODY, 0),
	SMITH_STEEL_PLATELEG("Smith ", " steel platelegs", TaskTiers.MEDIUM, TaskType.SKILLING,
		9, 12, StatType.Smithing, 46, ItemID.STEEL_PLATELEGS, 0),
	SMITH_STEEL_KITESHIELD("Smith ", " steel kiteshields", TaskTiers.MEDIUM, TaskType.SKILLING,
		9, 12, StatType.Smithing, 42, ItemID.STEEL_KITESHIELD, 0),
	SMITH_MITHRIL_MED("Smith ", " mithril med helms", TaskTiers.MEDIUM, TaskType.SKILLING,
		28, 36, StatType.Smithing, 53, ItemID.MITHRIL_MED_HELM, 0),
	SMITH_MITHRIL_DAGGER("Smith ", " mithril daggers", TaskTiers.MEDIUM, TaskType.SKILLING,
		28, 36, StatType.Smithing, 50, ItemID.MITHRIL_DAGGER, 0),
	SMITH_MITHRIL_MACE("Smith ", " mithril maces", TaskTiers.MEDIUM, TaskType.SKILLING,
		28, 36, StatType.Smithing, 52, ItemID.MITHRIL_MACE, 0),
	// Hard Smithing Tasks
	SMITH_ADAMANT_BAR("Smelt ", " adamant bars", TaskTiers.HARD, TaskType.SKILLING,
		10, 17, StatType.Smithing, 70, ItemID.ADAMANTITE_BAR, 0),
	SMITH_MITHRIL_SWORD("Smith ", " mithril swords", TaskTiers.HARD, TaskType.SKILLING,
		28, 36, StatType.Smithing, 54, ItemID.MITHRIL_SWORD, 0),
	SMITH_MITHRIL_SCIMITAR("Smith ", " mithril scimitars", TaskTiers.HARD, TaskType.SKILLING,
		14, 18, StatType.Smithing, 55, ItemID.MITHRIL_SCIMITAR, 0),
	SMITH_MITHRIL_CHAINBODY("Smith ", " mithril chainbodies", TaskTiers.HARD, TaskType.SKILLING,
		9, 12, StatType.Smithing, 61, ItemID.MITHRIL_CHAINBODY, 0),
	SMITH_MITHRIL_FULL_HELM("Smith ", " mithril full helms", TaskTiers.HARD, TaskType.SKILLING,
		14, 18, StatType.Smithing, 57, ItemID.MITHRIL_FULL_HELM, 0),
	SMITH_MITHRIL_PLATEBODY("Smith ", " mithril platebodies", TaskTiers.HARD, TaskType.SKILLING,
		7, 9, StatType.Smithing, 68, ItemID.MITHRIL_PLATEBODY, 0),
	SMITH_MITHRIL_PLATELEGS("Smith ", " mithril platelegs", TaskTiers.HARD, TaskType.SKILLING,
		9, 12, StatType.Smithing, 66, ItemID.MITHRIL_PLATELEGS, 0),
	SMITH_MITHRIL_KITESHIELD("Smith ", " mithril kiteshields", TaskTiers.HARD, TaskType.SKILLING,
		9, 12, StatType.Smithing, 62, ItemID.MITHRIL_KITESHIELD, 0),
	SMITH_MITHRIL_PLATESKIRT("Smith ", " mithril plateskirts", TaskTiers.HARD, TaskType.SKILLING,
		9, 12, StatType.Smithing, 66, ItemID.MITHRIL_PLATESKIRT, 0),
	SMITH_ADAMANT_MED("Smith ", " adamant med helms", TaskTiers.HARD, TaskType.SKILLING,
		28, 36, StatType.Smithing, 73, ItemID.ADAMANT_MED_HELM, 0),
	SMITH_ADAMANT_MACE("Smith ", " adamant maces", TaskTiers.HARD, TaskType.SKILLING,
		28, 36, StatType.Smithing, 72, ItemID.ADAMANT_MACE, 0),
	SMITH_ADAMANT_SCIMITAR("Smith ", " adamant scimitars", TaskTiers.HARD, TaskType.SKILLING,
		14, 18, StatType.Smithing, 75, ItemID.ADAMANT_SCIMITAR, 0),
	SMITH_ADAMANT_LONGSWORD("Smith ", " adamant longswords", TaskTiers.HARD, TaskType.SKILLING,
		14, 18, StatType.Smithing, 76, ItemID.ADAMANT_LONGSWORD, 0),
	// Elite Smithing Tasks
	SMITH_RUNITE_BAR("Smelt ", " runite bars", TaskTiers.ELITE, TaskType.SKILLING,
		10, 17, StatType.Smithing, 85, ItemID.RUNITE_BAR, 0),
	SMITH_ADAMANT_FULL_HELM("Smith ", " adamant full helms", TaskTiers.ELITE, TaskType.SKILLING,
		14, 18, StatType.Smithing, 77, ItemID.ADAMANT_FULL_HELM, 0),
	SMITH_ADAMANT_PLATEBODY("Smith ", " adamant platebodies", TaskTiers.ELITE, TaskType.SKILLING,
		7, 9, StatType.Smithing, 88, ItemID.ADAMANT_PLATEBODY, 0),
	SMITH_ADAMANT_PLATELEGS("Smith ", " adamant platelegs", TaskTiers.ELITE, TaskType.SKILLING,
		9, 12, StatType.Smithing, 86, ItemID.ADAMANT_PLATELEGS, 0),
	SMITH_ADAMANT_KITESHIELD("Smith ", " adamant kiteshields", TaskTiers.ELITE, TaskType.SKILLING,
		9, 12, StatType.Smithing, 82, ItemID.ADAMANT_KITESHIELD, 0),
	SMITH_ADAMANT_PLATESKIRT("Smith ", " adamant plateskirts", TaskTiers.ELITE, TaskType.SKILLING,
		9, 12, StatType.Smithing, 86, ItemID.ADAMANT_PLATESKIRT, 0),
	SMITH_RUNE_MED("Smith ", " rune med helms", TaskTiers.ELITE, TaskType.SKILLING,
		28, 36, StatType.Smithing, 88, ItemID.RUNE_MED_HELM, 0),
	SMITH_RUNE_FULL_HELM("Smith ", " rune full helms", TaskTiers.ELITE, TaskType.SKILLING,
		14, 18, StatType.Smithing, 92, ItemID.RUNE_FULL_HELM, 0),
	SMITH_RUNE_PLATEBODY("Smith ", " rune platebodies", TaskTiers.ELITE, TaskType.SKILLING,
		7, 9, StatType.Smithing, 99, ItemID.RUNE_PLATEBODY, 0),
	SMITH_RUNE_PLATELEGS("Smith ", " rune platelegs", TaskTiers.ELITE, TaskType.SKILLING,
		9, 12, StatType.Smithing, 99, ItemID.RUNE_PLATELEGS, 0),
	SMITH_RUNE_SQ_SHIELD("Smith ", " rune square shields", TaskTiers.ELITE, TaskType.SKILLING,
		14, 18, StatType.Smithing, 93, ItemID.RUNE_SQ_SHIELD, 0),
	SMITH_RUNE_KITESHIELD("Smith ", " rune kiteshields", TaskTiers.ELITE, TaskType.SKILLING,
		9, 12, StatType.Smithing, 97, ItemID.RUNE_KITESHIELD, 0),
	SMITH_RUNE_MACE("Smith ", " rune maces", TaskTiers.ELITE, TaskType.SKILLING,
		28, 36, StatType.Smithing, 87, ItemID.RUNE_MACE, 0),
	SMITH_RUNE_SCIMITAR("Smith ", " rune scimitars", TaskTiers.ELITE, TaskType.SKILLING,
		14, 18, StatType.Smithing, 90, ItemID.RUNE_SCIMITAR, 0),
	//Fishing
	FISH_SHRIMP("Fish ", " shrimps", TaskTiers.EASY, TaskType.SKILLING, 16, 32,
		StatType.Fishing, 1, ItemID.RAW_SHRIMPS, 0),
	FISH_ANCHOVIES("Fish ", " anchovies", TaskTiers.EASY, TaskType.SKILLING, 16, 32,
		StatType.Fishing, 15, ItemID.RAW_ANCHOVIES, 0),
	FISH_MONKFISH("Fish ", " monkfish", TaskTiers.HARD, TaskType.SKILLING, 68, 100,
		StatType.Fishing, 62, ItemID.RAW_MONKFISH, 0),
	//FISH_SARDINE("Fish ", " sardines", TaskTiers.EASY, TaskType.SKILLING, 16, 32,
	//   StatType.Fishing, 5, ItemID.RAW_SARDINE, 0),
	FISH_TROUT("Fish ", " trouts", TaskTiers.EASY, TaskType.SKILLING, 16, 32,
		StatType.Fishing, 20, ItemID.RAW_TROUT, 0),
	FISH_SALMON("Fish ", " salmon", TaskTiers.MEDIUM, TaskType.SKILLING, 30, 52,
		StatType.Fishing, 5, ItemID.RAW_SALMON, 0),
	FISH_ANGLER("Fish ", " anglerfish", TaskTiers.ELITE, TaskType.SKILLING, 88, 150,
		StatType.Fishing, 82, ItemID.RAW_ANGLERFISH, 0),
	FISH_SACRED_EEL("Fish ", " sacred eels", TaskTiers.ELITE, TaskType.SKILLING, 88, 150,
		StatType.Fishing, 87, 13339, 0),
	FISH_TUNA("Fish ", " tuna", TaskTiers.MEDIUM, TaskType.SKILLING, 60, 80,
		StatType.Fishing, 35, ItemID.RAW_TUNA, 0),
	FISH_SWORDFISH("Fish ", " swordfish", TaskTiers.MEDIUM, TaskType.SKILLING, 60, 80,
		StatType.Fishing, 50, ItemID.RAW_SWORDFISH, 0),
	FISH_SHARK("Fish ", " sharks", TaskTiers.ELITE, TaskType.SKILLING, 95, 140,
		StatType.Fishing, 76, ItemID.RAW_SHARK, 0),
	FISH_LOBSTER("Fish ", " lobsters", TaskTiers.MEDIUM, TaskType.SKILLING, 60, 90,
		StatType.Fishing, 40, ItemID.RAW_LOBSTER, 0),
	FISH_DARK_CRAB("Fish ", " dark crabs", TaskTiers.ELITE, TaskType.WILDERNESS, 90, 140,
		StatType.Fishing, 85, ItemID.RAW_DARK_CRAB, 0),

	COOK_SHRIMP("Cook ", " shrimps", TaskTiers.EASY, TaskType.SKILLING, 9, 25,
		StatType.Cooking, 1, ItemID.SHRIMPS, 0),
	COOK_HERRING("Cook ", " herrings", TaskTiers.EASY, TaskType.SKILLING, 12, 19,
		StatType.Cooking, 5, ItemID.HERRING, 0),
	COOK_TROUT("Cook ", " trout", TaskTiers.EASY, TaskType.SKILLING, 22, 30,
		StatType.Cooking, 15, ItemID.TROUT, 0),
	COOK_SALMON("Cook ", " salmon", TaskTiers.MEDIUM, TaskType.SKILLING, 40, 55,
		StatType.Cooking, 25, ItemID.SALMON, 0),
	COOK_TUNA("Cook ", " tuna", TaskTiers.MEDIUM, TaskType.SKILLING, 40, 55,
		StatType.Cooking, 30, ItemID.TUNA, 0),
	COOK_LOBSTER("Cook ", " lobsters", TaskTiers.MEDIUM, TaskType.SKILLING, 40, 70,
		StatType.Cooking, 40, ItemID.LOBSTER, 0),
	COOK_SWORDFISH("Cook ", " swordfish", TaskTiers.MEDIUM, TaskType.SKILLING, 40, 70,
		StatType.Cooking, 45, ItemID.SWORDFISH, 0),
	COOK_MONKFISH("Cook ", " monkfish", TaskTiers.HARD, TaskType.SKILLING, 40, 70,
		StatType.Cooking, 62, ItemID.MONKFISH, 0),
	COOK_SHARK("Cook ", " sharks", TaskTiers.ELITE, TaskType.SKILLING, 50, 70,
		StatType.Cooking, 80, ItemID.SHARK, 0),
	COOK_ANGLER("Cook ", " anglerfish", TaskTiers.ELITE, TaskType.SKILLING, 40, 70,
		StatType.Cooking, 84, ItemID.ANGLERFISH, 0),
	COOK_DARK_CRAB("Cook ", " dark crabs", TaskTiers.ELITE, TaskType.SKILLING, 40, 70,
		StatType.Cooking, 90, ItemID.DARK_CRAB, 0),
	COOK_MANTA_RAY("Cook ", " manta rays", TaskTiers.ELITE, TaskType.SKILLING, 40, 70,
		StatType.Cooking, 91, ItemID.MANTA_RAY, 0),
	BURN_LOGS("Burn ", " regular logs", TaskTiers.EASY, TaskType.SKILLING, 15,
		35, StatType.Firemaking, 1, 33000 + ItemID.LOGS, 0),
	BURN_OAK_LOGS("Burn ", " oak logs", TaskTiers.EASY, TaskType.SKILLING, 15,
		35, StatType.Firemaking, 15, 33000 + ItemID.OAK_LOGS, 0),
	BURN_WILLOW_LOGS("Burn ", " willow logs", TaskTiers.MEDIUM, TaskType.SKILLING, 25,
		50, StatType.Firemaking, 30, 33000 + ItemID.WILLOW_LOGS, 0),
	BURN_MAPLE_LOGS("Burn ", " maple logs", TaskTiers.MEDIUM, TaskType.SKILLING, 25,
		50, StatType.Firemaking, 45, 33000 + ItemID.MAPLE_LOGS, 0),
	BURN_YEW_LOGS("Burn ", " yew logs", TaskTiers.HARD, TaskType.SKILLING, 30,
		65, StatType.Firemaking, 60, 33000 + ItemID.YEW_LOGS, 0),
	BURN_MAGIC_LOGS("Burn ", " magic logs", TaskTiers.HARD, TaskType.SKILLING, 29,
		60, StatType.Firemaking, 75, 33000 + ItemID.MAGIC_LOGS, 0),
	BURN_REDWOOD_LOGS("Burn ", " redwood logs", TaskTiers.ELITE, TaskType.SKILLING, 55,
		75, StatType.Firemaking, 90, 33000 + ItemID.REDWOOD_LOGS, 0),
	CHOP_LOGS("Chop ", " regular logs", TaskTiers.EASY, TaskType.SKILLING,
		15, 35, StatType.Woodcutting, 1, ItemID.LOGS, 0),
	CHOP_OAK_LOGS("Chop ", " oak logs", TaskTiers.EASY, TaskType.SKILLING,
		15, 35, StatType.Woodcutting, 15, ItemID.OAK_LOGS, 0),
	CHOP_WILLOW_LOGS("Chop ", " willow logs", TaskTiers.MEDIUM, TaskType.SKILLING,
		29, 45, StatType.Woodcutting, 30, ItemID.WILLOW_LOGS, 0),
	CHOP_MAPLE_LOGS("Chop ", " maple logs", TaskTiers.MEDIUM, TaskType.SKILLING,
		30, 50, StatType.Woodcutting, 45, ItemID.MAPLE_LOGS, 0),
	CHOP_TEAK_LOGS("Chop ", " teak logs", TaskTiers.MEDIUM, TaskType.SKILLING,
		35, 60, StatType.Woodcutting, 35, ItemID.TEAK_LOGS, 0),
	CHOP_MAHOGANY_LOGS("Chop ", " mahogany logs", TaskTiers.HARD, TaskType.SKILLING,
		40, 70, StatType.Woodcutting, 50, ItemID.MAHOGANY_LOGS, 0),
	CHOP_YEW_LOGS("Chop ", " yew logs", TaskTiers.HARD, TaskType.SKILLING,
		40, 50, StatType.Woodcutting, 60, ItemID.YEW_LOGS, 0),
	CHOP_MAGIC_LOGS("Chop ", " magic logs", TaskTiers.ELITE, TaskType.SKILLING,
		40, 50, StatType.Woodcutting, 75, ItemID.MAGIC_LOGS, 0),
	CHOP_REDWOOD_LOGS("Chop ", " redwood logs", TaskTiers.ELITE, TaskType.SKILLING,
		60, 100, StatType.Woodcutting, 90, ItemID.REDWOOD_LOGS, 0),

	KILL_SKOTIZO("Kill Skotizo ", " times", TaskTiers.HARD, TaskType.PVM, 2, 4,
		null, 100, 0, NpcID.SKOTIZO),
	KILL_REVENANT("Kill Revs ", " times", TaskTiers.HARD, TaskType.WILDERNESS, 60, 96,
		null, 50, 0, "revenant"),
	KILL_GALVEK("Kill Galvek ", " times", TaskTiers.ELITE, TaskType.PVM, 3, 7,
		null, 110, 0, "galvek"),

	KILL_ARGENTAVIS("Kill Argentavis ", " times", TaskTiers.HARD, TaskType.PVM, 10, 29,
		null, 80, 0, "argentavis"),

	KILL_OPHIDIA("Kill Ophidia ", " times", TaskTiers.ELITE, TaskType.PVM, 5, 10,
		null, 80, 0, NpcID.MUTANT_TARN),
	COMPLETE_GAUNTLET("Complete Gauntlet ", " times", TaskTiers.ELITE, TaskType.PVM, 3, 7,
		null, 100, 0, "gauntlet"),
	COMPLETE_CORRUPTED_GAUNTLET("Complete the CG ", " times", TaskTiers.ELITE, TaskType.PVM, 3, 7,
		null, 100, 0, "corruptedGauntlet"),
	COMPLETE_COX("Complete CoX ", " times", TaskTiers.ELITE, TaskType.PVM, 1, 1,
		null, 100, 0, "cox"),
	COMPLETE_TOB("Complete ToB ", " times", TaskTiers.ELITE, TaskType.PVM, 1, 1,
		null, 100, 0, "tob"),
	KILL_NIGHTMARE("Kill Nightmare ", " times", TaskTiers.ELITE, TaskType.PVM, 2, 5,
		null, 100, 0, "nightmare"),
	KILL_NEX("Kill Nex ", " times", TaskTiers.ELITE, TaskType.PVM, 2, 5,
		null, 100, 0, "nex"),
	KILL_BANDOS("Kill Graardor ", " times", TaskTiers.HARD, TaskType.PVM, 10, 29,
		null, 90, 0, NpcID.GENERAL_GRAARDOR),
	KILL_ZAMMY("Kill K'ril ", " times", TaskTiers.HARD, TaskType.PVM, 10, 29,
		null, 90, 0, NpcID.KRIL_TSUTSAROTH),
	KILL_ARMA("Kill Kree ", " times", TaskTiers.HARD, TaskType.PVM, 10, 29,
		null, 90, 0, NpcID.KREEARRA),
	KILL_SARA("Kill Zilyana ", " times", TaskTiers.HARD, TaskType.PVM, 10, 29,
		null, 90, 0, NpcID.COMMANDER_ZILYANA),
	KILL_MOLE("Kill the Mole ", " times", TaskTiers.ELITE, TaskType.PVM, 8, 20,
		null, 80, 0, NpcID.GIANT_MOLE),
	KILL_ZULRAH("Kill Zulrah ", " times", TaskTiers.HARD, TaskType.PVM, 15, 30,
		null, 100, 0, "zulrah"),
	KILL_VORKATH("Kill Vork ", " times", TaskTiers.HARD, TaskType.PVM, 10, 25,
		null, 100, 0, NpcID.VORKATH),
	KILL_DAGANNOTH_PRIME("Kill dag prime ", " times", TaskTiers.ELITE, TaskType.PVM, 8,
		20, null, 85, 0, NpcID.DAGANNOTH_PRIME),
	KILL_DAGANNOTH_SUPREME("Kill dag supreme ", " times", TaskTiers.ELITE, TaskType.PVM, 8,
		20, null, 85, 0, NpcID.DAGANNOTH_SUPREME),
	KILL_DAGANNOTH_REX("Kill dag rex ", " times", TaskTiers.ELITE, TaskType.PVM, 8,
		20, null, 85, 0, NpcID.DAGANNOTH_REX),
	KILL_KQ("Kill the KQ ", " times", TaskTiers.ELITE, TaskType.PVM, 8,
		20, null, 95, 0, "kalphite queen"),

	KILL_CORP("Kill Corp ", " times", TaskTiers.ELITE, TaskType.PVM, 8, 20,
		null, 110, 0, NpcID.CORPOREAL_BEAST),
	KILL_KBD("Kill the KBD ", " times", TaskTiers.ELITE, TaskType.PVM, 8,
		20, null, 85, 0, NpcID.KING_BLACK_DRAGON),
	KILL_LIZARDMAN_SHAMAN("Kill liz shamans ", " times", TaskTiers.MEDIUM, TaskType.PVM, 45,
		95, null, 75, 0, "lizardman shaman"),
	KILL_CHAOS_DRUID("Kill ", " chaos druids", TaskTiers.EASY, TaskType.PVM, 12, 35,
		null, 10, 0, "chaos druid"),
	KILL_ROCK_CRAB("Kill ", " rock crabs", TaskTiers.EASY, TaskType.PVM, 12, 35,
		null, 10, 0, "rock crab"),
	KILL_SAND_CRAB("Kill ", " sand crabs", TaskTiers.EASY, TaskType.PVM, 12, 35,
		null, 30, 0, "sand crab"),
	KILL_YAK("Kill ", " yaks", TaskTiers.EASY, TaskType.PVM, 12, 35,
		null, 10, 0, "yak"),
	KILL_CHICKEN("Kill ", " chickens", TaskTiers.EASY, TaskType.PVM, 20, 45,
		null, 3, 0, "chicken"),
	KILL_EXPERIMENT("Kill ", " experiments", TaskTiers.EASY, TaskType.PVM, 12, 35,
		null, 10, 0, "experiment"),
	KILL_AMMONITE_CRAB("Kill ", " ammonite crabs", TaskTiers.EASY, TaskType.PVM, 12, 40,
		null, 50, 0, "ammonite crab"),
	KILL_BRUTAL_BLACK_DRAGON("Kill ", " brutal black dragons", TaskTiers.MEDIUM, TaskType.PVM, 16,

		55, null, 75, 0, "brutal black"),
	KILL_VETION("Kill vet'ion ", " times", TaskTiers.HARD, TaskType.WILDERNESS, 10, 20,
		null, 100, 0, NpcID.VETION_REBORN),
	KILL_CALLISTO("Kill callisto ", " times", TaskTiers.ELITE, TaskType.PVM, 25, 50,
		null, 100, 0, 6609),
	KILL_SCORPIA("Kill scorpia ", " times", TaskTiers.ELITE, TaskType.PVM, 25, 50,
		null, 90, 0, NpcID.SCORPIA),
	KILL_VENENATIS("Kill venenatis ", " times", TaskTiers.HARD, TaskType.WILDERNESS, 10, 20,
		null, 100, 0, 6610),
	KILL_CHAOS_FANATIC("Kill the chaos fanatic ", " times", TaskTiers.MEDIUM, TaskType.WILDERNESS, 10, 20,
		null, 50, 0, NpcID.CHAOS_FANATIC),
	KILL_CHAOS_ELEMENTAL("Kill the chaos elemental ", " times", TaskTiers.ELITE, TaskType.PVM, 10, 20,null, 80, 0, NpcID.CHAOS_ELEMENTAL),
	KILL_CRAZY_ARCH("Kill the crazy archaeologist  ", " times", TaskTiers.EASY, TaskType.WILDERNESS, 10, 20, null, 50, 0, NpcID.CRAZY_ARCHAEOLOGIST),
	KILL_GREEN_DRAG("Kill ", " green dragons", TaskTiers.EASY, TaskType.WILDERNESS, 16, 35,	null, 60, 0, "green dragon"),
	KILL_LAVA_DRAG("Kill ", " lava dragons", TaskTiers.MEDIUM, TaskType.WILDERNESS, 21, 45, null, 60, 0, "lava dragon"),
	COMPLETE_DURADEL_TASK("Complete ", " slayer tasks from Duradel", TaskTiers.HARD, TaskType.PVM, 1, 3, null, 100, 0, SlayerMaster.DURADEL_ID),
	COMPLETE_NIEVE_TASK("Complete ", " slayer tasks from Nieve", TaskTiers.HARD, TaskType.PVM, 3, 3,	null, 85, 0, SlayerMaster.STEVE_ID),
	COMPLETE_KRYSTILIA_TASK("Complete ", " slayer tasks from Krystilia", TaskTiers.MEDIUM, TaskType.PVM, 1, 3, null, 3, 0, SlayerMaster.KRYSTILIA_ID),
	COMPLETE_TURAEL_TASK("Complete ", " slayer tasks from Turael", TaskTiers.EASY, TaskType.PVM, 3, 5,	null, 1, 0, SlayerMaster.TURAEL_ID),
	COMPLETE_VANNAKA_TASK("Complete ", " slayer tasks from Vannaka", TaskTiers.MEDIUM, TaskType.PVM, 3, 5, null, 40, 0, SlayerMaster.VANNAKA_ID),
	COMPLETE_KONAR_TASKS("Complete ", " konar slayer tasks", TaskTiers.HARD, TaskType.PVM, 3, 5, null, 75, 0, SlayerMaster.KONAR_ID),

	;
	public String description;
	public String description_2;
	TaskTiers tier;
	TaskType type;
	int minimumAmount;
	int maximumAmount;
	StatType statType;
	int levelReq;

	int resourceId;
	Object npcId;

	PerkTasks(String description, String description_2, TaskTiers tier, TaskType type, int minimumAmount, int maximumAmount,
	          StatType statType, int levelReq, int resourceId, Object npcId) {
		this.description = description;
		this.description_2 = description_2;
		this.tier = tier;
		this.type = type;
		this.minimumAmount = minimumAmount;
		this.maximumAmount = maximumAmount;
		this.statType = statType;
		this.levelReq = levelReq;
		this.resourceId = resourceId;
		this.npcId = npcId;
	}

	public static final PerkTasks[] VALUES = values();


	public enum TaskTiers {
		EASY,
		MEDIUM,
		HARD,
		ELITE;

		public static final TaskTiers[] VALUES = values();
	}

	public enum TaskType {
		PVM,
		PVP,
		SKILLING,
		WILDERNESS;

		public static final TaskType[] VALUES = values();
	}
}
