package io.ruin.model.activities.perktree;

public enum PerkShop {
	DAMAGE_REFLECT(Perks.DAMAGE_REFLECT, 13, 10),
	SPEEDY_STRIKES(Perks.SPEEDY_STRIKES, 13, 10),
	DOUBLE_TAP(Perks.DOUBLE_TAP, 13, 10),
	ARCANE_ENHANCEMENT(Perks.ARCANE_ENHANCEMENT, 13, 10),
	THE_SOULSPLIT(Perks.THE_SOULSPLIT, 18, 14),
	RECURRENT_DAMAGE(Perks.RECURRENT_DAMAGE, 14, 14),
	BLESSED_BOLTS(Perks.BLESSED_BOLTS, 11, 9),
	BLOOD_SACRIFICE(Perks.BLOOD_SACRIFICE, 8, 7),
	ACCURATE_BLOWS(Perks.ACCURATE_BLOWS, 8, 7),
	TAKE_YOUR_TIME(Perks.TAKE_YOUR_TIME, 8, 7),
	THE_CRUSHER(Perks.THE_CRUSHER, 7, 7),
	THE_SLASHER(Perks.THE_SLASHER, 7, 7),
	THE_STABBER(Perks.THE_STABBER, 7, 7),
	ENHANCED_MAGICAL_WEAPONS(Perks.ENHANCED_MAGICAL_WEAPONS, 9, 9),
	SKILLED_RANGER(Perks.SKILLED_RANGER, 9, 9),
	FINEST_WIZARDRY(Perks.FINEST_WIZARDRY, 9, 9),
	EFFICIENT_CHOP(Perks.THE_EFFICIENT_CHOP, 6, 6),
	SPEED_FISHER(Perks.SPEED_FISHER, 6, 6),
	ART_OF_MINING(Perks.THE_ART_OF_MINING, 6, 6),
	HUNTING_IN_ITS_TRUE_FORM(Perks.HUNTING_IN_ITS_TRUE_FORM, 6, 6),
	TAKING_IT_ON_THE_CHIN(Perks.TAKING_IT_ON_THE_CHIN, 7, 6),
	MASTER_THIEF(Perks.MASTER_THIEF, 7, 6),
	A_SLAYING_EXPERIENCE(Perks.A_SLAYING_EXPERIENCE, 9, 8),
	ONE_WITH_THE_RUNES(Perks.ONE_WITH_THE_RUNES, 6, 6),
	DANCING_IN_THE_YIELDS(Perks.DANCING_IN_THE_YIELDS, 6, 6),
	KITCHEN_EXPERT(Perks.KITCHEN_EXPERT, 5, 6),
	SMITHING_DYNASTY(Perks.SMITHING_DYNASTY, 6, 6),
	THE_ARSONIST(Perks.THE_ARSONIST, 5, 6),
	RUNNING_PAYS(Perks.RUNNING_PAYS, 5, 6),
	PACKS_N_POTIONS(Perks.PACKS_N_POTIONS, 8, 7),
	ARTS_N_CRAFTS(Perks.ARTS_N_CRAFTS, 6, 6),
	FLETCHING_DREAMS(Perks.FLETCHING_DREAMS, 6, 6),
	BOB_THE_BUILDER(Perks.BOB_THE_BUILDER, 6, 6),
	EXPERIENCE_ENHANCER(Perks.EXPERIENCE_ENHANCER, 8, 9),
	CONSERVATIVE_PRAYERS(Perks.CONSERVATIVE_PRAYERS, 11, 11),
	GOD_WARS_VETERAN(Perks.GOD_WARS_VETERAN, 8, 9),
	POTIONS_MASTER(Perks.POTIONS_MASTER, 11, 10),
	FOOD_CONNOISSEUR(Perks.FOOD_CONNOISSEUR, 11, 10),
	LAYING_TO_REST(Perks.LAYING_TO_REST, 10, 9),
	RAIDING_RESTORATIONS(Perks.RAIDING_RESTORATIONS, 15, 13),
	FAST_EATER(Perks.FAST_EATER, 11, 11),
	THE_DRAGON_SLAYER(Perks.THE_DRAGON_SLAYER, 11, 9),
	SNAKE_CHARMER(Perks.SNAKE_CHARMER, 10, 9),
	GOLDEN_GAUNTLET(Perks.THE_GOLDEN_GAUNTLET, 10, 9),
	VANQUISHED_FOE(Perks.VANQUISHED_FOE, 11, 9),
	WILDERNESS_HUNTER(Perks.WILDERNESS_HUNTER, 10, 9),
	THE_SPECIAL_ATTACKER(Perks.THE_SPECIAL_ATTACK, 13, 9),
	THE_ALCHEMIST(Perks.THE_ALCHEMIST, 12, 10),
	SECURING_THE_BAG(Perks.SECURING_THE_BAG, 19, 17),
	THE_PET_HUNTER(Perks.THE_PET_HUNTER, 17, 15),
	CRIMSON_CHIN(Perks.CRIMSON_CHIN, 12, 11),
	;

	Perks perk;
	int price;
	int originalUpgradePrice;

	PerkShop(Perks perk, int price, int originalUpradePrice) {
		this.perk = perk;
		this.price = price;
		this.originalUpgradePrice = originalUpradePrice;
	}

	public Perks getPerk() {
		return this.perk;
	}

	public int getPrice() {
		return this.price;
	}

	public int getOriginalUpgradePrice() {
		return this.originalUpgradePrice;
	}
}
