package io.ruin.model.inter;


/**
 * Represents a group-child {@link io.ruin.cache.iftype.Component} relationship.
 */
public enum ComponentInfo {
	FAIRY_RING_LEFT_ORB_CLOCKWISE(ComponentID.FAIRY_RING_GROUP_ID, ComponentID.FairyRing.LEFT_ORB_CLOCKWISE),
	FAIRY_RING_LEFT_ORB_COUNTER_CLOCKWISE(ComponentID.FAIRY_RING_GROUP_ID, ComponentID.FairyRing.LEFT_ORB_COUNTER_CLOCKWISE),
	FAIRY_RING_MIDDLE_ORB_CLOCKWISE(ComponentID.FAIRY_RING_GROUP_ID, ComponentID.FairyRing.MIDDLE_ORB_CLOCKWISE),
	FAIRY_RING_MIDDLE_ORB_COUNTER_CLOCKWISE(ComponentID.FAIRY_RING_GROUP_ID, ComponentID.FairyRing.MIDDLE_ORB_COUNTER_CLOCKWISE),
	FAIRY_RING_RIGHT_ORB_CLOCKWISE(ComponentID.FAIRY_RING_GROUP_ID, ComponentID.FairyRing.RIGHT_ORB_CLOCKWISE),
	FAIRY_RING_RIGHT_ORB_COUNTER_CLOCKWISE(ComponentID.FAIRY_RING_GROUP_ID, ComponentID.FairyRing.RIGHT_ORB_COUNTER_CLOCKWISE),

	FAIRY_RING_TELEPORT_BUTTON(ComponentID.FAIRY_RING_GROUP_ID, ComponentID.FairyRing.TELEPORT_BUTTON),

	WORLD_SWITCHER_BUTTON(ComponentID.LOGOUT_PANEL_ID, ComponentID.LogoutPanel.WORLD_SWITCHER_BUTTON),
	LOGOUT_BUTTON(ComponentID.LOGOUT_PANEL_ID, ComponentID.LogoutPanel.LOGOUT_BUTTON),

	INVENTORY(ComponentID.INVENTORY_GROUP_ID, 0),
	FRIENDS_LIST(ComponentID.FRIENDS_LIST_GROUP_ID, 0),
	CLAN_CHAT(ComponentID.CLAN_CHAT_GROUP_ID, 0),
	RAIDING_PARTY(ComponentID.RAIDING_PARTY_GROUP_ID, 0),

	WORLD_MAP_VIEW(ComponentID.WORLD_MAP_GROUP_ID, ComponentID.WorldMap.MAPVIEW),
	WORLD_MAP_OVERVIEW_MAP(ComponentID.WORLD_MAP_GROUP_ID, ComponentID.WorldMap.OVERVIEW_MAP),
	WORLD_MAP_SEARCH(ComponentID.WORLD_MAP_GROUP_ID, ComponentID.WorldMap.SEARCH),
	WORLD_MAP_SURFACE_SELECTOR(ComponentID.WORLD_MAP_GROUP_ID, ComponentID.WorldMap.SURFACE_SELECTOR),
	WORLD_MAP_EXIT(ComponentID.WORLD_MAP_GROUP_ID, ComponentID.WorldMap.EXIT),
	WORLD_MAP_OPTION(ComponentID.WORLD_MAP_MENU_GROUP_ID, ComponentID.WorldMap.OPTION),
	WORLD_MAP_BUTTON_BORDER(ComponentID.MINIMAP_GROUP_ID, ComponentID.Minimap.WORLDMAP_ORB),

	CLUE_SCROLL_TEXT(ComponentID.CLUE_SCROLL_GROUP_ID, ComponentID.Cluescroll.CLUE_TEXT),
	CLUE_SCROLL_REWARD_ITEM_CONTAINER(ComponentID.CLUE_SCROLL_REWARD_GROUP_ID, ComponentID.Cluescroll.CLUE_SCROLL_ITEM_CONTAINER),

	EQUIPMENT(ComponentID.EQUIPMENT_GROUP_ID, 0),
	EQUIPMENT_INVENTORY_ITEMS_CONTAINER(ComponentID.EQUIPMENT_INVENTORY_GROUP_ID, ComponentID.Equipment.INVENTORY_ITEM_CONTAINER),

	EQUIPMENT_HELMET(ComponentID.EQUIPMENT_GROUP_ID, ComponentID.Equipment.HELMET),
	EQUIPMENT_CAPE(ComponentID.EQUIPMENT_GROUP_ID, ComponentID.Equipment.CAPE),
	EQUIPMENT_AMULET(ComponentID.EQUIPMENT_GROUP_ID, ComponentID.Equipment.AMULET),
	EQUIPMENT_WEAPON(ComponentID.EQUIPMENT_GROUP_ID, ComponentID.Equipment.WEAPON),
	EQUIPMENT_BODY(ComponentID.EQUIPMENT_GROUP_ID, ComponentID.Equipment.BODY),
	EQUIPMENT_SHIELD(ComponentID.EQUIPMENT_GROUP_ID, ComponentID.Equipment.SHIELD),
	EQUIPMENT_LEGS(ComponentID.EQUIPMENT_GROUP_ID, ComponentID.Equipment.LEGS),
	EQUIPMENT_GLOVES(ComponentID.EQUIPMENT_GROUP_ID, ComponentID.Equipment.GLOVES),
	EQUIPMENT_BOOTS(ComponentID.EQUIPMENT_GROUP_ID, ComponentID.Equipment.BOOTS),
	EQUIPMENT_RING(ComponentID.EQUIPMENT_GROUP_ID, ComponentID.Equipment.RING),
	EQUIPMENT_AMMO(ComponentID.EQUIPMENT_GROUP_ID, ComponentID.Equipment.AMMO),

	EMOTE_WINDOW(ComponentID.EMOTES_GROUP_ID, ComponentID.Emotes.EMOTE_WINDOW),
	EMOTE_CONTAINER(ComponentID.EMOTES_GROUP_ID, ComponentID.Emotes.EMOTE_CONTAINER),
	EMOTE_SCROLLBAR(ComponentID.EMOTES_GROUP_ID, ComponentID.Emotes.EMOTE_SCROLLBAR),

	MUSIC_WINDOW(ComponentID.MUSIC_GROUP_ID, ComponentID.Music.CONTAINER),
	MUSIC_TRACK_LIST(ComponentID.MUSIC_GROUP_ID, ComponentID.Music.LIST),
	MUSIC_TRACK_SCROLLBAR(ComponentID.MUSIC_GROUP_ID, ComponentID.Music.SCROLLBAR),

	DIARY_QUEST_WIDGET_TITLE(ComponentID.DIARY_QUEST_GROUP_ID, ComponentID.Diary.DIARY_TITLE),
	DIARY_QUEST_WIDGET_TEXT(ComponentID.DIARY_QUEST_GROUP_ID, ComponentID.Diary.DIARY_TEXT),

	MINIGAME_DIALOG(ComponentID.DIALOG_MINIGAME_GROUP_ID, 0),
	MINIGAME_DIALOG_TEXT(ComponentID.DIALOG_MINIGAME_GROUP_ID, ComponentID.MessageDialogueComps.TEXT),
	PEST_CONTROL_EXCHANGE_WINDOW(ComponentID.PEST_CONTROL_EXCHANGE_WINDOW_GROUP_ID, 0),
	PEST_CONTROL_EXCHANGE_WINDOW_POINTS(ComponentID.PEST_CONTROL_EXCHANGE_WINDOW_GROUP_ID, ComponentID.PestControlExchangeWindow.POINTS),
	PEST_CONTROL_BOAT_INFO(ComponentID.PEST_CONTROL_BOAT_GROUP_ID, ComponentID.PestControlBoat.INFO),
	PEST_CONTROL_BOAT_INFO_POINTS(ComponentID.PEST_CONTROL_BOAT_GROUP_ID, ComponentID.PestControlBoat.POINTS),
	PEST_CONTROL_INFO(ComponentID.PEST_CONTROL_GROUP_ID, ComponentID.PestControl.INFO),
	PEST_CONTROL_INFO_TIME(ComponentID.PEST_CONTROL_GROUP_ID, ComponentID.PestControl.TIME),
	PEST_CONTROL_PURPLE_SHIELD(ComponentID.PEST_CONTROL_GROUP_ID, ComponentID.PestControl.PURPLE_SHIELD),
	PEST_CONTROL_BLUE_SHIELD(ComponentID.PEST_CONTROL_GROUP_ID, ComponentID.PestControl.BLUE_SHIELD),
	PEST_CONTROL_YELLOW_SHIELD(ComponentID.PEST_CONTROL_GROUP_ID, ComponentID.PestControl.YELLOW_SHIELD),
	PEST_CONTROL_RED_SHIELD(ComponentID.PEST_CONTROL_GROUP_ID, ComponentID.PestControl.RED_SHIELD),
	PEST_CONTROL_PURPLE_HEALTH(ComponentID.PEST_CONTROL_GROUP_ID, ComponentID.PestControl.PURPLE_HEALTH),
	PEST_CONTROL_BLUE_HEALTH(ComponentID.PEST_CONTROL_GROUP_ID, ComponentID.PestControl.BLUE_HEALTH),
	PEST_CONTROL_YELLOW_HEALTH(ComponentID.PEST_CONTROL_GROUP_ID, ComponentID.PestControl.YELLOW_HEALTH),
	PEST_CONTROL_RED_HEALTH(ComponentID.PEST_CONTROL_GROUP_ID, ComponentID.PestControl.RED_HEALTH),
	PEST_CONTROL_PURPLE_ICON(ComponentID.PEST_CONTROL_GROUP_ID, ComponentID.PestControl.PURPLE_ICON),
	PEST_CONTROL_BLUE_ICON(ComponentID.PEST_CONTROL_GROUP_ID, ComponentID.PestControl.BLUE_ICON),
	PEST_CONTROL_YELLOW_ICON(ComponentID.PEST_CONTROL_GROUP_ID, ComponentID.PestControl.YELLOW_ICON),
	PEST_CONTROL_RED_ICON(ComponentID.PEST_CONTROL_GROUP_ID, ComponentID.PestControl.RED_ICON),
	PEST_CONTROL_ACTIVITY_BAR(ComponentID.PEST_CONTROL_GROUP_ID, ComponentID.PestControl.ACTIVITY_BAR),
	PEST_CONTROL_ACTIVITY_PROGRESS(ComponentID.PEST_CONTROL_GROUP_ID, ComponentID.PestControl.ACTIVITY_PROGRESS),

	VOLCANIC_MINE_GENERAL_INFOBOX_GROUP(ComponentID.VOLCANIC_MINE_GROUP_ID, ComponentID.VolcanicMine.GENERAL_INFOBOX_GROUP_ID),
	VOLCANIC_MINE_TIME_LEFT(ComponentID.VOLCANIC_MINE_GROUP_ID, ComponentID.VolcanicMine.TIME_LEFT),
	VOLCANIC_MINE_POINTS(ComponentID.VOLCANIC_MINE_GROUP_ID, ComponentID.VolcanicMine.POINTS),
	VOLCANIC_MINE_STABILITY(ComponentID.VOLCANIC_MINE_GROUP_ID, ComponentID.VolcanicMine.STABILITY),
	VOLCANIC_MINE_PLAYER_COUNT(ComponentID.VOLCANIC_MINE_GROUP_ID, ComponentID.VolcanicMine.PLAYER_COUNT),
	VOLCANIC_MINE_VENTS_INFOBOX_GROUP(ComponentID.VOLCANIC_MINE_GROUP_ID, ComponentID.VolcanicMine.VENTS_INFOBOX_GROUP_ID),
	VOLCANIC_MINE_VENT_A_PERCENTAGE(ComponentID.VOLCANIC_MINE_GROUP_ID, ComponentID.VolcanicMine.VENT_A_PERCENTAGE),
	VOLCANIC_MINE_VENT_B_PERCENTAGE(ComponentID.VOLCANIC_MINE_GROUP_ID, ComponentID.VolcanicMine.VENT_B_PERCENTAGE),
	VOLCANIC_MINE_VENT_C_PERCENTAGE(ComponentID.VOLCANIC_MINE_GROUP_ID, ComponentID.VolcanicMine.VENT_C_PERCENTAGE),
	VOLCANIC_MINE_VENT_A_STATUS(ComponentID.VOLCANIC_MINE_GROUP_ID, ComponentID.VolcanicMine.VENT_A_STATUS),
	VOLCANIC_MINE_VENT_B_STATUS(ComponentID.VOLCANIC_MINE_GROUP_ID, ComponentID.VolcanicMine.VENT_B_STATUS),
	VOLCANIC_MINE_VENT_C_STATUS(ComponentID.VOLCANIC_MINE_GROUP_ID, ComponentID.VolcanicMine.VENT_C_STATUS),

	FRIEND_CHAT_TITLE(ComponentID.FRIENDS_LIST_GROUP_ID, ComponentID.FriendList.TITLE),

	IGNORE_TITLE(ComponentID.IGNORE_LIST_GROUP_ID, ComponentID.IgnoreList.TITLE),

	EXPLORERS_RING_ALCH_INVENTORY(ComponentID.EXPLORERS_RING_ALCH_GROUP_ID, ComponentID.ExplorersRing.INVENTORY),

	CLAN_CHAT_TITLE(ComponentID.CLAN_CHAT_GROUP_ID, ComponentID.ClanChat.TITLE),
	CLAN_CHAT_NAME(ComponentID.CLAN_CHAT_GROUP_ID, ComponentID.ClanChat.NAME),
	CLAN_CHAT_OWNER(ComponentID.CLAN_CHAT_GROUP_ID, ComponentID.ClanChat.OWNER),
	CLAN_CHAT_LIST(ComponentID.CLAN_CHAT_GROUP_ID, ComponentID.ClanChat.LIST),

	BANK_CONTAINER(ComponentID.BANK_GROUP_ID, ComponentID.Bank.BANK_CONTAINER),
	BANK_SEARCH_BUTTON_BACKGROUND(ComponentID.BANK_GROUP_ID, ComponentID.Bank.SEARCH_BUTTON_BACKGROUND),
	BANK_ITEM_CONTAINER(ComponentID.BANK_GROUP_ID, ComponentID.Bank.ITEM_CONTAINER),
	BANK_INVENTORY_ITEMS_CONTAINER(ComponentID.BANK_INVENTORY_GROUP_ID, ComponentID.Bank.INVENTORY_ITEM_CONTAINER),
	BANK_TITLE_BAR(ComponentID.BANK_GROUP_ID, ComponentID.Bank.BANK_TITLE_BAR),
	BANK_INCINERATOR(ComponentID.BANK_GROUP_ID, ComponentID.Bank.INCINERATOR),
	BANK_INCINERATOR_CONFIRM(ComponentID.BANK_GROUP_ID, ComponentID.Bank.INCINERATOR_CONFIRM),
	BANK_CONTENT_CONTAINER(ComponentID.BANK_GROUP_ID, ComponentID.Bank.CONTENT_CONTAINER),
	BANK_DEPOSIT_EQUIPMENT(ComponentID.BANK_GROUP_ID, ComponentID.Bank.DEPOSIT_EQUIPMENT),
	BANK_DEPOSIT_INVENTORY(ComponentID.BANK_GROUP_ID, ComponentID.Bank.DEPOSIT_INVENTORY),
	BANK_TAB_CONTAINER(ComponentID.BANK_GROUP_ID, ComponentID.Bank.TAB_CONTAINER),

	GRAND_EXCHANGE_WINDOW_CONTAINER(ComponentID.GRAND_EXCHANGE_GROUP_ID, ComponentID.GrandExchange.WINDOW_CONTAINER),
	GRAND_EXCHANGE_OFFER_CONTAINER(ComponentID.GRAND_EXCHANGE_GROUP_ID, ComponentID.GrandExchange.OFFER_CONTAINER),
	GRAND_EXCHANGE_OFFER_TEXT(ComponentID.GRAND_EXCHANGE_GROUP_ID, ComponentID.GrandExchange.OFFER_DESCRIPTION),
	GRAND_EXCHANGE_OFFER_PRICE(ComponentID.GRAND_EXCHANGE_GROUP_ID, ComponentID.GrandExchange.OFFER_PRICE),

	GRAND_EXCHANGE_INVENTORY_ITEMS_CONTAINER(ComponentID.GRAND_EXCHANGE_INVENTORY_GROUP_ID, ComponentID.GrandExchangeInventory.INVENTORY_ITEM_CONTAINER),

	DEPOSIT_BOX_INVENTORY_ITEMS_CONTAINER(ComponentID.DEPOSIT_BOX_GROUP_ID, ComponentID.DepositBox.INVENTORY_ITEM_CONTAINER),

	SHOP_ITEMS_CONTAINER(ComponentID.SHOP_GROUP_ID, ComponentID.Shop.ITEMS_CONTAINER),
	SHOP_INVENTORY_ITEMS_CONTAINER(ComponentID.SHOP_INVENTORY_GROUP_ID, ComponentID.Shop.INVENTORY_ITEM_CONTAINER),

	SMITHING_INVENTORY_ITEMS_CONTAINER(ComponentID.SMITHING_GROUP_ID, ComponentID.Smithing.INVENTORY_ITEM_CONTAINER),

	GUIDE_PRICES_ITEMS_CONTAINER(ComponentID.GUIDE_PRICES_GROUP_ID, ComponentID.GuidePrices.ITEM_CONTAINER),
	GUIDE_PRICES_INVENTORY_ITEMS_CONTAINER(ComponentID.GUIDE_PRICES_INVENTORY_GROUP_ID, ComponentID.GuidePrices.INVENTORY_ITEM_CONTAINER),

	RUNE_POUCH_ITEM_CONTAINER(ComponentID.RUNE_POUCH_GROUP_ID, 0),

	MINIMAP_ORBS(ComponentID.MINIMAP_GROUP_ID, 0),
	MINIMAP_XP_ORB(ComponentID.MINIMAP_GROUP_ID, ComponentID.Minimap.XP_ORB),
	MINIMAP_PRAYER_ORB(ComponentID.MINIMAP_GROUP_ID, ComponentID.Minimap.PRAYER_ORB),
	MINIMAP_QUICK_PRAYER_ORB(ComponentID.MINIMAP_GROUP_ID, ComponentID.Minimap.QUICK_PRAYER_ORB),
	MINIMAP_PRAYER_ORB_TEXT(ComponentID.MINIMAP_GROUP_ID, ComponentID.Minimap.PRAYER_ORB_TEXT),
	MINIMAP_RUN_ORB(ComponentID.MINIMAP_GROUP_ID, ComponentID.Minimap.RUN_ORB),
	MINIMAP_TOGGLE_RUN_ORB(ComponentID.MINIMAP_GROUP_ID, ComponentID.Minimap.TOGGLE_RUN_ORB),
	MINIMAP_RUN_ORB_TEXT(ComponentID.MINIMAP_GROUP_ID, ComponentID.Minimap.RUN_ORB_TEXT),
	MINIMAP_HEALTH_ORB(ComponentID.MINIMAP_GROUP_ID, ComponentID.Minimap.HEALTH_ORB),
	MINIMAP_SPEC_ORB(ComponentID.MINIMAP_GROUP_ID, ComponentID.Minimap.SPEC_ORB),
	MINIMAP_WORLDMAP_ORB(ComponentID.MINIMAP_GROUP_ID, ComponentID.Minimap.WORLDMAP_ORB),
	MINIMAP_WORLD_ORB(ComponentID.MINIMAP_GROUP_ID, ComponentID.Minimap.WORLDMAP_ORB),

	LMS_INFO(ComponentID.LMS_GROUP_ID, ComponentID.Lms.INFO),
	LMS_KDA(ComponentID.LMS_INGAME_GROUP_ID, ComponentID.LmsKDA.INFO),

	LOGIN_CLICK_TO_PLAY_SCREEN(ComponentID.LOGIN_CLICK_TO_PLAY_GROUP_ID, 0),
	LOGIN_CLICK_TO_PLAY_SCREEN_MESSAGE_OF_THE_DAY(ComponentID.LOGIN_CLICK_TO_PLAY_GROUP_ID, ComponentID.LoginClickToPlayScreen.MESSAGE_OF_THE_DAY),
	LOGIN_CLICK_TO_PLAY_SCREEN_BANK_PIN(ComponentID.LOGIN_CLICK_TO_PLAY_GROUP_ID, 73),
	LOGIN_CLICK_TO_PLAY_SCREEN_PLAY_BUTTON(ComponentID.LOGIN_CLICK_TO_PLAY_GROUP_ID, 78),
	LOGIN_CLICK_TO_PLAY_SCREEN_RIGHT_BUTTON(ComponentID.LOGIN_CLICK_TO_PLAY_GROUP_ID, 79),
	LOGIN_CLICK_TO_PLAY_SCREEN_MAIL_BUTTON(ComponentID.LOGIN_CLICK_TO_PLAY_GROUP_ID, 83),
	LOGIN_CLICK_TO_PLAY_SCREEN_PROMO_CLICK(ComponentID.LOGIN_CLICK_TO_PLAY_GROUP_ID, 86),

	FIXED_VIEWPORT(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.Viewport.FIXED_VIEWPORT),
	FIXED_VIEWPORT_ROOT_INTERFACE_CONTAINER(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.ROOT_INTERFACE_CONTAINER),
	FIXED_VIEWPORT_BANK_CONTAINER(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.BANK_CONTAINER),
	FIXED_VIEWPORT_INTERFACE_CONTAINER(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.INTERFACE_CONTAINER),
	FIXED_VIEWPORT_INVENTORY_CONTAINER(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.INVENTORY_CONTAINER),
	FIXED_VIEWPORT_COMBAT_TAB(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.COMBAT_TAB),
	FIXED_VIEWPORT_STATS_TAB(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.STATS_TAB),
	FIXED_VIEWPORT_QUESTS_TAB(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.QUESTS_TAB),
	FIXED_VIEWPORT_INVENTORY_TAB(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.INVENTORY_TAB),
	FIXED_VIEWPORT_EQUIPMENT_TAB(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.EQUIPMENT_TAB),
	FIXED_VIEWPORT_PRAYER_TAB(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.PRAYER_TAB),
	FIXED_VIEWPORT_MAGIC_TAB(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.MAGIC_TAB),
	FIXED_VIEWPORT_CLAN_CHAT_TAB(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.CLAN_CHAT_TAB),
	FIXED_VIEWPORT_FRIENDS_TAB(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.FRIENDS_TAB),
	FIXED_VIEWPORT_IGNORES_TAB(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.IGNORES_TAB),
	FIXED_VIEWPORT_LOGOUT_TAB(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.LOGOUT_TAB),
	FIXED_VIEWPORT_OPTIONS_TAB(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.OPTIONS_TAB),
	FIXED_VIEWPORT_EMOTES_TAB(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.EMOTES_TAB),
	FIXED_VIEWPORT_MUSIC_TAB(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.MUSIC_TAB),
	FIXED_VIEWPORT_COMBAT_ICON(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.COMBAT_ICON),
	FIXED_VIEWPORT_STATS_ICON(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.STATS_ICON),
	FIXED_VIEWPORT_QUESTS_ICON(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.QUESTS_ICON),
	FIXED_VIEWPORT_INVENTORY_ICON(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.INVENTORY_ICON),
	FIXED_VIEWPORT_EQUIPMENT_ICON(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.EQUIPMENT_ICON),
	FIXED_VIEWPORT_PRAYER_ICON(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.PRAYER_ICON),
	FIXED_VIEWPORT_MAGIC_ICON(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.MAGIC_ICON),
	FIXED_VIEWPORT_CLAN_CHAT_ICON(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.CLAN_CHAT_ICON),
	FIXED_VIEWPORT_FRIENDS_ICON(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.FRIENDS_ICON),
	FIXED_VIEWPORT_IGNORES_ICON(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.IGNORES_ICON),
	FIXED_VIEWPORT_LOGOUT_ICON(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.LOGOUT_ICON),
	FIXED_VIEWPORT_OPTIONS_ICON(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.OPTIONS_ICON),
	FIXED_VIEWPORT_EMOTES_ICON(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.EMOTES_ICON),
	FIXED_VIEWPORT_MUSIC_ICON(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.MUSIC_ICON),
	FIXED_VIEWPORT_MINIMAP(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.MINIMAP),
	FIXED_VIEWPORT_MINIMAP_DRAW_AREA(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.MINIMAP_DRAW_AREA),

	RESIZABLE_MINIMAP_WIDGET(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, ComponentID.Viewport.MINIMAP_RESIZABLE_WIDGET),
	RESIZABLE_MINIMAP_CLICKBOX(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, ComponentID.Viewport.MINIMAP_RESIZABLE_CLICKBOX),
	RESIZABLE_MINIMAP_DRAW_AREA(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, ComponentID.Viewport.MINIMAP_RESIZABLE_DRAW_AREA),
	RESIZABLE_MINIMAP_DECORATIONS(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, ComponentID.Viewport.MINIMAP_RESIZABLE_DECORATIONS),
	RESIZABLE_MINIMAP_ORB_HOLDER(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, ComponentID.Viewport.MINIMAP_RESIZABLE_ORB_HOLDER),
	RESIZABLE_MINIMAP_LOGOUT_BUTTON(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, ComponentID.Viewport.MINIMAP_RESIZABLE_LOGOUT_BUTTON),

	RESIZABLE_MINIMAP_STONES_WIDGET(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.Viewport.MINIMAP_RESIZABLE_WIDGET),
	RESIZABLE_MINIMAP_STONES_CLICKBOX(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.Viewport.MINIMAP_RESIZABLE_CLICKBOX),
	RESIZABLE_MINIMAP_STONES_DRAW_AREA(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.Viewport.MINIMAP_RESIZABLE_DRAW_AREA),
	RESIZABLE_MINIMAP_STONES_DECORATIONS(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.Viewport.MINIMAP_RESIZABLE_DECORATIONS),
	RESIZABLE_MINIMAP_STONES_ORB_HOLDER(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.Viewport.MINIMAP_RESIZABLE_ORB_HOLDER),

	RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.Viewport.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX),
	RESIZABLE_VIEWPORT_COMBAT_TAB(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.COMBAT_TAB),
	RESIZABLE_VIEWPORT_STATS_TAB(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.STATS_TAB),
	RESIZABLE_VIEWPORT_QUESTS_TAB(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.QUESTS_TAB),
	RESIZABLE_VIEWPORT_INVENTORY_TAB(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.INVENTORY_TAB),
	RESIZABLE_VIEWPORT_EQUIPMENT_TAB(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.EQUIPMENT_TAB),
	RESIZABLE_VIEWPORT_PRAYER_TAB(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.PRAYER_TAB),
	RESIZABLE_VIEWPORT_MAGIC_TAB(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.MAGIC_TAB),
	RESIZABLE_VIEWPORT_CLAN_CHAT_TAB(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.CLAN_CHAT_TAB),
	RESIZABLE_VIEWPORT_FRIENDS_TAB(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.FRIENDS_TAB),
	RESIZABLE_VIEWPORT_IGNORES_TAB(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.IGNORES_TAB),
	RESIZABLE_VIEWPORT_LOGOUT_TAB(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.LOGOUT_TAB),
	RESIZABLE_VIEWPORT_OPTIONS_TAB(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.OPTIONS_TAB),
	RESIZABLE_VIEWPORT_EMOTES_TAB(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.EMOTES_TAB),
	RESIZABLE_VIEWPORT_MUSIC_TAB(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.MUSIC_TAB),
	RESIZABLE_VIEWPORT_COMBAT_ICON(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.COMBAT_ICON),
	RESIZABLE_VIEWPORT_STATS_ICON(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.STATS_ICON),
	RESIZABLE_VIEWPORT_QUESTS_ICON(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.QUESTS_ICON),
	RESIZABLE_VIEWPORT_INVENTORY_ICON(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.INVENTORY_ICON),
	RESIZABLE_VIEWPORT_EQUIPMENT_ICON(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.EQUIPMENT_ICON),
	RESIZABLE_VIEWPORT_PRAYER_ICON(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.PRAYER_ICON),
	RESIZABLE_VIEWPORT_MAGIC_ICON(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.MAGIC_ICON),
	RESIZABLE_VIEWPORT_CLAN_CHAT_ICON(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.CLAN_CHAT_ICON),
	RESIZABLE_VIEWPORT_FRIENDS_ICON(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.FRIENDS_ICON),
	RESIZABLE_VIEWPORT_IGNORES_ICON(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.IGNORES_ICON),
	RESIZABLE_VIEWPORT_LOGOUT_ICON(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.LOGOUT_ICON),
	RESIZABLE_VIEWPORT_OPTIONS_ICON(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.OPTIONS_ICON),
	RESIZABLE_VIEWPORT_EMOTES_ICON(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.EMOTES_ICON),
	RESIZABLE_VIEWPORT_MUSIC_ICON(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.MUSIC_ICON),
	RESIZABLE_VIEWPORT_KEPT_ON_DEATH(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.ITEMS_KEPT_ON_DEATH),

	RESIZABLE_VIEWPORT_BOTTOM_LINE(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, ComponentID.Viewport.RESIZABLE_VIEWPORT_BOTTOM_LINE),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_LOGOUT_BUTTON(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, ComponentID.ResizableViewportBottomLine.LOGOUT_BUTTON_OVERLAY),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_QUESTS_ICON(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, ComponentID.ResizableViewportBottomLine.QUESTS_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_INVENTORY_TAB(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, ComponentID.ResizableViewportBottomLine.INVENTORY_TAB),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_INVENTORY_ICON(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, ComponentID.ResizableViewportBottomLine.INVENTORY_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_PRAYER_TAB(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, ComponentID.ResizableViewportBottomLine.PRAYER_TAB),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_PRAYER_ICON(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, ComponentID.ResizableViewportBottomLine.PRAYER_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_EQUIPMENT_ICON(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, ComponentID.ResizableViewportBottomLine.EQUIP_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_COMBAT_ICON(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, ComponentID.ResizableViewportBottomLine.CMB_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_STATS_ICON(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, ComponentID.ResizableViewportBottomLine.SKILLS_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_MAGIC_TAB(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, ComponentID.ResizableViewportBottomLine.MAGIC_TAB),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_MAGIC_ICON(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, ComponentID.ResizableViewportBottomLine.MAGIC_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_FRIEND_ICON(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, ComponentID.ResizableViewportBottomLine.FRIEND_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_FRIEND_CHAT_ICON(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, ComponentID.ResizableViewportBottomLine.FC_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_OPTIONS_ICON(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, ComponentID.ResizableViewportBottomLine.SETTINGS_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_EMOTES_ICON(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, ComponentID.ResizableViewportBottomLine.EMOTE_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_MUSIC_ICON(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, ComponentID.ResizableViewportBottomLine.MUSIC_ICON),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_INVENTORY_CONTAINER(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, ComponentID.ResizableViewportBottomLine.INVENTORY_CONTAINER),
	RESIZABLE_VIEWPORT_INTERFACE_CONTAINER(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.INTERFACE_CONTAINER),
	RESIZABLE_VIEWPORT_INVENTORY_CONTAINER(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.INVENTORY_CONTAINER),
	RESIZABLE_VIEWPORT_BOTTOM_LINE_INTERFACE_CONTAINER(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, ComponentID.ResizableViewport.INTERFACE_CONTAINER),

	PRAYER_THICK_SKIN(ComponentID.PRAYER_GROUP_ID, ComponentID.Prayer.THICK_SKIN),
	PRAYER_BURST_OF_STRENGTH(ComponentID.PRAYER_GROUP_ID, ComponentID.Prayer.BURST_OF_STRENGTH),
	PRAYER_CLARITY_OF_THOUGHT(ComponentID.PRAYER_GROUP_ID, ComponentID.Prayer.CLARITY_OF_THOUGHT),
	PRAYER_SHARP_EYE(ComponentID.PRAYER_GROUP_ID, ComponentID.Prayer.SHARP_EYE),
	PRAYER_MYSTIC_WILL(ComponentID.PRAYER_GROUP_ID, ComponentID.Prayer.MYSTIC_WILL),
	PRAYER_ROCK_SKIN(ComponentID.PRAYER_GROUP_ID, ComponentID.Prayer.ROCK_SKIN),
	PRAYER_SUPERHUMAN_STRENGTH(ComponentID.PRAYER_GROUP_ID, ComponentID.Prayer.SUPERHUMAN_STRENGTH),
	PRAYER_IMPROVED_REFLEXES(ComponentID.PRAYER_GROUP_ID, ComponentID.Prayer.IMPROVED_REFLEXES),
	PRAYER_RAPID_RESTORE(ComponentID.PRAYER_GROUP_ID, ComponentID.Prayer.RAPID_RESTORE),
	PRAYER_RAPID_HEAL(ComponentID.PRAYER_GROUP_ID, ComponentID.Prayer.RAPID_HEAL),
	PRAYER_PROTECT_ITEM(ComponentID.PRAYER_GROUP_ID, ComponentID.Prayer.PROTECT_ITEM),
	PRAYER_HAWK_EYE(ComponentID.PRAYER_GROUP_ID, ComponentID.Prayer.HAWK_EYE),
	PRAYER_MYSTIC_LORE(ComponentID.PRAYER_GROUP_ID, ComponentID.Prayer.MYSTIC_LORE),
	PRAYER_STEEL_SKIN(ComponentID.PRAYER_GROUP_ID, ComponentID.Prayer.STEEL_SKIN),
	PRAYER_ULTIMATE_STRENGTH(ComponentID.PRAYER_GROUP_ID, ComponentID.Prayer.ULTIMATE_STRENGTH),
	PRAYER_INCREDIBLE_REFLEXES(ComponentID.PRAYER_GROUP_ID, ComponentID.Prayer.INCREDIBLE_REFLEXES),
	PRAYER_PROTECT_FROM_MAGIC(ComponentID.PRAYER_GROUP_ID, ComponentID.Prayer.PROTECT_FROM_MAGIC),
	PRAYER_PROTECT_FROM_MISSILES(ComponentID.PRAYER_GROUP_ID, ComponentID.Prayer.PROTECT_FROM_MISSILES),
	PRAYER_PROTECT_FROM_MELEE(ComponentID.PRAYER_GROUP_ID, ComponentID.Prayer.PROTECT_FROM_MELEE),
	PRAYER_EAGLE_EYE(ComponentID.PRAYER_GROUP_ID, ComponentID.Prayer.EAGLE_EYE),
	PRAYER_MYSTIC_MIGHT(ComponentID.PRAYER_GROUP_ID, ComponentID.Prayer.MYSTIC_MIGHT),
	PRAYER_RETRIBUTION(ComponentID.PRAYER_GROUP_ID, ComponentID.Prayer.RETRIBUTION),
	PRAYER_REDEMPTION(ComponentID.PRAYER_GROUP_ID, ComponentID.Prayer.REDEMPTION),
	PRAYER_SMITE(ComponentID.PRAYER_GROUP_ID, ComponentID.Prayer.SMITE),
	PRAYER_PRESERVE(ComponentID.PRAYER_GROUP_ID, ComponentID.Prayer.PRESERVE),
	PRAYER_CHIVALRY(ComponentID.PRAYER_GROUP_ID, ComponentID.Prayer.CHIVALRY),
	PRAYER_PIETY(ComponentID.PRAYER_GROUP_ID, ComponentID.Prayer.PIETY),
	PRAYER_RIGOUR(ComponentID.PRAYER_GROUP_ID, ComponentID.Prayer.RIGOUR),
	PRAYER_AUGURY(ComponentID.PRAYER_GROUP_ID, ComponentID.Prayer.AUGURY),

	QUICK_PRAYER_PRAYERS(ComponentID.QUICK_PRAYERS_GROUP_ID, ComponentID.QuickPrayer.PRAYERS),

	COMBAT_LEVEL(ComponentID.COMBAT_GROUP_ID, ComponentID.Combat.LEVEL),
	COMBAT_WEAPON(ComponentID.COMBAT_GROUP_ID, ComponentID.Combat.WEAPON_NAME),
	COMBAT_STYLE_ONE(ComponentID.COMBAT_GROUP_ID, ComponentID.Combat.STYLE_ONE),
	COMBAT_STYLE_TWO(ComponentID.COMBAT_GROUP_ID, ComponentID.Combat.STYLE_TWO),
	COMBAT_STYLE_THREE(ComponentID.COMBAT_GROUP_ID, ComponentID.Combat.STYLE_THREE),
	COMBAT_STYLE_FOUR(ComponentID.COMBAT_GROUP_ID, ComponentID.Combat.STYLE_FOUR),
	COMBAT_SPELLS(ComponentID.COMBAT_GROUP_ID, ComponentID.Combat.SPELLS),
	COMBAT_DEFENSIVE_SPELL_BOX(ComponentID.COMBAT_GROUP_ID, ComponentID.Combat.DEFENSIVE_SPELL_BOX),
	COMBAT_DEFENSIVE_SPELL_ICON(ComponentID.COMBAT_GROUP_ID, ComponentID.Combat.DEFENSIVE_SPELL_ICON),
	COMBAT_DEFENSIVE_SPELL_SHIELD(ComponentID.COMBAT_GROUP_ID, ComponentID.Combat.DEFENSIVE_SPELL_SHIELD),
	COMBAT_DEFENSIVE_SPELL_TEXT(ComponentID.COMBAT_GROUP_ID, ComponentID.Combat.DEFENSIVE_SPELL_TEXT),
	COMBAT_SPELL_BOX(ComponentID.COMBAT_GROUP_ID, ComponentID.Combat.SPELL_BOX),
	COMBAT_SPELL_ICON(ComponentID.COMBAT_GROUP_ID, ComponentID.Combat.SPELL_ICON),
	COMBAT_SPELL_TEXT(ComponentID.COMBAT_GROUP_ID, ComponentID.Combat.SPELL_TEXT),
	COMBAT_AUTO_RETALIATE(ComponentID.COMBAT_GROUP_ID, ComponentID.Combat.AUTO_RETALIATE),
	COMBAT_SPECIAL_ATTACK(ComponentID.COMBAT_GROUP_ID, ComponentID.Combat.SPECIAL_ATTACK_BAR),
	COMBAT_TOOLTIP(ComponentID.COMBAT_GROUP_ID, ComponentID.Combat.TOOLTIP),

	DIALOG_OPTION(ComponentID.DIALOG_OPTION_GROUP_ID, 0),

	DIALOG_SPRITE(ComponentID.DIALOG_SPRITE_GROUP_ID, 0),
	DIALOG_SPRITE_SPRITE(ComponentID.DIALOG_SPRITE_GROUP_ID, ComponentID.DialogSprite.SPRITE),
	DIALOG_SPRITE_TEXT(ComponentID.DIALOG_SPRITE_GROUP_ID, ComponentID.DialogSprite.TEXT),
	DIALOG2_SPRITE(ComponentID.DIALOG_SPRITE2_ID, 0),
	DIALOG2_SPRITE_SPRITE1(ComponentID.DIALOG_SPRITE2_ID, ComponentID.DialogSprite2.SPRITE1),
	DIALOG2_SPRITE_SPRITE2(ComponentID.DIALOG_SPRITE2_ID, ComponentID.DialogSprite2.SPRITE2),
	DIALOG2_SPRITE_TEXT(ComponentID.DIALOG_SPRITE2_ID, ComponentID.DialogSprite2.TEXT),
	DIALOG2_SPRITE_CONTINUE(ComponentID.DIALOG_SPRITE2_ID, ComponentID.DialogSprite2.CONTINUE),

	DIALOG_NPC(ComponentID.DIALOG_NPC_GROUP_ID, 0),
	DIALOG_NPC_NAME(ComponentID.DIALOG_NPC_GROUP_ID, ComponentID.HeadDialogueComps.NAME),
	DIALOG_NPC_TEXT(ComponentID.DIALOG_NPC_GROUP_ID, ComponentID.HeadDialogueComps.TEXT),
	DIALOG_NPC_HEAD_MODEL(ComponentID.DIALOG_NPC_GROUP_ID, ComponentID.HeadDialogueComps.HEAD_MODEL),
	DIALOG_NPC_CONTINUE(ComponentID.DIALOG_NPC_GROUP_ID, ComponentID.HeadDialogueComps.CONTINUE),

	DIALOG_PLAYER(ComponentID.DIALOG_PLAYER_GROUP_ID, 0),

	PRIVATE_CHAT_MESSAGE(ComponentID.PRIVATE_CHAT, 0),

	SLAYER_REWARDS_TOPBAR(ComponentID.SLAYER_REWARDS_GROUP_ID, ComponentID.SlayerRewards.TOP_BAR),

	CHATBOX_PARENT(ComponentID.CHATBOX_GROUP_ID, ComponentID.Chatbox.PARENT),
	CHATBOX(ComponentID.CHATBOX_GROUP_ID, ComponentID.Chatbox.FRAME),
	CHATBOX_MESSAGES(ComponentID.CHATBOX_GROUP_ID, ComponentID.Chatbox.MESSAGES),
	CHATBOX_BUTTONS(ComponentID.CHATBOX_GROUP_ID, ComponentID.Chatbox.BUTTONS),
	CHATBOX_TITLE(ComponentID.CHATBOX_GROUP_ID, ComponentID.Chatbox.TITLE),
	CHATBOX_FULL_INPUT(ComponentID.CHATBOX_GROUP_ID, ComponentID.Chatbox.FULL_INPUT),
	CHATBOX_CONTAINER(ComponentID.CHATBOX_GROUP_ID, ComponentID.Chatbox.CONTAINER),
	CHATBOX_REPORT_TEXT(ComponentID.CHATBOX_GROUP_ID, ComponentID.Chatbox.REPORT_TEXT),
	CHATBOX_INPUT(ComponentID.CHATBOX_GROUP_ID, ComponentID.Chatbox.INPUT),
	CHATBOX_TRANSPARENT_BACKGROUND(ComponentID.CHATBOX_GROUP_ID, ComponentID.Chatbox.TRANSPARENT_BACKGROUND),
	CHATBOX_TRANSPARENT_LINES(ComponentID.CHATBOX_GROUP_ID, ComponentID.Chatbox.TRANSPARENT_BACKGROUND_LINES),

	BA_HEAL_WAVE_TEXT(ComponentID.BA_HEALER_GROUP_ID, ComponentID.BarbarianAssault.CURRENT_WAVE),
	BA_HEAL_CALL_TEXT(ComponentID.BA_HEALER_GROUP_ID, ComponentID.BarbarianAssault.TO_CALL),
	BA_HEAL_LISTEN_TEXT(ComponentID.BA_HEALER_GROUP_ID, ComponentID.BarbarianAssault.LISTEN),
	BA_HEAL_HORN_LISTEN_TEXT(ComponentID.BA_HORN_OF_GLORY, ComponentID.BarbarianAssault.HORN_GLORY.HEALER),
	BA_HEAL_ROLE_TEXT(ComponentID.BA_HEALER_GROUP_ID, ComponentID.BarbarianAssault.ROLE),
	BA_HEAL_ROLE_SPRITE(ComponentID.BA_HEALER_GROUP_ID, ComponentID.BarbarianAssault.ROLE_SPRITE),

	BA_HEAL_TEAMMATE1(ComponentID.BA_HEALER_GROUP_ID, ComponentID.BarbarianAssault.HLR.TEAMMATE1),
	BA_HEAL_TEAMMATE2(ComponentID.BA_HEALER_GROUP_ID, ComponentID.BarbarianAssault.HLR.TEAMMATE2),
	BA_HEAL_TEAMMATE3(ComponentID.BA_HEALER_GROUP_ID, ComponentID.BarbarianAssault.HLR.TEAMMATE3),
	BA_HEAL_TEAMMATE4(ComponentID.BA_HEALER_GROUP_ID, ComponentID.BarbarianAssault.HLR.TEAMMATE4),

	BA_COLL_WAVE_TEXT(ComponentID.BA_COLLECTOR_GROUP_ID, ComponentID.BarbarianAssault.CURRENT_WAVE),
	BA_COLL_CALL_TEXT(ComponentID.BA_COLLECTOR_GROUP_ID, ComponentID.BarbarianAssault.TO_CALL),
	BA_COLL_LISTEN_TEXT(ComponentID.BA_COLLECTOR_GROUP_ID, ComponentID.BarbarianAssault.LISTEN),
	BA_COLL_HORN_LISTEN_TEXT(ComponentID.BA_HORN_OF_GLORY, ComponentID.BarbarianAssault.HORN_GLORY.COLLECTOR),
	BA_COLL_ROLE_TEXT(ComponentID.BA_COLLECTOR_GROUP_ID, ComponentID.BarbarianAssault.ROLE),
	BA_COLL_ROLE_SPRITE(ComponentID.BA_COLLECTOR_GROUP_ID, ComponentID.BarbarianAssault.ROLE_SPRITE),

	BA_ATK_WAVE_TEXT(ComponentID.BA_ATTACKER_GROUP_ID, ComponentID.BarbarianAssault.CURRENT_WAVE),
	BA_ATK_CALL_TEXT(ComponentID.BA_ATTACKER_GROUP_ID, ComponentID.BarbarianAssault.ATK.TO_CALL),
	BA_ATK_LISTEN_TOP_TEXT(ComponentID.BA_ATTACKER_GROUP_ID, ComponentID.BarbarianAssault.ATK.LISTEN_TOP),
	BA_ATK_LISTEN_BOTTOM_TEXT(ComponentID.BA_ATTACKER_GROUP_ID, ComponentID.BarbarianAssault.ATK.LISTEN_BOTTOM),
	BA_ATK_HORN_LISTEN_TEXT(ComponentID.BA_HORN_OF_GLORY, ComponentID.BarbarianAssault.HORN_GLORY.ATTACKER),
	BA_ATK_ROLE_TEXT(ComponentID.BA_ATTACKER_GROUP_ID, ComponentID.BarbarianAssault.ATK.ROLE),
	BA_ATK_ROLE_SPRITE(ComponentID.BA_ATTACKER_GROUP_ID, ComponentID.BarbarianAssault.ATK.ROLE_SPRITE),

	BA_DEF_WAVE_TEXT(ComponentID.BA_DEFENDER_GROUP_ID, ComponentID.BarbarianAssault.CURRENT_WAVE),
	BA_DEF_CALL_TEXT(ComponentID.BA_DEFENDER_GROUP_ID, ComponentID.BarbarianAssault.TO_CALL),
	BA_DEF_LISTEN_TEXT(ComponentID.BA_DEFENDER_GROUP_ID, ComponentID.BarbarianAssault.LISTEN),
	BA_DEF_HORN_LISTEN_TEXT(ComponentID.BA_HORN_OF_GLORY, ComponentID.BarbarianAssault.HORN_GLORY.DEFENDER),
	BA_DEF_ROLE_TEXT(ComponentID.BA_DEFENDER_GROUP_ID, ComponentID.BarbarianAssault.ROLE),
	BA_DEF_ROLE_SPRITE(ComponentID.BA_DEFENDER_GROUP_ID, ComponentID.BarbarianAssault.ROLE_SPRITE),

	BA_REWARD_TEXT(ComponentID.BA_REWARD_GROUP_ID, ComponentID.BarbarianAssault.REWARD_TEXT),
	BA_RUNNERS_PASSED(ComponentID.BA_REWARD_GROUP_ID, ComponentID.BarbarianAssault.REWARD_VALUES.RUNNERS_PASSED),
	BA_HITPOINTS_REPLENISHED(ComponentID.BA_REWARD_GROUP_ID, ComponentID.BarbarianAssault.REWARD_VALUES.HITPOINTS_REPLENISHED),
	BA_WRONG_POISON_PACKS(ComponentID.BA_REWARD_GROUP_ID, ComponentID.BarbarianAssault.REWARD_VALUES.WRONG_POISON_PACKS_USED),
	BA_EGGS_COLLECTED(ComponentID.BA_REWARD_GROUP_ID, ComponentID.BarbarianAssault.REWARD_VALUES.EGGS_COLLECTED),
	BA_FAILED_ATTACKER_ATTACKS(ComponentID.BA_REWARD_GROUP_ID, ComponentID.BarbarianAssault.REWARD_VALUES.FAILED_ATTACKER_ATTACKS),
	BA_RUNNERS_PASSED_POINTS(ComponentID.BA_REWARD_GROUP_ID, ComponentID.BarbarianAssault.REWARD_VALUES.RUNNERS_PASSED_POINTS),
	BA_RANGERS_KILLED(ComponentID.BA_REWARD_GROUP_ID, ComponentID.BarbarianAssault.REWARD_VALUES.RANGERS_KILLED),
	BA_FIGHTERS_KILLED(ComponentID.BA_REWARD_GROUP_ID, ComponentID.BarbarianAssault.REWARD_VALUES.FIGHTERS_KILLED),
	BA_HEALERS_KILLED(ComponentID.BA_REWARD_GROUP_ID, ComponentID.BarbarianAssault.REWARD_VALUES.HEALERS_KILLED),
	BA_RUNNERS_KILLED(ComponentID.BA_REWARD_GROUP_ID, ComponentID.BarbarianAssault.REWARD_VALUES.RUNNERS_KILLED),
	BA_HITPOINTS_REPLENISHED_POINTS(ComponentID.BA_REWARD_GROUP_ID, ComponentID.BarbarianAssault.REWARD_VALUES.HITPOINTS_REPLENISHED_POINTS),
	BA_WRONG_POISON_PACKS_POINTS(ComponentID.BA_REWARD_GROUP_ID, ComponentID.BarbarianAssault.REWARD_VALUES.WRONG_POISON_PACKS_USED_POINTS),
	BA_EGGS_COLLECTED_POINTS(ComponentID.BA_REWARD_GROUP_ID, ComponentID.BarbarianAssault.REWARD_VALUES.EGGS_COLLECTED_POINTS),
	BA_FAILED_ATTACKER_ATTACKS_POINTS(ComponentID.BA_REWARD_GROUP_ID, ComponentID.BarbarianAssault.REWARD_VALUES.FAILED_ATTACKER_ATTACKS_POINTS),
	BA_HONOUR_POINTS_REWARD(ComponentID.BA_REWARD_GROUP_ID, ComponentID.BarbarianAssault.REWARD_VALUES.HONOUR_POINTS_REWARD),
	BA_BASE_POINTS(ComponentID.BA_REWARD_GROUP_ID, ComponentID.BarbarianAssault.REWARD_VALUES.BASE_POINTS),

	LEVEL_UP(ComponentID.LEVEL_UP_GROUP_ID, 0),
	LEVEL_UP_SKILL(ComponentID.LEVEL_UP_GROUP_ID, ComponentID.LevelUp.SKILL),
	LEVEL_UP_LEVEL(ComponentID.LEVEL_UP_GROUP_ID, ComponentID.LevelUp.LEVEL),

	QUEST_COMPLETED(ComponentID.QUEST_COMPLETED_GROUP_ID, 0),
	QUEST_COMPLETED_NAME_TEXT(ComponentID.QUEST_COMPLETED_GROUP_ID, ComponentID.QuestCompleted.NAME_TEXT),

	MOTHERLODE_MINE(ComponentID.MOTHERLODE_MINE_GROUP_ID, 0),

	PUZZLE_BOX(ComponentID.PUZZLE_BOX_GROUP_ID, ComponentID.PuzzleBox.VISIBLE_BOX),

	LIGHT_BOX(ComponentID.LIGHT_BOX_GROUP_ID, ComponentID.LightBox.LIGHT_BOX),
	LIGHT_BOX_CONTENTS(ComponentID.LIGHT_BOX_GROUP_ID, ComponentID.LightBox.LIGHT_BULB_CONTAINER),
	LIGHT_BOX_BUTTON_A(ComponentID.LIGHT_BOX_GROUP_ID, ComponentID.LightBox.BUTTON_A),
	LIGHT_BOX_BUTTON_B(ComponentID.LIGHT_BOX_GROUP_ID, ComponentID.LightBox.BUTTON_B),
	LIGHT_BOX_BUTTON_C(ComponentID.LIGHT_BOX_GROUP_ID, ComponentID.LightBox.BUTTON_C),
	LIGHT_BOX_BUTTON_D(ComponentID.LIGHT_BOX_GROUP_ID, ComponentID.LightBox.BUTTON_D),
	LIGHT_BOX_BUTTON_E(ComponentID.LIGHT_BOX_GROUP_ID, ComponentID.LightBox.BUTTON_E),
	LIGHT_BOX_BUTTON_F(ComponentID.LIGHT_BOX_GROUP_ID, ComponentID.LightBox.BUTTON_F),
	LIGHT_BOX_BUTTON_G(ComponentID.LIGHT_BOX_GROUP_ID, ComponentID.LightBox.BUTTON_G),
	LIGHT_BOX_BUTTON_H(ComponentID.LIGHT_BOX_GROUP_ID, ComponentID.LightBox.BUTTON_H),

	LIGHT_BOX_WINDOW(ComponentID.LIGHT_BOX_GROUP_ID, ComponentID.LightBox.LIGHT_BOX_WINDOW),

	Krota_ZONE(ComponentID.Krota_ZONE_GROUP_ID, 0),

	RAIDS_POINTS_INFOBOX(ComponentID.RAIDS_GROUP_ID, ComponentID.Raids.POINTS_INFOBOX),

	THEATRE_OF_BLOOD_HEALTH_ORBS(ComponentID.THEATRE_OF_BLOOD_GROUP_ID, ComponentID.TheatreOfBlood.ORB_BOX),
	THEATRE_OF_BLOOD_BOSS_HEALTH(ComponentID.THEATRE_OF_BLOOD_GROUP_ID, ComponentID.TheatreOfBlood.BOSS_HEALTH_BAR),
	THEATRE_OF_BLOOD_RAIDING_PARTY(ComponentID.THEATRE_OF_BLOOD_GROUP_ID, ComponentID.TheatreOfBlood.RAIDING_PARTY),

	BLAST_FURNACE_COFFER(ComponentID.BLAST_FURNACE_GROUP_ID, 2),

	PYRAMID_PLUNDER_DATA(ComponentID.PYRAMID_PLUNDER_GROUP_ID, 2),

	EXPERIENCE_TRACKER(ComponentID.EXPERIENCE_TRACKER_GROUP_ID, 0),
	EXPERIENCE_TRACKER_WIDGET(ComponentID.EXPERIENCE_TRACKER_GROUP_ID, ComponentID.ExperienceTracker.WIDGET),
	EXPERIENCE_TRACKER_BOTTOM_BAR(ComponentID.EXPERIENCE_TRACKER_GROUP_ID, ComponentID.ExperienceTracker.BOTTOM_BAR),

	FISHING_TRAWLER_TIMER(ComponentID.FISHING_TRAWLER_GROUP_ID, 14),

	TITHE_FARM(ComponentID.TITHE_FARM_GROUP_ID, 1),

	BARROWS_INFO(ComponentID.BARROWS_GROUP_ID, 0),
	BARROWS_BROTHERS(ComponentID.BARROWS_GROUP_ID, ComponentID.Barrows.BARROWS_BROTHERS),
	BARROWS_POTENTIAL(ComponentID.BARROWS_GROUP_ID, ComponentID.Barrows.BARROWS_POTENTIAL),
	BARROWS_REWARD_INVENTORY(ComponentID.BARROWS_REWARD_GROUP_ID, ComponentID.Barrows.BARROWS_REWARD_INVENTORY),
	BARROWS_PUZZLE_PARENT(ComponentID.BARROWS_PUZZLE_GROUP_ID, ComponentID.Barrows_Puzzle.PARENT),
	BARROWS_PUZZLE_ANSWER1(ComponentID.BARROWS_PUZZLE_GROUP_ID, ComponentID.Barrows_Puzzle.ANSWER1),
	BARROWS_PUZZLE_ANSWER1_CONTAINER(ComponentID.BARROWS_PUZZLE_GROUP_ID, ComponentID.Barrows_Puzzle.ANSWER1_CONTAINER),
	BARROWS_PUZZLE_ANSWER2(ComponentID.BARROWS_PUZZLE_GROUP_ID, ComponentID.Barrows_Puzzle.ANSWER2),
	BARROWS_PUZZLE_ANSWER2_CONTAINER(ComponentID.BARROWS_PUZZLE_GROUP_ID, ComponentID.Barrows_Puzzle.ANSWER2_CONTAINER),
	BARROWS_PUZZLE_ANSWER3(ComponentID.BARROWS_PUZZLE_GROUP_ID, ComponentID.Barrows_Puzzle.ANSWER3),
	BARROWS_PUZZLE_ANSWER3_CONTAINER(ComponentID.BARROWS_PUZZLE_GROUP_ID, ComponentID.Barrows_Puzzle.ANSWER3_CONTAINER),
	BARROWS_FIRST_PUZZLE(ComponentID.BARROWS_PUZZLE_GROUP_ID, ComponentID.Barrows_Puzzle.SEQUENCE_1),

	BLAST_MINE(ComponentID.BLAST_MINE_GROUP_ID, 2),

	FAIRY_RING(ComponentID.FAIRY_RING_GROUP_ID, 0),

	FAIRY_RING_HEADER(ComponentID.FAIRY_RING_PANEL_GROUP_ID, ComponentID.FairyRingPanel.HEADER),
	FAIRY_RING_LIST(ComponentID.FAIRY_RING_PANEL_GROUP_ID, ComponentID.FairyRingPanel.LIST),
	FAIRY_RING_FAVORITES(ComponentID.FAIRY_RING_PANEL_GROUP_ID, ComponentID.FairyRingPanel.FAVORITES),
	FAIRY_RING_LIST_SEPARATOR(ComponentID.FAIRY_RING_PANEL_GROUP_ID, ComponentID.FairyRingPanel.SEPARATOR),
	FAIRY_RING_LIST_SCROLLBAR(ComponentID.FAIRY_RING_PANEL_GROUP_ID, ComponentID.FairyRingPanel.SCROLLBAR),

	DESTROY_ITEM(ComponentID.DESTROY_ITEM_GROUP_ID, 0),
	DESTROY_ITEM_NAME(ComponentID.DESTROY_ITEM_GROUP_ID, ComponentID.DestroyItem.DESTROY_ITEM_NAME),
	DESTROY_ITEM_YES(ComponentID.DESTROY_ITEM_GROUP_ID, ComponentID.DestroyItem.DESTROY_ITEM_YES),
	DESTROY_ITEM_NO(ComponentID.DESTROY_ITEM_GROUP_ID, ComponentID.DestroyItem.DESTROY_ITEM_NO),

	VARROCK_MUSEUM_QUESTION(ComponentID.VARROCK_MUSEUM_QUIZ_GROUP_ID, ComponentID.VarrockMuseum.VARROCK_MUSEUM_QUESTION),
	VARROCK_MUSEUM_FIRST_ANSWER(ComponentID.VARROCK_MUSEUM_QUIZ_GROUP_ID, ComponentID.VarrockMuseum.VARROCK_MUSEUM_FIRST_ANSWER),
	VARROCK_MUSEUM_SECOND_ANSWER(ComponentID.VARROCK_MUSEUM_QUIZ_GROUP_ID, ComponentID.VarrockMuseum.VARROCK_MUSEUM_SECOND_ANSWER),
	VARROCK_MUSEUM_THIRD_ANSWER(ComponentID.VARROCK_MUSEUM_QUIZ_GROUP_ID, ComponentID.VarrockMuseum.VARROCK_MUSEUM_THIRD_ANSWER),

	KILL_LOG_TITLE(ComponentID.KILL_LOGS_GROUP_ID, ComponentID.KillLog.TITLE),
	KILL_LOG_MONSTER(ComponentID.KILL_LOGS_GROUP_ID, ComponentID.KillLog.MONSTER),
	KILL_LOG_KILLS(ComponentID.KILL_LOGS_GROUP_ID, ComponentID.KillLog.KILLS),
	KILL_LOG_STREAK(ComponentID.KILL_LOGS_GROUP_ID, ComponentID.KillLog.STREAK),

	WORLD_SWITCHER_LIST(ComponentID.WORLD_SWITCHER_GROUP_ID, ComponentID.WorldSwitcher.WORLD_LIST),

	FOSSIL_ISLAND_OXYGENBAR(ComponentID.FOSSIL_ISLAND_OXYGENBAR_ID, ComponentID.FossilOxygen.FOSSIL_ISLAND_OXYGEN_BAR),

	MINIGAME_TELEPORT_BUTTON(ComponentID.MINIGAME_TAB_ID, ComponentID.Minigames.TELEPORT_BUTTON),

	PVP_FOG_OVERLAY(ComponentID.PVP_GROUP_ID, ComponentID.Pvp.FOG_OVERLAY),
	PVP_CONTAINER(ComponentID.PVP_GROUP_ID, ComponentID.Pvp.PVP_WIDGET_CONTAINER),
	PVP_SKULL_CONTAINER(ComponentID.PVP_GROUP_ID, ComponentID.Pvp.SKULL_CONTAINER),
	PVP_SKULL(ComponentID.PVP_GROUP_ID, ComponentID.Pvp.SKULL),
	PVP_ATTACK_RANGE(ComponentID.PVP_GROUP_ID, ComponentID.Pvp.ATTACK_RANGE),
	PVP_WORLD_SAFE_ZONE(ComponentID.PVP_GROUP_ID, ComponentID.Pvp.SAFE_ZONE),

	PVP_WILDERNESS_LEVEL(ComponentID.PVP_GROUP_ID, ComponentID.Pvp.WILDERNESS_LEVEL),

	PVP_BOUNTY_HUNTER_INFO(ComponentID.PVP_GROUP_ID, ComponentID.Pvp.BOUNTY_HUNTER_INFO),
	PVP_KILLDEATH_COUNTER(ComponentID.PVP_GROUP_ID, ComponentID.Pvp.KILLDEATH_RATIO),

	SPELLBOOK(ComponentID.SPELLBOOK_GROUP_ID, 0),
	SPELLBOOK_FILTERED_SPELLS_PARENT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.FILTERED_SPELLS_PARENT),
	SPELLBOOK_FILTERED_BOUNDS(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.FILTERED_SPELLS_BOUNDS),

	/* STANDARD SPELL BOOK WIDGETS*/
	SPELL_LUMBRIDGE_HOME_TELEPORT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.LUMBRIDGE_HOME_TELEPORT),
	SPELL_WIND_STRIKE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.WIND_STRIKE),
	SPELL_CONFUSE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.CONFUSE),
	SPELL_ENCHANT_CROSSBOW_BOLT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.ENCHANT_CROSSBOW_BOLT),
	SPELL_WATER_STRIKE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.WATER_STRIKE),
	SPELL_LVL_1_ENCHANT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.LVL_1_ENCHANT),
	SPELL_EARTH_STRIKE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.EARTH_STRIKE),
	SPELL_WEAKEN(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.WEAKEN),
	SPELL_FIRE_STRIKE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.FIRE_STRIKE),
	SPELL_BONES_TO_BANANAS(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.BONES_TO_BANANAS),
	SPELL_WIND_BOLT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.WIND_BOLT),
	SPELL_CURSE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.CURSE),
	SPELL_BIND(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.BIND),
	SPELL_LOW_LEVEL_ALCHEMY(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.LOW_LEVEL_ALCHEMY),
	SPELL_WATER_BOLT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.WATER_BOLT),
	SPELL_VARROCK_TELEPORT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.VARROCK_TELEPORT),
	SPELL_LVL_2_ENCHANT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.LVL_2_ENCHANT),
	SPELL_EARTH_BOLT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.EARTH_BOLT),
	SPELL_LUMBRIDGE_TELEPORT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.LUMBRIDGE_TELEPORT),
	SPELL_TELEKINETIC_GRAB(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.TELEKINETIC_GRAB),
	SPELL_FIRE_BOLT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.FIRE_BOLT),
	SPELL_FALADOR_TELEPORT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.FALADOR_TELEPORT),
	SPELL_CRUMBLE_UNDEAD(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.CRUMBLE_UNDEAD),
	SPELL_TELEPORT_TO_HOUSE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.TELEPORT_TO_HOUSE),
	SPELL_WIND_BLAST(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.WIND_BLAST),
	SPELL_SUPERHEAT_ITEM(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.SUPERHEAT_ITEM),
	SPELL_CAMELOT_TELEPORT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.CAMELOT_TELEPORT),
	SPELL_WATER_BLAST(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.WATER_BLAST),
	SPELL_LVL_3_ENCHANT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.LVL_3_ENCHANT),
	SPELL_IBAN_BLAST(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.IBAN_BLAST),
	SPELL_SNARE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.SNARE),
	SPELL_MAGIC_DART(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.MAGIC_DART),
	SPELL_ARDOUGNE_TELEPORT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.ARDOUGNE_TELEPORT),
	SPELL_EARTH_BLAST(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.EARTH_BLAST),
	SPELL_HIGH_LEVEL_ALCHEMY(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.HIGH_LEVEL_ALCHEMY),
	SPELL_CHARGE_WATER_ORB(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.CHARGE_WATER_ORB),
	SPELL_LVL_4_ENCHANT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.LVL_4_ENCHANT),
	SPELL_WATCHTOWER_TELEPORT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.WATCHTOWER_TELEPORT),
	SPELL_FIRE_BLAST(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.FIRE_BLAST),
	SPELL_CHARGE_EARTH_ORB(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.CHARGE_EARTH_ORB),
	SPELL_BONES_TO_PEACHES(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.BONES_TO_PEACHES),
	SPELL_SARADOMIN_STRIKE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.SARADOMIN_STRIKE),
	SPELL_CLAWS_OF_GUTHIX(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.CLAWS_OF_GUTHIX),
	SPELL_FLAMES_OF_ZAMORAK(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.FLAMES_OF_ZAMORAK),
	SPELL_TROLLHEIM_TELEPORT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.TROLLHEIM_TELEPORT),
	SPELL_WIND_WAVE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.WIND_WAVE),
	SPELL_CHARGE_FIRE_ORB(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.CHARGE_FIRE_ORB),
	SPELL_TELEPORT_TO_APE_ATOLL(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.TELEPORT_TO_APE_ATOLL),
	SPELL_WATER_WAVE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.WATER_WAVE),
	SPELL_CHARGE_AIR_ORB(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.CHARGE_AIR_ORB),
	SPELL_VULNERABILITY(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.VULNERABILITY),
	SPELL_LVL_5_ENCHANT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.LVL_5_ENCHANT),
	SPELL_TELEPORT_TO_KOUREND(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.TELEPORT_TO_KOUREND),
	SPELL_EARTH_WAVE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.EARTH_WAVE),
	SPELL_ENFEEBLE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.ENFEEBLE),
	SPELL_FIRE_WAVE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.FIRE_WAVE),
	SPELL_ENTANGLE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.ENTANGLE),
	SPELL_TELEOTHER_LUMBRIDGE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.TELEOTHER_LUMBRIDGE),
	SPELL_STUN(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.STUN),
	SPELL_CHARGE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.CHARGE),
	SPELL_WIND_SURGE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.WIND_SURGE),
	SPELL_TELEOTHER_FALADOR(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.TELEOTHER_FALADOR),
	SPELL_WATER_SURGE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.WATER_SURGE),
	SPELL_TELE_BLOCK(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.TELE_BLOCK),
	SPELL_LVL_6_ENCHANT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.LVL_6_ENCHANT),
	SPELL_TELEOTHER_CAMELOT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.TELEOTHER_CAMELOT),
	SPELL_EARTH_SURGE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.EARTH_SURGE),
	SPELL_LVL_7_ENCHANT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.LVL_7_ENCHANT),
	SPELL_FIRE_SURGE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.FIRE_SURGE),
	SPELL_BOUNTY_TARGET_TELEPORT2(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.BOUNTY_TARGET_TELEPORT),
	/* END OF STANDARD SPELL BOOK WIDGETS*/

	/* ANCIENT SPELL BOOK WIDGETS*/
	SPELL_ICE_RUSH(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.ICE_RUSH),
	SPELL_ICE_BLITZ(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.ICE_BLITZ),
	SPELL_ICE_BURST(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.ICE_BURST),
	SPELL_ICE_BARRAGE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.ICE_BARRAGE),
	SPELL_BLOOD_RUSH(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.BLOOD_RUSH),
	SPELL_BLOOD_BLITZ(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.BLOOD_BLITZ),
	SPELL_BLOOD_BURST(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.BLOOD_BURST),
	SPELL_BLOOD_BARRAGE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.BLOOD_BARRAGE),
	SPELL_SMOKE_RUSH(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.SMOKE_RUSH),
	SPELL_SMOKE_BLITZ(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.SMOKE_BLITZ),
	SPELL_SMOKE_BURST(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.SMOKE_BURST),
	SPELL_SMOKE_BARRAGE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.SMOKE_BARRAGE),
	SPELL_SHADOW_RUSH(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.SHADOW_RUSH),
	SPELL_SHADOW_BLITZ(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.SHADOW_BLITZ),
	SPELL_SHADOW_BURST(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.SHADOW_BURST),
	SPELL_SHADOW_BARRAGE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.SHADOW_BARRAGE),
	SPELL_PADDEWWA_TELEPORT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.PADDEWWA_TELEPORT),
	SPELL_SENNTISTEN_TELEPORT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.SENNTISTEN_TELEPORT),
	SPELL_KHARYRLL_TELEPORT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.KHARYRLL_TELEPORT),
	SPELL_LASSAR_TELEPORT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.LASSAR_TELEPORT),
	SPELL_DAREEYAK_TELEPORT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.DAREEYAK_TELEPORT),
	SPELL_CARRALLANGER_TELEPORT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.CARRALLANGER_TELEPORT),
	SPELL_ANNAKARL_TELEPORT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.ANNAKARL_TELEPORT),
	SPELL_GHORROCK_TELEPORT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.GHORROCK_TELEPORT),
	SPELL_EDGEVILLE_HOME_TELEPORT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.EDGEVILLE_HOME_TELEPORT),
	SPELL_BOUNTY_TARGET_TELEPORT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.BOUNTY_TARGET_TELEPORT),
	/* END OF ANCIENT SPELL BOOK WIDGETS*/

	/* LUNAR SPELL BOOK WIDGETS*/
	SPELL_LUNAR_HOME_TELEPORT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.LUNAR_HOME_TELEPORT),
	SPELL_VENGEANCE_OTHER(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.VENGEANCE_OTHER),
	SPELL_VENGEANCE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.VENGEANCE),
	SPELL_BOUNTY_TARGET_TELEPORT3(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.BOUNTY_TARGET_TELEPORT),
	SPELL_BAKE_PIE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.BAKE_PIE),
	SPELL_CURE_PLANT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.CURE_PLANT),
	SPELL_MONSTER_EXAMINE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.MONSTER_EXAMINE),
	SPELL_NPC_CONTACT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.NPC_CONTACT),
	SPELL_CURE_OTHER(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.CURE_OTHER),
	SPELL_HUMIDIFY(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.HUMIDIFY),
	SPELL_MOONCLAN_TELEPORT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.MOONCLAN_TELEPORT),
	SPELL_TELE_GROUP_MOONCLAN(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.TELE_GROUP_MOONCLAN),
	SPELL_CURE_ME(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.CURE_ME),
	SPELL_HUNTER_KIT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.HUNTER_KIT),
	SPELL_WATERBIRTH_TELEPORT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.WATERBIRTH_TELEPORT),
	SPELL_TELE_GROUP_WATERBIRTH(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.TELE_GROUP_WATERBIRTH),
	SPELL_CURE_GROUP(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.CURE_GROUP),
	SPELL_STAT_SPY(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.STAT_SPY),
	SPELL_BARBARIAN_TELEPORT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.BARBARIAN_TELEPORT),
	SPELL_TELE_GROUP_BARBARIAN(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.TELE_GROUP_BARBARIAN),
	SPELL_SUPERGLASS_MAKE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.SUPERGLASS_MAKE),
	SPELL_TAN_LEATHER(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.TAN_LEATHER),
	SPELL_KHAZARD_TELEPORT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.KHAZARD_TELEPORT),
	SPELL_TELE_GROUP_KHAZARD(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.TELE_GROUP_KHAZARD),
	SPELL_DREAM(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.DREAM),
	SPELL_STRING_JEWELLERY(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.STRING_JEWELLERY),
	SPELL_STAT_RESTORE_POT_SHARE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.STAT_RESTORE_POT_SHARE),
	SPELL_MAGIC_IMBUE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.MAGIC_IMBUE),
	SPELL_FERTILE_SOIL(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.FERTILE_SOIL),
	SPELL_BOOST_POTION_SHARE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.BOOST_POTION_SHARE),
	SPELL_FISHING_GUILD_TELEPORT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.FISHING_GUILD_TELEPORT),
	SPELL_TELE_GROUP_FISHING_GUILD(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.TELE_GROUP_FISHING_GUILD),
	SPELL_PLANK_MAKE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.PLANK_MAKE),
	SPELL_CATHERBY_TELEPORT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.CATHERBY_TELEPORT),
	SPELL_TELE_GROUP_CATHERBY(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.TELE_GROUP_CATHERBY),
	SPELL_RECHARGE_DRAGONSTONE(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.RECHARGE_DRAGONSTONE),
	SPELL_ICE_PLATEAU_TELEPORT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.ICE_PLATEAU_TELEPORT),
	SPELL_TELE_GROUP_ICE_PLATEAU(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.TELE_GROUP_ICE_PLATEAU),
	SPELL_ENERGY_TRANSFER(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.ENERGY_TRANSFER),
	SPELL_HEAL_OTHER(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.HEAL_OTHER),
	SPELL_HEAL_GROUP(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.HEAL_GROUP),
	SPELL_SPELLBOOK_SWAP(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.SPELLBOOK_SWAP),
	SPELL_GEOMANCY(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.GEOMANCY),
	SPELL_SPIN_FLAX(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.SPIN_FLAX),
	SPELL_OURANIA_TELEPORT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.OURANIA_TELEPORT),
	/* END OF LUNAR SPELL BOOK WIDGETS*/
	SPELL_TOOLTIP(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.TOOLTIP),
	/* ARCEUUS SPELL BOOK WIDGETS*/
	SPELL_ARCEUUS_HOME_TELEPORT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.ARCEUUS_HOME_TELEPORT),
	SPELL_BATTLEFRONT_TELEPORT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.BATTLEFRONT_TELEPORT),
	/* END OF ARCEUUS SPELL BOOK WIDGETS*/
	SPELLBOOK_FILTER_SECTION_PARENT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.FILTER_SECTION_PARENT),
	SPELLBOOK_FILTER_BUTTONS_PARENT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.FILTER_BUTTONS_PARENT),
	SPELLBOOK_FILTER_BUTTON_PARENT(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.FILTER_BUTTON_PARENT),
	SPELLBOOK_FILTER_BUTTON(ComponentID.SPELLBOOK_GROUP_ID, ComponentID.SpellBook.FILTER_BUTTON),


	KOUREND_FAVOUR_OVERLAY(ComponentID.KOUREND_FAVOUR_GROUP_ID, ComponentID.KourendFavour.KOUREND_FAVOUR_OVERLAY),
	ZEAH_MESS_HALL_COOKING_DISPLAY(ComponentID.ZEAH_MESS_HALL_GROUP_ID, ComponentID.Zeah.MESS_HALL_COOKING_DISPLAY),

	LOOTING_BAG_CONTAINER(ComponentID.LOOTING_BAG_GROUP_ID, ComponentID.LootingBag.LOOTING_BAG_INVENTORY),

	SKOTIZO_CONTAINER(ComponentID.SKOTIZO_GROUP_ID, ComponentID.Skotizo.CONTAINER),

	MULTICOMBAT_FIXED(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.MULTICOMBAT_INDICATOR),
	MULTICOMBAT_RESIZEABLE(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, ComponentID.ResizableViewport.MULTICOMBAT_INDICATOR),


	FULLSCREEN_MAP_ROOT(ComponentID.FULLSCREEN_MAP_GROUP_ID, ComponentID.FullScreenMap.ROOT),

	QUESTLIST_BOX(ComponentID.QUESTLIST_GROUP_ID, ComponentID.QuestList.BOX),
	QUESTLIST_CONTAINER(ComponentID.QUESTLIST_GROUP_ID, ComponentID.QuestList.CONTAINER),
	QUESTLIST_SCROLLBAR(ComponentID.QUESTLIST_GROUP_ID, ComponentID.QuestList.SCROLLBAR),
	QUESTLIST_FREE_CONTAINER(ComponentID.QUESTLIST_GROUP_ID, ComponentID.QuestList.FREE_CONTAINER),
	QUESTLIST_MEMBERS_CONTAINER(ComponentID.QUESTLIST_GROUP_ID, ComponentID.QuestList.MEMBERS_CONTAINER),
	QUESTLIST_MINIQUEST_CONTAINER(ComponentID.QUESTLIST_GROUP_ID, ComponentID.QuestList.MINIQUEST_CONTAINER),

	MUSICTAB_INTERFACE(ComponentID.MUSICTAB_GROUP_ID, 1),
	MUSICTAB_SONG_BOX(ComponentID.MUSICTAB_GROUP_ID, 2),
	MUSICTAB_ALL_SONGS(ComponentID.MUSICTAB_GROUP_ID, 3),
	MUSICTAB_SCROLLBAR(ComponentID.MUSICTAB_GROUP_ID, 4),
	MUSICTAB_PLAYING(ComponentID.MUSICTAB_GROUP_ID, 5),
	MUSICTAB_CURRENT_SONG_NAME(ComponentID.MUSICTAB_GROUP_ID, 6),
	MUSICTAB_AUTO_BUTTON_LISTENER(ComponentID.MUSICTAB_GROUP_ID, 7),
	MUSICTAB_AUTO_BUTTON(ComponentID.MUSICTAB_GROUP_ID, 8),
	MUSICTAB_MANUAL_BUTTON_LISTENER(ComponentID.MUSICTAB_GROUP_ID, 9),
	MUSICTAB_MANUAL_BUTTON(ComponentID.MUSICTAB_GROUP_ID, 10),
	MUSICTAB_LOOP_BUTTON_LISTENER(ComponentID.MUSICTAB_GROUP_ID, 11),
	MUSICTAB_LOOP_BUTTON(ComponentID.MUSICTAB_GROUP_ID, 12),
	MUSICTAB_UNLOCKED_SONGS(ComponentID.MUSICTAB_GROUP_ID, 13),

	QUESTTAB_QUEST_TAB(ComponentID.QUESTTAB_GROUP_ID, ComponentID.QuestTab.QUEST_TAB),

	EQUIPMENT_MELEE_STRENGTH(ComponentID.EQUIPMENT_PAGE_GROUP_ID, ComponentID.EquipmentWidgetIdentifiers.MELEE_STRENGTH),
	EQUIPMENT_RANGED_STRENGTH(ComponentID.EQUIPMENT_PAGE_GROUP_ID, ComponentID.EquipmentWidgetIdentifiers.RANGED_STRENGTH),
	EQUIPMENT_MAGIC_DAMAGE(ComponentID.EQUIPMENT_PAGE_GROUP_ID, ComponentID.EquipmentWidgetIdentifiers.MAGIC_DAMAGE),
	EQUIP_YOUR_CHARACTER(ComponentID.EQUIPMENT_PAGE_GROUP_ID, ComponentID.EquipmentWidgetIdentifiers.EQUIP_YOUR_CHARACTER),

	FIXED_BANK_PIN(ComponentID.FIXED_VIEWPORT_GROUP_ID, ComponentID.FixedViewport.BANK_PIN),
	RESIZABLE_BANK_PIN(ComponentID.RESIZABLE_VIEWPORT_OLD_SCHOOL_BOX_GROUP_ID, ComponentID.ResizableViewport.BANK_PIN),
	RESIZABLE_BOTTOM_LINE_BANK_PIN(ComponentID.RESIZABLE_VIEWPORT_BOTTOM_LINE_GROUP_ID, ComponentID.ResizableViewportBottomLine.BANK_PIN),
	BANK_PIN_TOP_LEFT_TEXT(ComponentID.BANK_PIN_GROUP_ID, ComponentID.BankPin.TOP_LEFT_TEXT),
	BANK_PIN_EXIT_BUTTON(ComponentID.BANK_PIN_GROUP_ID, ComponentID.BankPin.EXIT_BUTTON),
	BANK_PIN_FORGOT_BUTTON(ComponentID.BANK_PIN_GROUP_ID, ComponentID.BankPin.FORGOT_BUTTON),
	BANK_PIN_FIRST_ENTERED(ComponentID.BANK_PIN_GROUP_ID, ComponentID.BankPin.FIRST_ENTERED),
	BANK_PIN_SECOND_ENTERED(ComponentID.BANK_PIN_GROUP_ID, ComponentID.BankPin.SECOND_ENTERED),
	BANK_PIN_THIRD_ENTERED(ComponentID.BANK_PIN_GROUP_ID, ComponentID.BankPin.THIRD_ENTERED),
	BANK_PIN_FOURTH_ENTERED(ComponentID.BANK_PIN_GROUP_ID, ComponentID.BankPin.FOURTH_ENTERED),
	BANK_PIN_INSTRUCTION_TEXT(ComponentID.BANK_PIN_GROUP_ID, ComponentID.BankPin.INSTRUCTION_TEXT),
	BANK_PIN_1(ComponentID.BANK_PIN_GROUP_ID, ComponentID.BankPin.BUTTON_1),
	BANK_PIN_2(ComponentID.BANK_PIN_GROUP_ID, ComponentID.BankPin.BUTTON_2),
	BANK_PIN_3(ComponentID.BANK_PIN_GROUP_ID, ComponentID.BankPin.BUTTON_3),
	BANK_PIN_4(ComponentID.BANK_PIN_GROUP_ID, ComponentID.BankPin.BUTTON_4),
	BANK_PIN_5(ComponentID.BANK_PIN_GROUP_ID, ComponentID.BankPin.BUTTON_5),
	BANK_PIN_6(ComponentID.BANK_PIN_GROUP_ID, ComponentID.BankPin.BUTTON_6),
	BANK_PIN_7(ComponentID.BANK_PIN_GROUP_ID, ComponentID.BankPin.BUTTON_7),
	BANK_PIN_8(ComponentID.BANK_PIN_GROUP_ID, ComponentID.BankPin.BUTTON_8),
	BANK_PIN_9(ComponentID.BANK_PIN_GROUP_ID, ComponentID.BankPin.BUTTON_9),
	BANK_PIN_10(ComponentID.BANK_PIN_GROUP_ID, ComponentID.BankPin.BUTTON_10),

	XP_DROP_1(ComponentID.EXPERIENCE_DROP_GROUP_ID, ComponentID.ExperienceDrop.DROP_1),
	XP_DROP_2(ComponentID.EXPERIENCE_DROP_GROUP_ID, ComponentID.ExperienceDrop.DROP_2),
	XP_DROP_3(ComponentID.EXPERIENCE_DROP_GROUP_ID, ComponentID.ExperienceDrop.DROP_3),
	XP_DROP_4(ComponentID.EXPERIENCE_DROP_GROUP_ID, ComponentID.ExperienceDrop.DROP_4),
	XP_DROP_5(ComponentID.EXPERIENCE_DROP_GROUP_ID, ComponentID.ExperienceDrop.DROP_5),
	XP_DROP_6(ComponentID.EXPERIENCE_DROP_GROUP_ID, ComponentID.ExperienceDrop.DROP_6),
	XP_DROP_7(ComponentID.EXPERIENCE_DROP_GROUP_ID, ComponentID.ExperienceDrop.DROP_7),

	ITEMS_KEPT_CUSTOM_TEXT_CONTAINER(ComponentID.KEPT_ON_DEATH_GROUP_ID, ComponentID.KeptOnDeath.CUSTOM_TEXT_CONTAINER),
	ITEMS_KEPT_ON_DEATH_CONTAINER(ComponentID.ITEMS_KEPT_ON_DEATH_GROUP_ID, ComponentID.KeptOnDeath.KEPT_ITEMS_CONTAINER),
	ITEMS_KEPT_ON_DEATH_TEXT(ComponentID.ITEMS_KEPT_ON_DEATH_GROUP_ID, ComponentID.KeptOnDeath.KEPT_ITEMS_TEXT),
	ITEMS_LOST_ON_DEATH_TEXT(ComponentID.ITEMS_KEPT_ON_DEATH_GROUP_ID, ComponentID.KeptOnDeath.LOST_ITEMS_TEXT),
	ITEMS_LOST_ON_DEATH_CONTAINER(ComponentID.ITEMS_KEPT_ON_DEATH_GROUP_ID, ComponentID.KeptOnDeath.LOST_ITEMS_CONTAINER),
	ITEMS_KEPT_INFORMATION_CONTAINER(ComponentID.ITEMS_KEPT_ON_DEATH_GROUP_ID, ComponentID.KeptOnDeath.INFORMATION_CONTAINER),
	ITEMS_KEPT_SAFE_ZONE_CONTAINER(ComponentID.ITEMS_KEPT_ON_DEATH_GROUP_ID, ComponentID.KeptOnDeath.SAFE_ZONE_CONTAINER),
	ITEMS_LOST_VALUE(ComponentID.ITEMS_KEPT_ON_DEATH_GROUP_ID, ComponentID.KeptOnDeath.LOST_ITEMS_VALUE),
	ITEMS_KEPT_MAX(ComponentID.ITEMS_KEPT_ON_DEATH_GROUP_ID, ComponentID.KeptOnDeath.MAX_ITEMS_KEPT_ON_DEATH),

	SEED_VAULT_TITLE_CONTAINER(ComponentID.SEED_VAULT_GROUP_ID, ComponentID.SeedVault.TITLE_CONTAINER),
	SEED_VAULT_ITEM_CONTAINER(ComponentID.SEED_VAULT_GROUP_ID, ComponentID.SeedVault.ITEM_CONTAINER),
	SEED_VAULT_ITEM_TEXT(ComponentID.SEED_VAULT_GROUP_ID, ComponentID.SeedVault.ITEM_TEXT),

	JEWELLERY_BOX_DUEL_RING(ComponentID.JEWELLERY_BOX_GROUP_ID, ComponentID.JewelBox.DUEL_RING),
	JEWELLERY_BOX_GAME_NECK(ComponentID.JEWELLERY_BOX_GROUP_ID, ComponentID.JewelBox.GAME_NECK),
	JEWELLERY_BOX_COMB_BRAC(ComponentID.JEWELLERY_BOX_GROUP_ID, ComponentID.JewelBox.COMB_BRAC),
	JEWELLERY_BOX_SKIL_NECK(ComponentID.JEWELLERY_BOX_GROUP_ID, ComponentID.JewelBox.SKIL_NECK),
	JEWELLERY_BOX_RING_OFGP(ComponentID.JEWELLERY_BOX_GROUP_ID, ComponentID.JewelBox.RING_OFGP),
	JEWELLERY_BOX_AMUL_GLOR(ComponentID.JEWELLERY_BOX_GROUP_ID, ComponentID.JewelBox.AMUL_GLOR);

	private final int groupId;
	private final int childId;

	ComponentInfo(int groupId, int childId) {
		this.groupId = groupId;
		this.childId = childId;
	}

	/**
	 * Gets the ID of the group-child pairing.
	 *
	 * @return the ID
	 */
	public int getId() {
		return groupId << 16 | childId;
	}

	/**
	 * Gets the group ID of the pair.
	 *
	 * @return the group ID
	 */
	public int getGroupId() {
		return groupId;
	}

	/**
	 * Gets the ID of the child in the group.
	 *
	 * @return the child ID
	 */
	public int getChildId() {
		return childId;
	}

	/**
	 * Gets the packed widget ID.
	 *
	 * @return the packed ID
	 */
	public int getPackedId() {
		return groupId << 16 | childId;
	}

	/**
	 * Utility method that converts an ID returned by {@link #getId()} back
	 * to its group ID.
	 *
	 * @param id passed group-child ID
	 * @return the group ID
	 */
	public static int TO_GROUP(int id) {
		return id >>> 16;
	}

	/**
	 * Utility method that converts an ID returned by {@link #getId()} back
	 * to its child ID.
	 *
	 * @param id passed group-child ID
	 * @return the child ID
	 */
	public static int TO_CHILD(int id) {
		return id & 0xFFFF;
	}

	/**
	 * Packs the group and child IDs into a single integer.
	 *
	 * @param groupId the group ID
	 * @param childId the child ID
	 * @return the packed ID
	 */
	public static int PACK(int groupId, int childId) {
		return groupId << 16 | childId;
	}

}
