package io.ruin.model.item.actions.impl.pet.perk;

public enum PerkType {

	BONUS_EXP,
	BONUS_DR,
	INVENTORY_AUTO_LOOT,
	BONUS_STRENGTH,
	DRAGON_FIRE_IMMUNITY,
	BONUS_SMITE,
	BANK_AUTO_LOOT,
	KEEP_BONUS_ITEMS_ON_DEATH,
	BONUS_POINTS,
	WALKER_PERK,
	BETA_DONATORS,

	KARUULM_IMMUNITY
}