package io.ruin.model.item.actions.impl;

import io.ruin.cache.ItemID;

public enum PotionDrink {
	/**
	 * Regular potions
	 */
	ATTACK(new int[]{ItemID.ATTACK_POTION4, ItemID.ATTACK_POTION3, ItemID.ATTACK_POTION2, ItemID.ATTACK_POTION1}),
	ANTIPOISON(new int[]{ItemID.ANTIPOISON4, ItemID.ANTIPOISON3, ItemID.ANTIPOISON2, ItemID.ANTIPOISON1}),
	RELICYMS_BALM(new int[]{ItemID.RELICYMS_BALM4, ItemID.RELICYMS_BALM3, ItemID.RELICYMS_BALM2, ItemID.RELICYMS_BALM1}),
	STRENGTH(new int[]{ItemID.STRENGTH_POTION4, ItemID.STRENGTH_POTION3, ItemID.STRENGTH_POTION2, ItemID.STRENGTH_POTION1}),

	RESTORE(new int[]{ItemID.RESTORE_POTION4, ItemID.RESTORE_POTION3, ItemID.RESTORE_POTION2, ItemID.RESTORE_POTION1}),
	GUTHIX_BALANCE(new int[]{ItemID.GUTHIX_BALANCE4, ItemID.GUTHIX_BALANCE3, ItemID.GUTHIX_BALANCE2, ItemID.GUTHIX_BALANCE1}),
	ENERGY(new int[]{ItemID.ENERGY_POTION4, ItemID.ENERGY_POTION3, ItemID.ENERGY_POTION2, ItemID.ENERGY_POTION1}),
	DEFENCE(new int[]{ItemID.DEFENCE_POTION4, ItemID.DEFENCE_POTION3, ItemID.DEFENCE_POTION2, ItemID.DEFENCE_POTION1}),
	AGILITY(new int[]{ItemID.AGILITY_POTION4, ItemID.AGILITY_POTION3, ItemID.AGILITY_POTION2, ItemID.AGILITY_POTION1}),
	COMBAT(new int[]{ItemID.COMBAT_POTION4, ItemID.COMBAT_POTION3, ItemID.COMBAT_POTION2, ItemID.COMBAT_POTION1}),
	PRAYER(new int[]{ItemID.PRAYER_POTION4, ItemID.PRAYER_POTION3, ItemID.PRAYER_POTION2, ItemID.PRAYER_POTION1}),
	SUPER_ATTACK(new int[]{ItemID.SUPER_ATTACK4, ItemID.SUPER_ATTACK3, ItemID.SUPER_ATTACK2, ItemID.SUPER_ATTACK1}),
	SUPER_ANTIPOISON(new int[]{ItemID.SUPERANTIPOISON4, ItemID.SUPERANTIPOISON3, ItemID.SUPERANTIPOISON2, ItemID.SUPERANTIPOISON1}),
	FISHING(new int[]{ItemID.FISHING_POTION4, ItemID.FISHING_POTION3, ItemID.FISHING_POTION2, ItemID.FISHING_POTION1}),
	SUPER_ENERGY(new int[]{ItemID.SUPER_ENERGY4, ItemID.SUPER_ENERGY3, ItemID.SUPER_ENERGY2, ItemID.SUPER_ENERGY1}),
	HUNTER(new int[]{ItemID.HUNTER_POTION4, ItemID.HUNTER_POTION3, ItemID.HUNTER_POTION2, ItemID.HUNTER_POTION1}),
	SUPER_STRENGTH(new int[]{ItemID.SUPER_STRENGTH4, ItemID.SUPER_STRENGTH3, ItemID.SUPER_STRENGTH2, ItemID.SUPER_STRENGTH1}),
	MAGIC_ESSENCE(new int[]{ItemID.MAGIC_ESSENCE4, ItemID.MAGIC_ESSENCE3, ItemID.MAGIC_ESSENCE2, ItemID.MAGIC_ESSENCE1}),
	SUPER_RESTORE(new int[]{ItemID.SUPER_RESTORE4, ItemID.SUPER_RESTORE3, ItemID.SUPER_RESTORE2, ItemID.SUPER_RESTORE1}),
	SANFEW_SERUM(new int[]{ItemID.SANFEW_SERUM4, ItemID.SANFEW_SERUM3, ItemID.SANFEW_SERUM2, ItemID.SANFEW_SERUM1}),
	SUPER_DEFENCE(new int[]{ItemID.SUPER_DEFENCE4, ItemID.SUPER_DEFENCE3, ItemID.SUPER_DEFENCE2, ItemID.SUPER_DEFENCE1}),
	ANTIDOTE_PLUS(new int[]{ItemID.ANTIDOTE4, ItemID.ANTIDOTE3, ItemID.ANTIDOTE2, ItemID.ANTIDOTE1}),
	ANTIFIRE(new int[]{ItemID.ANTIFIRE_POTION4, ItemID.ANTIFIRE_POTION3, ItemID.ANTIFIRE_POTION2, ItemID.ANTIFIRE_POTION1}),
	RANGING(new int[]{ItemID.RANGING_POTION4, ItemID.RANGING_POTION3, ItemID.RANGING_POTION2, ItemID.RANGING_POTION1}),

	MAGIC(new int[]{ItemID.MAGIC_POTION4, ItemID.MAGIC_POTION3, ItemID.MAGIC_POTION2, ItemID.MAGIC_POTION1}),
	STAMINA(new int[]{ItemID.STAMINA_POTION4, ItemID.STAMINA_POTION3, ItemID.STAMINA_POTION2, ItemID.STAMINA_POTION1}),
	ZAMORAK_BREW(new int[]{ItemID.ZAMORAK_BREW4, ItemID.ZAMORAK_BREW3, ItemID.ZAMORAK_BREW2, ItemID.ZAMORAK_BREW1}),
	ANTIDOTE_PLUS_PLUS(new int[]{ItemID.ANTIDOTE4_5952, ItemID.ANTIDOTE3_5954, ItemID.ANTIDOTE2_5956, ItemID.ANTIDOTE1_5958}),
	SARADOMIN_BREW(new int[]{ItemID.SARADOMIN_BREW4, ItemID.SARADOMIN_BREW3, ItemID.SARADOMIN_BREW2, ItemID.SARADOMIN_BREW1}),
	EXTENDED_ANTIFIRE(new int[]{ItemID.EXTENDED_ANTIFIRE4, ItemID.EXTENDED_ANTIFIRE3, ItemID.EXTENDED_ANTIFIRE2, ItemID.EXTENDED_ANTIFIRE1}),
	ANTI_VENOM(new int[]{ItemID.ANTIVENOM4, ItemID.ANTIVENOM3, ItemID.ANTIVENOM2, ItemID.ANTIVENOM1}),
	SUPER_COMBAT(new int[]{ItemID.SUPER_COMBAT_POTION4, ItemID.SUPER_COMBAT_POTION3, ItemID.SUPER_COMBAT_POTION2, ItemID.SUPER_COMBAT_POTION1}),
	SUPER_ANTIFIRE(new int[]{ItemID.SUPER_ANTIFIRE_POTION4, ItemID.SUPER_ANTIFIRE_POTION3, ItemID.SUPER_ANTIFIRE_POTION2, ItemID.SUPER_ANTIFIRE_POTION1}),
	SUPER_ANTI_VENOM(new int[]{ItemID.ANTIVENOM4_12913, ItemID.ANTIVENOM3_12915, ItemID.ANTIVENOM2_12917, ItemID.ANTIVENOM1_12919}),

	EXTENDED_SUPER_ANTIFIRE(new int[]{ItemID.EXTENDED_SUPER_ANTIFIRE4, ItemID.EXTENDED_SUPER_ANTIFIRE3, ItemID.EXTENDED_SUPER_ANTIFIRE2, ItemID.EXTENDED_SUPER_ANTIFIRE1}),

	/**
	 * Combination Potions
	 */

	BASTION(new int[]{ItemID.BASTION_POTION4, ItemID.BASTION_POTION3, ItemID.BASTION_POTION2, ItemID.BASTION_POTION1}),
	BATTLEMAGE(new int[]{ItemID.BATTLEMAGE_POTION4, ItemID.BATTLEMAGE_POTION3, ItemID.BATTLEMAGE_POTION2, ItemID.BATTLEMAGE_POTION1}),

	/**
	 * Divine potions
	 */

	DIVINE_SUPER_ATTACK(new int[]{ItemID.DIVINE_SUPER_ATTACK_POTION4, ItemID.DIVINE_SUPER_ATTACK_POTION3, ItemID.DIVINE_SUPER_ATTACK_POTION2, ItemID.DIVINE_SUPER_ATTACK_POTION1}),
	DIVINE_SUPER_STRENGTH(new int[]{ItemID.DIVINE_SUPER_STRENGTH_POTION4, ItemID.DIVINE_SUPER_STRENGTH_POTION3, ItemID.DIVINE_SUPER_STRENGTH_POTION2, ItemID.DIVINE_SUPER_STRENGTH_POTION1}),
	DIVINE_SUPER_DEFENCE(new int[]{ItemID.DIVINE_SUPER_DEFENCE_POTION4, ItemID.DIVINE_SUPER_DEFENCE_POTION3, ItemID.DIVINE_SUPER_DEFENCE_POTION2, ItemID.DIVINE_SUPER_DEFENCE_POTION1}),
	DIVINE_RANGING(new int[]{ItemID.DIVINE_RANGING_POTION4, ItemID.DIVINE_RANGING_POTION3, ItemID.DIVINE_RANGING_POTION2, ItemID.DIVINE_RANGING_POTION1}),
	DIVINE_MAGIC(new int[]{ItemID.DIVINE_MAGIC_POTION4, ItemID.DIVINE_MAGIC_POTION3, ItemID.DIVINE_MAGIC_POTION2, ItemID.DIVINE_MAGIC_POTION1}),
	DIVINE_BASTION(new int[]{24635, 24638, 24641, 24644}),
	MOONLIGHT_POTION(new int[]{29080, 29081, 29082, 29083}),
	DIVINE_BATTLEMAGE(new int[]{24623, 24626, 24629, 24632}),
	DIVINE_SUPER_COMBAT(new int[]{ItemID.DIVINE_SUPER_COMBAT_POTION4, ItemID.DIVINE_SUPER_COMBAT_POTION3, ItemID.DIVINE_SUPER_COMBAT_POTION2, ItemID.DIVINE_SUPER_COMBAT_POTION1}),

	/**
	 * Raids potions
	 */
	ELDER_MINUS(new int[]{ItemID.ELDER_4, ItemID.ELDER_3, ItemID.ELDER_2, ItemID.ELDER_1}),
	ELDER_REGULAR(new int[]{ItemID.ELDER_POTION_4, ItemID.ELDER_POTION_3, ItemID.ELDER_POTION_2, ItemID.ELDER_POTION_1}),
	ELDER_PLUS(new int[]{ItemID.ELDER_4_20924, ItemID.ELDER_3_20923, ItemID.ELDER_2_20922, ItemID.ELDER_1_20921}),
	TWISTED_MINUS(new int[]{ItemID.TWISTED_4, ItemID.TWISTED_3, ItemID.TWISTED_2, ItemID.TWISTED_1}),
	TWISTED_REGULAR(new int[]{ItemID.TWISTED_POTION_4, ItemID.TWISTED_POTION_3, ItemID.TWISTED_POTION_2, ItemID.TWISTED_POTION_1}),
	TWISTED_PLUS(new int[]{ItemID.TWISTED_4_20936, ItemID.TWISTED_3_20935, ItemID.TWISTED_2_20934, ItemID.TWISTED_1_20933}),
	KODAI_MINUS(new int[]{ItemID.KODAI_4, ItemID.KODAI_3, ItemID.KODAI_2, ItemID.KODAI_1}),
	KODAI_REGULAR(new int[]{ItemID.KODAI_POTION_4, ItemID.KODAI_POTION_3, ItemID.KODAI_POTION_2, ItemID.KODAI_POTION_1}),
	KODAI_PLUS(new int[]{ItemID.KODAI_4_20948, ItemID.KODAI_3_20947, ItemID.KODAI_2_20946, ItemID.KODAI_1_20945}),
	REVITALISATION_MINUS(new int[]{ItemID.REVITALISATION_4, ItemID.REVITALISATION_3, ItemID.REVITALISATION_2, ItemID.REVITALISATION_1}),
	REVITALISATION_REGULAR(new int[]{ItemID.REVITALISATION_POTION_4, ItemID.REVITALISATION_POTION_3, ItemID.REVITALISATION_POTION_2, ItemID.REVITALISATION_POTION_1}),
	REVITALISATION_PLUS(new int[]{ItemID.REVITALISATION_4_20960, ItemID.REVITALISATION_3_20959, ItemID.REVITALISATION_2_20958, ItemID.REVITALISATION_1_20957}),
	PRAYER_ENHANCE_MINUS(new int[]{ItemID.PRAYER_ENHANCE_4, ItemID.PRAYER_ENHANCE_3, ItemID.PRAYER_ENHANCE_2, ItemID.PRAYER_ENHANCE_1}),
	PRAYER_ENHANCE_REGULAR(new int[]{ItemID.PRAYER_ENHANCE_4_20968, ItemID.PRAYER_ENHANCE_3_20967, ItemID.PRAYER_ENHANCE_2_20966, ItemID.PRAYER_ENHANCE_1_20965}),
	PRAYER_ENHANCE_PLUS(new int[]{ItemID.PRAYER_ENHANCE_4_20972, ItemID.PRAYER_ENHANCE_3_20971, ItemID.PRAYER_ENHANCE_2_20970, ItemID.PRAYER_ENHANCE_1_20969}),
	XERIC_AID_MINUS(new int[]{ItemID.XERICS_AID_4, ItemID.XERICS_AID_3, ItemID.XERICS_AID_2, ItemID.XERICS_AID_1}),
	XERIC_AID_REGULAR(new int[]{ItemID.XERICS_AID_4_20980, ItemID.XERICS_AID_3_20979, ItemID.XERICS_AID_2_20978, ItemID.XERICS_AID_1_20977}),
	XERIC_AID_PLUS(new int[]{ItemID.XERICS_AID_4_20984, ItemID.XERICS_AID_3_20983, ItemID.XERICS_AID_2_20982, ItemID.XERICS_AID_1_20981}),
	OVERLOAD_MINUS(new int[]{ItemID.OVERLOAD_4_20988, ItemID.OVERLOAD_3_20987, ItemID.OVERLOAD_2_20986, ItemID.OVERLOAD_1_20985}),
	OVERLOAD_REGULAR(new int[]{ItemID.OVERLOAD_4_20992, ItemID.OVERLOAD_3_20991, ItemID.OVERLOAD_2_20990, ItemID.OVERLOAD_1_20989}),
	OVERLOAD_PLUS(new int[]{ItemID.OVERLOAD_4_20996, ItemID.OVERLOAD_3_20995, ItemID.OVERLOAD_2_20994, ItemID.OVERLOAD_1_20993}),
	EGNIOL_POTION(new int[]{ItemID.EGNIOL_POTION_4, ItemID.EGNIOL_POTION_3, ItemID.EGNIOL_POTION_2, ItemID.EGNIOL_POTION_1}),
	BLIGHTED_SUPER_RESTORE(new int[]{24598, 24601, 24603, 24605}),
	;


	public final int[] vialIds;
	public boolean raidsPotion;

	PotionDrink(int[] vialIds) {
		this.vialIds = vialIds;
	}
}
