package io.ruin.model.entity.player;

import com.google.gson.annotations.SerializedName;
import io.ruin.content.objects.Cannon;
import io.ruin.model.activities.ActivityTimer;
import io.ruin.model.activities.barrows.BarrowsBrother;
import io.ruin.model.activities.cluescrolls.ClueSave;
import io.ruin.model.activities.dailytasks.DailyTasks;
import io.ruin.model.activities.fightcaves.FightCaves;
import io.ruin.model.activities.inferno.Inferno;
import io.ruin.model.activities.newcomertasks.NewcomerTasks;
import io.ruin.model.activities.perktree.PerkTasks;
import io.ruin.model.activities.tasks.DailyTask;
import io.ruin.model.activities.wilderness.BountyHunter;
import io.ruin.model.activities.wilderness.WildernessObelisk;
import io.ruin.model.combat.WildernessRating;
import io.ruin.model.content.DailyLoginInterface;
import io.ruin.model.content.DailyVoteInterface;
import io.ruin.model.content.ItemExchange;
import io.ruin.model.content.UpgradeManager;
import io.ruin.model.content.equipmentpresets.GearPreset;
import io.ruin.model.content.loadouts.ZelusLoadout;
import io.ruin.model.content.pvppreset.PvpPreset;
import io.ruin.model.entity.shared.masks.Appearance;
import io.ruin.model.inter.handlers.ServerTeleports;
import io.ruin.model.inter.questtab.QuestTab;
import io.ruin.model.inter.questtab.main.Achievements;
import io.ruin.model.inter.questtab.presets.PresetCustom;
import io.ruin.model.inter.questtab.toggles.EdgevilleBlacklist;
import io.ruin.model.item.Item;
import io.ruin.model.item.ItemContainer;
import io.ruin.model.item.actions.impl.BoneCrusher;
import io.ruin.model.item.actions.impl.pet.Pet;
import io.ruin.model.item.actions.impl.storage.*;
import io.ruin.model.item.containers.Equipment;
import io.ruin.model.item.containers.Inventory;
import io.ruin.model.item.containers.bank.Bank;
import io.ruin.model.item.containers.bank.BankPin;
import io.ruin.model.map.Position;
import io.ruin.model.map.object.actions.impl.FairyRing;
import io.ruin.model.skills.birdhouses.BirdHouseHandler;
import io.ruin.model.skills.construction.House;
import io.ruin.model.skills.construction.actions.impl.costume_room.CostumeStorage;
import io.ruin.model.skills.farming.Farming;
import io.ruin.model.skills.slayer.SlayerTask;
import io.ruin.model.stat.Stat;
import io.ruin.model.stat.StatList;
import io.ruin.model.tutorial.GameModeInterface;
import io.ruin.utility.TickDelay;
import io.ruin.utility.TimedList;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Set;

public abstract class PlayerAttributes extends PlayerAttributesRuntime {

	public CostumeStorage costumeStorage;
	public Position taggedVolatileEarth;

	public static class CollectionLogLegacy {
		public Map<Integer, Integer> collected = new HashMap<>();
	}

	public Stat[] dummyStats;
	public int doubleExpRemaining = 0;
	public int doubleDropsRemaining = 0;
	public int brewImmunityRemaining = 0;
	public int dropRateBoostRemaining = 0;
	public int prayerBoostBonusRemaining = 0;
	public int damageBoostRemaining = 0;
	public int damageReductionBoostRemaining = 0;
	public int loyalty;
	public int displayMode = -1;
	public int lastClaimedDailyLogin = 0;
	public int difficultyChangeCount = 0;
	public int donationDealAmount = 0;
	public int donationDealPoints = 0;
	public int combatAchievementPoints = 0;
	public int combatAchievementsClaimed = 0;
	public int alchsInSamePlace = 0;
	public int slayerTaskKills = 0;
	public int halloweenEventPoints = 0;
	public int holidayEventPoints = 0;
	public int soulStacks = 0;
	public int bossSlayerStartAmount = 0;
	public int currentBossSlayerAmount = 0;
	public int previousBossSlayerStartAmount = -1;
	public int bossSlayerStreak = 0;
	public int currentToARaidId = -1;
	public int fiendishAshesScattered;
	public int vileAshesScattered;
	public int maliciousAshesScattered;
	public int lastHydraRingDrop = -1;
	public int petRolls = 1;
	public int dropRate = 0;
	public int damageForHireHighCount = 0;
	public int damageForHireLowCount = 0;
	public int voteStreak = 0;
	public int loginStreak = 0;
	public int votesClaimed = 0;
	public int lastTotem = 0;
	public int roofSave = 0;
	public int shiftDropSave = 0;
	public int clientLayout = 0;
	public int clanChatSpeeches = 0;
	public int totalPerkTasksCompleted = 0;
	public int totalSlayerTasksCompleted = 0;
	public int totalAchievementsCompleted = 0;
	public int totalSlayerTasksSkipped = 0;
	public int totalReasonPointsSpent = 0;
	public int totalDailyTasksCompleted = 0;
	public int abyssalAshesScattered;
	public int infernalAshesScattered;
	public int perkTreeExperience = 0;
	public int perkTreeLevel = 1;
	public int perkPoints = 0; // used for upgrading perks/unlocking perks
	public int[] varps = new int[30_000];
	public int[] currentDailyTaskAmounts = new int[5];
	public int[] startingDailyTaskAmounts = new int[5];
	public int perkTaskCurrentAmount = 0;
	public int perkTaskAssignedAmount = 0;
	public int nextPlunderRoomId;
	public int totalPyramidPlunderGames = 0;
	public int temporossPoints;
	public int temporossWins;
	public int currentMeleeWeaponUpgrade = BeginnerUpgrades.MELEE_HELM.currentUpgrades;
	public int currentRangeWeaponUpgrade = BeginnerUpgrades.RANGE_WEAPON.currentUpgrades;
	public int currentMeleeHelmUpgrade = BeginnerUpgrades.MELEE_HELM.currentUpgrades;
	public int currentMeleeBodyUpgrade = BeginnerUpgrades.MELEE_BODY.currentUpgrades;
	public int currentMeleeLegsUpgrade = BeginnerUpgrades.MELEE_LEGS.currentUpgrades;
	public int currentRangeHelmUpgrade = BeginnerUpgrades.RANGE_HAT.currentUpgrades;
	public int currentRangeBodyUpgrade = BeginnerUpgrades.RANGE_TOP.currentUpgrades;
	public int currentRangeLegsUpgrade = BeginnerUpgrades.RANGE_LEGS.currentUpgrades;
	public int currentMageHelmUpgrade = BeginnerUpgrades.MAGIC_HAT.currentUpgrades;
	public int currentMageBodyUpgrade = BeginnerUpgrades.MAGIC_TOP.currentUpgrades;
	public int currentMageLegsUpgrade = BeginnerUpgrades.MAGIC_BOTTOM.currentUpgrades;
	public int temporossActivityScore = 0;
	public int temporossrewards;
	public int easyArdy = 0;
	public int medArdy = 0;
	public int hardArdy = 0;
	public int eliteArdy = 0;
	public int desertEasy = 0;
	public int desertMedium = 0;
	public int desertHard = 0;
	public int desertElite = 0;
	public int faladorEasy = 0;
	public int faladorMedium = 0;
	public int faladorHard = 0;
	public int faladorElite = 0;
	public int fremennikEasy = 0;
	public int fremennikMedium = 0;
	public int fremennikHard = 0;
	public int fremennikElite = 0;
	public int kandarinEasy = 0;
	public int kandarinMedium = 0;
	public int kandarinHard = 0;
	public int kandarinElite = 0;
	public int karamjaEasy = 0;
	public int karamjaMedium = 0;
	public int karamjaHard = 0;
	public int karamjaElite = 0;
	public int lumbEasy = 0;
	public int lumbMedium = 0;
	public int lumbHard = 0;
	public int lumbElite = 0;
	public int morytaniaEasy = 0;
	public int morytaniaMedium = 0;
	public int morytaniaHard = 0;
	public int morytaniaElite = 0;
	public int varrockEasy = 0;
	public int varrockMedium = 0;
	public int varrockHard = 0;
	public int varrockElite = 0;
	public int westernEasy = 0;
	public int westernMedium = 0;
	public int westernHard = 0;
	public int westernElite = 0;
	public int wildyEasy = 0;
	public int wildyMedium = 0;
	public int wildyHard = 0;
	public int wildyElite = 0;
	public int kourendEasy = 0;
	public int kourendMedium = 0;
	public int kourendHard = 0;
	public int kourendElite = 0;
	public int groupId;
	public int newGroupId;
	public int specialId;
	public int ELO;
	public int pkPoints;

	// -----------------------------------------------------------------------
	// PvP Preset system  (phantom gear — not persisted to DB)
	// -----------------------------------------------------------------------
	/** True while a PvP preset loadout is active. */
	public transient boolean pvpPresetActive = false;
	/** True when the preset was loaded from the player's own bank (free path, real items). */
	public transient boolean pvpPresetBankMode = false;
	/** The currently active preset, or null. */
	public transient PvpPreset pvpActivePreset = null;
	/** The preset currently highlighted in the selection interface (not yet activated). */
	public transient PvpPreset pvpPresetViewing = null;
	/** Snapshot of real equipment before the preset was applied. */
	public transient Item[] pvpPresetSavedEquipment = null;
	/** Snapshot of real inventory before the preset was applied. */
	public transient Item[] pvpPresetSavedInventory = null;
	/** Snapshot of combat stat levels [fixedLevel, currentLevel, experience] per stat. */
	public transient int[][] pvpPresetSavedStats = null;
	/** Snapshot of rune pouch contents (3 slots) before the preset was applied. */
	public transient io.ruin.model.item.Item[] pvpPresetSavedRunePouch = null;

	public int loyaltyPoints;
	public int bountyPoints;
	/** Current BH killstreak (reset on death). */
	public int bhKillstreak;
	/** Total BH target kills (lifetime). */
	public int bhTargetKills;

	// ── WANTED system ────────────────────────────────────────────────────────
	/** Blood Money amount currently placed on this player's head (0 = no bounty). */
	public int wantedBountyAmount;
	/** Name of the player who placed (or most-recently contributed to) the bounty. */
	public String wantedByName = "";
	// ─────────────────────────────────────────────────────────────────────────
	public int achievementPoints;
	public int reasonPoints;
	public int totalDonated;
	public int donatorPoints;
	public long lastClaimDonation;
	public int votePoints;
	public int totalWorldTaskPoints;
	public int uniquePetsObtained = 0;
	public int slayerTasksCompleted;
	public int slayerSpree = 0;
	public int slayerLocation = 0;
	public int summerPoints = 0;
	public int tutorialStage;
	public int totalExtraBankStorage = 0;
	public int targetOverlaySetting = 0;
	public int KROTAOverlay = 0;
	public int absorptionPoints = 0;
	public int NightmareZonePoints = 0;
	public int nmzRewardPoints;
	public int nmzCofferCoins;
	public int combatXpRate = 100;
	public int brimstoneChestsOpened;
	public int larranChestsOpened;
	public int crystalChestsOpened;
	public int enhancedCrystalChestsOpened;
	public int slayerChestsT1Opened;
	public int slayerChestsT2Opened;
	public int slayerChestsT3Opened;
	public int slayerChestsT4Opened;
	public int theatreOfBloodCompleted;
	public int theatreOfBloodStage = 0;
	public int tobDamageDealt = 0;
	public int tobChestId = 0;
	public int BlueMoonPub = 0;
	public int BarbarianVillage = 0;
	public int KayleeFally = 0;
	public int BartPortSarim = 0;
	public int MalakCanafis = 0;
	public int BartSeers = 0;
	public int BartBandit = 0;
	public int BartEastArdy = 0;
	public int TostigBurthorpe = 0;
	public int BrawlCardSigs = 0;
	public int lastAgilityObjId = -1;
	public int draynorRooftopLaps;
	public int alKharidRooftopLaps;
	public int varrockRooftopLaps;
	public int canifisRooftopLaps;
	public int faladorRooftopLaps;
	public int seersRooftopLaps;
	public int rellekkaRooftopLaps;
	public int ardougneRooftopLaps;
	public int pollnivneachRooftopLaps;
	public int gnomeStrongholdLaps;
	public int barbarianCrouseLaps;
	public int wildernessCourseLaps;
	public int prifddinasLaps;
	public int totalLaps;
	public int smeltedBronzeBars;
	public int smeltedBluriteBars;
	public int smeltedIronBars;
	public int smeltedSilverBars;
	public int smeltedSteelBars;
	public int smeltedGoldBars;
	public int smeltedMithrilBars;
	public int smeltedAdamantBars;
	public int smeltedRuniteBars;
	public int smeltedCorruptBars;
	public int smithedBars;
	public int blastFurnaceCofferAmount = 0;
	public int blastFurnaceOres = 0;
	public int blastFurnaceCoalAmount;
	public int blastFurnaceBars = 0;
	public int collection_log_current_entry = 0;
	public int collection_log_current_struct = 471;
	public int collection_log_current_tab = 0;
	public int collectionLogTotalItemsCollected;
	public int minedClay;
	public int minedCopper;
	public int minedTin;
	public int minedIron;
	public int minedSilver;
	public int minedCoal;
	public int minedGold;
	public int minedMithril;
	public int minedLovakite;
	public int minedAdamant;
	public int minedRunite;
	public int minedAmethyst;
	public int minedRuneEssence;
	public int minedPureEssence;
	public int minedDarkEssence;
	public int minedGeode;
	public int minedSandstone;
	public int minedGranite;
	public int minedGemRock;
	public int minedCorrupt;
	public int minedBasalt;
	public int minedUrtSalt;
	public int minedTeSalt;
	public int minedEfhSalt;
	public int minedLimestone;
	public int minedAshPile;
	public int choppedRegular;
	public int choppedSapling;
	public int choppedAchey;
	public int choppedOak;
	public int choppedWillow;
	public int choppedTeak;
	public int choppedJuniper;
	public int choppedMaple;
	public int choppedYew;
	public int choppedMagic;
	public int choppedRedwood;
	public int choppedCelastrus;
	public int choppedMahogany;
	public int choppedCorrupt;
	public int openedBirdsNests;
	public int acquiredBirdsNests;
	public int cookedFood;
	public int burntFood;
	public int jugsOfWineMade;
	public int cookedOnFire;
	public int vegetableStallThieves;
	public int bakerStallThieves;
	public int craftingStallThieves;
	public int monkeyFoodStallThieves;
	public int monkeyGeneralStallThieves;
	public int teaStallThieves;
	public int silkStallThieves;
	public int wineStallThieves;
	public int seedStallThieves;
	public int furStallThieves;
	public int fishStallThieves;
	public int crossbowStallThieves;
	public int silverStallThieves;
	public int spiceStallThieves;
	public int magicStallThieves;
	public int scimitarStallThieves;
	public int gemStallThieves;
	public int gemMorStallThieves;
	public int oreStallThieves;
	public int pickpocketMan;
	public int pickpocketFarmer;
	public int pickpocketVyre;
	public int pickpocketWarrior;
	public int pickpocketHamMember;
	public int pickpocketRogue;
	public int pickpocketMasterFarmer;
	public int pickpocketGuard;
	public int pickpocketBandit;
	public int pickpocketKnight;
	public int pickpocketPaladin;
	public int pickpocketGnome;
	public int pickpocketHero;
	public int pickpocketElf;
	public int pickpocketTzhaarHur;
	public int wallSafesCracked;
	public int rougesCastleChests;
	public int pickedLocks;
	public int normalLogsBurnt;
	public int acheyLogsBurnt;
	public int oakLogsBurnt;
	public int willowLogsBurnt;
	public int teakLogsBurnt;
	public int arcticPineLogsBurnt;
	public int mapleLogsBurnt;
	public int mahoganyLogsBurnt;
	public int yewLogsBurnt;
	public int magicLogsBurnt;
	public int redwoodLogsBurnt;
	public int redLogsBurnt;
	public int greenLogsBurnt;
	public int blueLogsBurnt;
	public int whiteLogsBurnt;
	public int purpleLogsBurnt;
	public int kindlingBurnt;
	public int regularBonesBuried;
	public int burntBonesBuried;
	public int batBonesBuried;
	public int wolfBonesBuried;
	public int bigBonesBuried;
	public int longBonesBuried;
	public int curvedBonesBuried;
	public int jogreBonesBuried;
	public int babydragonBonesBuried;
	public int dragonBonesBuried;
	public int zogreBonesBuried;
	public int ourgBonesBuried;
	public int raurgBonesBuried;
	public int monkeyBonesBuried;
	public int wyvernBonesBuried;
	public int dagannothBonesBuried;
	public int lavaDragonBonesBuried;
	public int superiorDragonBonesBuried;
	public int wyrmBonesBuried;
	public int drakeBonesBuried;
	public int hydraBonesBuried;
	public int regularBonesAltar;
	public int burntBonesAltar;
	public int batBonesAltar;
	public int wolfBonesAltar;
	public int bigBonesAltar;
	public int longBonesAltar;
	public int curvedBonesAltar;
	public int jogreBonesAltar;
	public int babydragonBonesAltar;
	public int dragonBonesAltar;
	public int zogreBonesAltar;
	public int ourgBonesAltar;
	public int raurgBonesAltar;
	public int monkeyBonesAltar;
	public int wyvernBonesAltar;
	public int dagannothBonesAltar;
	public int lavaDragonBonesAltar;
	public int superiorDragonBonesAltar;
	public int wyrmBonesAltar;
	public int drakeBonesAltar;
	public int hydraBonesAltar;
	public int totalFishCaught;
	public int craftedAir;
	public int craftedMind;
	public int craftedWater;
	public int craftedEarth;
	public int craftedFire;
	public int craftedBody;
	public int craftedCosmic;
	public int craftedLaw;
	public int craftedNature;
	public int craftedChaos;
	public int craftedDeath;
	public int craftedAstral;
	public int craftedBlood;
	public int craftedSoul;
	public int craftedWrath;
	public int harvestedPotato;
	public int harvestedOnion;
	public int harvestedCabbage;
	public int harvestedTomato;
	public int harvestedSweetcorn;
	public int harvestedStrawberry;
	public int harvestedWatermelon;
	public int harvestedSnapegrass;
	public int harvestedMarigolds;
	public int harvestedRosemary;
	public int harvestedNasturtium;
	public int harvestedWoad;
	public int harvestedLimpwurt;
	public int harvestedGuam;
	public int harvestedMarrentill;
	public int harvestedTarromin;
	public int harvestedHarralander;
	public int harvestedRanarr;
	public int harvestedToadflax;
	public int harvestedIrit;
	public int harvestedAvantoe;
	public int harvestedKwuarm;
	public int harvestedSnapdragon;
	public int harvestedCadantine;
	public int harvestedLantadyme;
	public int harvestedDwarfWeed;
	public int harvestedTorstol;
	public int grownAttas;
	public int grownIasor;
	public int grownKronos;
	public int harvestedHespori;
	public int harvestedBittercap;
	public int grownApple;
	public int grownBanana;
	public int grownOrange;
	public int grownCurry;
	public int grownPineapple;
	public int grownPapaya;
	public int grownPalm;
	public int grownDragonfruit;
	public int grownOak;
	public int grownWillow;
	public int grownMaple;
	public int grownYew;
	public int grownMagic;
	public int grownRedWood;
	public int grownCelastrus;
	public int grownRedberry;
	public int grownCadavaberry;
	public int grownDwellberry;
	public int grownJangerberry;
	public int grownWhiteberry;
	public int grownPoisonIvy;
	public int harvestedBarley;
	public int harvestedHammerstone;
	public int harvestedAsgarnian;
	public int harvestedJute;
	public int harvestedYanillian;
	public int harvestedKrandorian;
	public int harvestedWildblood;
	public int grownCalquat;
	public int grownCactus;
	public int grownSpiritTree;
	public int barbarianAssultHighLevelGambles;
	public int beginnerClueCount;
	public int easyClueCount;
	public int medClueCount;
	public int hardClueCount;
	public int eliteClueCount;
	public int masterClueCount;
	public int minedPaydirt;
	public int cleanedPaydirt;
	public int paydirtInWater;
	public int staminaTicks;
	public int darkEssFragments;
	public int baggedCoal;
	public int gluttony;
	public int yesEmote;
	public int noEmote;
	public int teleportTabsBroken;
	public int runForestRun;
	public int barrowsChestsOpened;
	public int teleportCategoryIndex, teleportSubcategoryIndex;
	public int mageArenaPoints;
	public int previousTeleportX = -1, previousTeleportY, previousTeleportZ;
	public int previousTeleportPrice;
	public int securityPin = 0;
	public int dragSetting = 5;
	public int switchGrading;
	public int crabKills;
	public int strikeSpellCounter;
	public int regularBonesBuriedOrSarcrificed;
	public int runecraftedRunesCounter;
	public int leatherItemsCraftedCounter;
	public int flyFishCaughtCounter;
	public int cookedFishCounter;
	public int oakChoppedCounter;
	public int oakBurnedCounter;
	public int shortbowsFletchedCounter;
	public int agilityLapsRan;
	public int manPickpocketCounter;
	public int herbPatchesRaked;
	public int housesBought;
	public int copperLongtailCatches;
	public int guamsCleanedCounter;
	public int magicCapesBought;
	public int homePoolsUsed;
	public int homeTeleportsUsed;
	public int homeSpellbookAltarsUsed;
	public int enteredMotherloadMineCounter;
	public int makeOverMageCounter;
	public int ibanBlastsCast;
	public int magicShortbowAttacks;
	public int barrowsCompletedKillingAllBrothers;
	public int dragonBonesBuriedOrSacrificed;
	public int astralsCrafted;
	public int bloodsCrafted;
	public int wrathsCrafted;
	public int diamondsCut;
	public int swordfishFished;
	public int swordfishCooked;
	public int mahoganyArmchairsMade;
	public int runiteCrossbowsFletched;
	public int knightsPickpocketed;
	public int tzhaarPickpocketed;
	public int slayerTasksBlockedOrExtended;
	public int treesGrown;
	public int superRestoresMixed;
	public int fairyRingsUsed;
	public int puropuroTravelledCounter;
	public int fighterTorsosEquipped;
	public int totalChinchompasCaught;
	public int slayerHelmsCrafted;
	public int lavaDragonsKilled;
	public int lavaDragonBonesBuriedOrSacrificed;
	public int crystalEquipmentWorn;
	public int chargesCastWearingGodStaff;
	public int magicShortbowsFletched;
	public int revenantKillcount;
	public int herosPickpocketed;
	public int magicLogsChopped;
	public int anglerFishAndSharksCaughtCounter;
	public int anglerFishAndSharksCookedCounter;
	public int motherloadMineUpperUnlockedCounter;
	public int dragonSqShieldsSmithed;
	public int blowpipesFletched;
	public int voidEquippedCounter;
	public int slayerMasterUsedCounter;
	public int prospectorEquippedCounter;
	public int dragonfireShieldsSmithed;
	public int darkCrabsFished;
	public int darkCrabsCooked;
	public int dragonDartsFletched;
	public int amethystArrowTipsCrafted;
	public int wildernessSlayerTasksCompleted;
	public int dragonsAnimated;
	public int demonicThronesCraftedAndSatOn;
	public int dragonImplingOrLuckyImplingCaughtBarehandedCounter;
	public int zenyteAmuletsCraftedAndEnchanted;
	public int divineSuperCombatPotionsMixed;
	public int inferoCounter;
	public int infernalAxesMade;
	public int POHSpiritTreeTeleportsUed;
	public int recoilDamageRemaining = 40;
	public int sufferingCharges;
	public int presetDuelVarp, lastDuelVarp, Whip, Boxing;
	public int duelWins, duelLosses;
	public int gemBagDiamond;
	public int gemBagRuby;
	public int gemBagEmerald;
	public int gemBagSapphire;
	public int gemBagDragonstone;
	public int gemBagOpal;
	public int gemBagJade;
	public int gemBagTopaz;
	public int gemBagOnyx;
	public int gemBagZenyte;
	public int herbSackGuamLeaf;
	public int herbSackMarrentill;
	public int herbSackTarromin;
	public int herbSackHarralander;
	public int herbSackRanarrWeed;
	public int herbSackToadflax;
	public int herbSackIritLeaf;
	public int herbSackAvantoe;
	public int herbSackKwuarm;
	public int herbSackSnapdragon;
	public int herbSackCadantine;
	public int herbSackLantadyme;
	public int herbSackDwarfWeed;
	public int herbSackTorstol;
	public int lifetimeWintertodtPoints;
	public int wintertodtSubdued;
	public int wintertodtHighscore;
	public int caughtSwift, caughtWarbler, caughtLongtail, caughtTwitch, caughtWagtail;
	public int caughtGreyChinchompa, caughtRedChinchompa, caughtBlackChinchompa;
	public int caughtSwampLizard, caughtOrangeSalamander, caughtRedSalamander, caughtBlackSalamander;
	public int totalSuccessfulUpgrades;
	public int totalAttemptedUpgrades;
	public int abyssalBloodwhipUpgrades;
	public int abyssalBloodwhipAttempts;
	public int dscimeUpgrades;
	public int dscimeAttempts;
	public int creationClawUpgrades;
	public int creationClawAttempts;
	public int bloodlineChainmaceUpgrades;
	public int bloodlineChainmaceAttempts;
	public int bloodlineBowUpgrades;
	public int bloodlineBowAttempts;
	public int corruptedOrbUpgrades;
	public int corruptedOrbAttempts;
	public int zamorakGodswordUpgrades;
	public int zamorakGodswordAttempts;
	public int bandosGodswordUpgrades;
	public int bandosGodswordAttempts;
	public int saradominGodswordUpgrades;
	public int saradominGodswordAttempts;
	public int cursedVestasLongswordUpgrades;
	public int cursedVestasLongswordAttempts;
	public int armadylgodswordUpgrades;
	public int armadylgodswordAttempts;
	public int corruptstaffUpgrades;
	public int corruptstaffAttempts;
	public int corruptjavelinUpgrades;
	public int corruptjavelinAttempts;
	public int galvekcrossbowUpgrades;
	public int galvekcrossbowAttempts;
	public int infernaldinsUpgrades;
	public int infernaldinsAttempts;
	public int galvekmaceUpgrades;
	public int galvekmaceAttempts;
	public int dracoSetUpgrades;
	public int dracoSetAttempts;
	public int fighterTorsoUpgrades;
	public int fighterTorsoAttempts;
	public int fusedbootsUpgrades;
	public int fusedbootsAttempts;
	public int primbootsUpgrades;
	public int primbootsAttempts;
	public int pegasianbootsUpgrades;
	public int pegasianbootsAttempts;
	public int eternalbootsUpgrades;
	public int eternalbootsAttempts;
	public int vampyricFaceguardUpgrades;
	public int vampyricFaceguardAttempts;
	public int lavaCoifUpgrades;
	public int lavaCoifAttempts;
	public int lavaBodyUpgrades;
	public int lavaBodyAttempts;
	public int lavaChapsUpgrades;
	public int lavaChapsAttempts;
	public int dragonDefenderUpgrades;
	public int dragonDefenderAttempts;
	public int corruptLegsUpgrades;
	public int corruptLegsAttempts;
	public int corruptBodyUpgrades;
	public int corruptBodyAttempts;
	public int corruptHelmUpgrades;
	public int corruptHelmAttempts;
	public int necrohatUpgrades;
	public int necrohatAttempts;
	public int necrobodyUpgrades;
	public int necrobodyAttempts;
	public int necrobottomsUpgrades;
	public int necrobottomsAttempts;
	public int fusedHaloUpgrades;
	public int fusedHaloAttempts;
	public int goldenFlippersUpgrades;
	public int goldenFlippersAttempts;
	public int capeofSkullsUpgrades;
	public int capeofSkullsAttempts;
	public int overloadheartUpgrades;
	public int overloadheartAttempts;
	public int combatantheartUpgrades;
	public int combatantheartAttempts;
	public int rangersheartUpgrades;
	public int rangersheartAttempts;
	public int ringundeadUpgrades;
	public int ringundeadAttempts;
	public int ringbeastsUpgrades;
	public int ringbeastsAttempts;
	public int ringarachnidsUpgrades;
	public int ringarachnidsAttempts;
	public int amuletTortureUpgrades;
	public int amuletTortureAttempts;
	public int necklaceAnguishUpgrades;
	public int necklaceAnguishAttempts;
	public int tormentedBraceletUpgrades;
	public int tormentedBraceletAttempts;
	public int occultNecklaceUpgrades;
	public int occultNecklaceAttempts;
	public int blessingAttempts;
	public int blessingUpgrades;
	public int brimstoneRingAttempts;
	public int brimstoneRingUpgrades;
	public int walkerTotemAttempts;
	public int walkerTotemUpgrades;
	public int goldenLeprechaunAttempts;
	public int goldenLeprechaunUpgrades;
	public int slayerExtendedCounter;
	public int slayerTaskRemaining;
	public int slayerTaskAmountAssigned;
	public int wildernessTasksCompleted;
	public int wildernessSlayerPoints;
	public int taskLocation = 0;
	public int currentSlayerMaster;
	public int blackChinchompaBoostTimeLeft;
	public int darkCrabBoostTimeLeft;
	public int antifireTicks;
	public int superAntifireTicks;
	public int KROTACountdownTicks;
	public int jailOresAssigned, jailOresCollected;
	public int currentKillSpree;
	public int highestKillSpree;
	public int highestShutdown;
	public int abyssCreaturesKilled;
	public int dragonAxeSpecial;
	public int infernalAxeSpecial;
	public int infernalPickAxeSpecial;
	public int dragonPickaxeSpecial;
	public int infernalPickaxeSpecial;
	public int lastMakeXAmount;
	public int pkRating = WildernessRating.DEFAULT_RATING;
	public int loyaltyChestReward = 1;
	public int loyaltyChestCount;
	public int loyaltyChestSpree;
	public int highestLoyaltyChestSpree;
	public int first3TimeLeft;
	public int PvmPoints;
	public int BossPoints;
	public int PCPoints;
	public int storeAmountSpent;
	public int tournamentWins = 0;
	public int[] preTournyAttack;
	public int[] preTournyStrength;
	public int[] preTournyDefence;
	public int[] preTournyRanged;
	public int[] preTournyPrayer;
	public int[] preTournyMagic;
	public int[] preTournyHitpoints;
	public int partyAdvertisementsRemaining = 15;
	public int titleId = -1;
	public int teleportPortalUses = 0;
	public int presetsLoaded = 0;
	public int expBonusTimeLeft;
	public int petDropBonusTimeLeft;
	public int rareDropBonusTimeLeft;
	public int modifiedDropBonus;
	public int wildernessPoints;
	public int wintertodtstorePoints;
	public int tournamentPoints;
	public int guaranteedMysteryBoxLoot = 1;
	public int[] dailyTaskProgress = new int[3];
	public int dailyTasksCompleted;
	public int dailyTaskPoints;
	public int riskProtectionTier = 10;
	public int magicSkillcapeUses = 0;
	public int explorerRingUses = 0;
	public int faladorShieldUses = 0;
	public int snowballPoints = 0;
	public int giveawayId = -1;
	public int giveawayEntries = 0;
	public int demonKills = 0;
	public int nestBoxSeeds;
	public int nestBoxRings;
	public int appreciationTicks = 0;
	public int afkPoints = 0;
	public int refundedCredits = 0;
	public int claimedVotes;
	public int voteLimit = 500; // Any time we add a new page we will need to add to this
	public int voteMysteryBoxReward;
	public int implingCaught = 0;
	public int LogId = 0;
	public int LogAmount = 0;
	public int LogStorage = 0;
	public int timesKilledDonatorBoss;
	public int pestPoints;
	public int pestNoviceWins;
	public int pestIntermediateWins;
	public int pestVeteranWins;
	public int lmsKills;
	public int lmsWins;
	public int lmsGamesPlayed;
	public int lmsRank;
	public int mysteriousStrangerVarp;
	public int cannonBallsLoaded;
	public int bossPoints;
	public int SoulWarsSpoilsofWarOpened;
	public int barbAssaultHighLevelGambles;
	public int desertOrbFails = 0;
	public int fremenikOrbFails = 0;
	public int asgarniaOrbFails = 0;
	public int wildernessOrbFails = 0;
	public int varlamoreOrbFails = 0;
	public int shadowOrbFails = 0;
	public int virelithOrbFails = 0;
	public boolean petsCollected;
	public boolean checkGIM = false;
	public boolean reviveActive = false;
	public boolean refClaimed = false;
	public boolean inDynamicMap = false;
	public boolean jailed;
	public boolean hasRef = false;
	public boolean bossTaskInWildy = false;
	public boolean taskInWilderness = false;
	public boolean bossSlayerUnlocked = false;
	public boolean hasFreePerkUnlock = false;
	public boolean canClaimVoteReward = false;
	public boolean claimedVoteToday = false;
	public boolean votedToday = false;
	public boolean canClaimLoginReward = false;
	public boolean claimedLoginToday = false;
	// Interface 1109 is shared between DailyVoteInterface and
	// DailyLoginInterface (same widget, different backing data) -- tracks
	// which one is currently populating it so the single shared claim
	// button (see DailyVoteInterface.register()) knows which claimReward()
	// to call.
	public boolean viewingDailyLoginRewards = false;
	public boolean newcomerRewardClaimed = false;
	public boolean loggedInGauntlet = false;
	public boolean[] currentDailyRewardsClaimed = new boolean[5];
	public boolean dailyTaskCompletionRewardClaimed = false;
	public boolean disarmedPlunderRoomTrap = false;
	public boolean inPyramidPlunder = false;
	public boolean LeftPyramid = false;
	public boolean loot26580;
	public boolean loot26600;
	public boolean loot26601;
	public boolean loot26602;
	public boolean loot26603;
	public boolean loot26604;
	public boolean loot26605;
	public boolean loot26606;
	public boolean loot26607;
	public boolean loot26608;
	public boolean loot26609;
	public boolean loot26610;
	public boolean loot26611;
	public boolean loot26612;
	public boolean loot26613;
	public boolean loot26616;
	public boolean loot26626;
	public boolean temporossTether;
	public boolean joinedTempoross;
	public boolean corruptedGauntletBossChestToBeLooted = false;
	public boolean crystallineGauntletBossChestToBeLooted = false;
	public boolean corruptedGauntletChestToBeLooted = false;
	public boolean crystallineGauntletChestToBeLooted = false;
	public boolean slayerCombatCheck;
	public boolean debug;
	public boolean breakVials;
	public boolean discardBuckets;
	public boolean referral = false;
	public boolean restored;
	public boolean beforeFuckup;
	public boolean edgeHome;
	public boolean tobreward = false;
	public boolean acceptedTheatreRisk;
	public boolean acceptedTheatreCrystals;
	public boolean permBanned;
	public String permBannedReason = "none";
	public boolean motherlodeRestrictedMineUnlocked;
	public boolean motherlodeBiggerSackUnlocked;
	public boolean miningGuildMinerals;
	public boolean goldenArmadylGodsword = false;
	public boolean goldenBandosGodsword = false;
	public boolean goldenSaradominGodsword = false;
	public boolean goldenZamorakGodsword = false;
	public boolean beginnerParkourEnergyBoost;
	public boolean kylieMinnowDialogueStarted;
	public boolean taxidermistDialogueStarted;
	public boolean fairyAerykaDialogueStarted;
	public boolean elnockInquisitorDialogueStarted;
	public boolean elnockInquisitorGivenEquipment;
	public boolean runForestRunUnlockable;
	public boolean canEnterMorUlRek;
	public boolean edgevilleLeverWarning = true;
	public boolean newPlayer = true;
	public boolean allowedAccess = false;
	public boolean krakenWarning = true;
	public boolean smokeBossWarning = true;
	public boolean wyvernWarning = true;
	public boolean capeRoLEffect = true;
	public boolean showTimers = true;
	public boolean colorValuedGroundItems = false;
	public boolean swapRangePrayerPosition;
	public boolean swapMagePrayerPosition;
	public boolean yellFilter;
	public boolean hideTitles = false;
	public boolean crabKillsRewardClaimed = false;
	public boolean strikeSpellCastRewardClaimed = false;
	public boolean regularBonesBuriedOrSarcrificedRewardClaimed = false;
	public boolean runecraftedRunesRewardClaimed = false;
	public boolean leatherItemsCraftedRewardClaimed = false;
	public boolean flyFishCaughtRewardClaimed = false;
	public boolean cookedFishRewardClaimed = false;
	public boolean oakChoppedRewardClaimed = false;
	public boolean oakBurntRewardClaimed = false;
	public boolean shortbowsFletchedRewardClaimed = false;
	public boolean agilityLapsRanRewardClaimed = false;
	public boolean menPickpocketedRewardClaimed = false;
	public boolean herbPatchRakedRewardClaimed = false;
	public boolean houseBoughtRewardClaimed = false;
	public boolean copperLongtailsRewardClaimed = false;
	public boolean guamCleanedRewardClaimed = false;
	public boolean magicCapeRewardClaimed = false;
	public boolean homePoolUsedRewardClaimed = false;
	public boolean homeAltarUsedRewardClaimed = false;
	public boolean motherloadMinedEnteredRewardClaimed = false;
	public boolean makeoverMageUsedRewardClaimed = false;
	public boolean ironBarsSmeltedRewardClaimed = false;
	public boolean voteRewardClaimed = false;
	public boolean easyCasketRewardClaimed = false;
	public boolean slayerTaskCompletedRewardClaimed = false;
	public boolean homeTeleportUsedRewardClaimed = false;
	public boolean crabKillsRewardClaimedItems = false;
	public boolean strikeSpellCastRewardClaimedItems = false;
	public boolean regularBonesBuriedOrSarcrificedRewardClaimedItems = false;
	public boolean runecraftedRunesRewardClaimedItems = false;
	public boolean leatherItemsCraftedRewardClaimedItems = false;
	public boolean flyFishCaughtRewardClaimedItems = false;
	public boolean cookedFishRewardClaimedItems = false;
	public boolean oakChoppedRewardClaimedItems = false;
	public boolean oakBurntRewardClaimedItems = false;
	public boolean shortbowsFletchedRewardClaimedItems = false;
	public boolean agilityLapsRanRewardClaimedItems = false;
	public boolean menPickpocketedRewardClaimedItems = false;
	public boolean herbPatchRakedRewardClaimedItems = false;
	public boolean houseBoughtRewardClaimedItems = false;
	public boolean copperLongtailsRewardClaimedItems = false;
	public boolean guamCleanedRewardClaimedItems = false;
	public boolean magicCapeRewardClaimedItems = false;
	public boolean homePoolUsedRewardClaimedItems = false;
	public boolean homeAltarUsedRewardClaimedItems = false;
	public boolean motherloadMinedEnteredRewardClaimedItems = false;
	public boolean makeoverMageUsedRewardClaimedItems = false;
	public boolean ironBarsSmeltedRewardClaimedItems = false;
	public boolean voteRewardClaimedItems = false;
	public boolean easyCasketRewardClaimedItems = false;
	public boolean slayerTaskCompletedRewardClaimedItems = false;
	public boolean homeTeleportUsedRewardClaimedItems = false;
	public boolean ibanBlastRewardClaimed = false;
	public boolean magicShortAttackRewardClaimed = false;
	public boolean barrowsCompletedRewardClaimed = false;
	public boolean dragonBonesBuriedRewardClaimed = false;
	public boolean astralsCraftedRewardClaimed = false;
	public boolean diamondsCutRewardClaimed = false;
	public boolean mithBarsSmeltedRewardClaimed = false;
	public boolean swordfishFishedRewardClaimed = false;
	public boolean swordfishCookedRewardClaimed = false;
	public boolean wintertodtKillsRewardClaimed = false;
	public boolean yewsChoppedRewardClaimed = false;
	public boolean mahoganyArmchairsRewardClaimed = false;
	public boolean runiteCrossbowFletchedRewardClaimed = false;
	public boolean knightsPickpocketedRewardClaimed = false;
	public boolean slayerTaskExtendedOrBlockedRewardClaimed = false;
	public boolean treeGrownRewardClaimed = false;
	public boolean chinchompasCaughtRewardClaimed = false;
	public boolean restoresMixedRewardClaimed = false;
	public boolean fairyRingUsedRewardClaimed = false;
	public boolean brimstoneChestUsedRewardClaimed = false;
	public boolean puropuroTravelledToRewardClaimed = false;
	public boolean chaosElementalKilledRewardClaimed = false;
	public boolean iritGrownRewardClaimed = false;
	public boolean torsoEquippedRewardClaimed = false;
	public boolean wildernessLapsCompletedRewardClaimed = false;
	public boolean mediumCluesCompletedRewardClaimed = false;
	public boolean ibanBlastRewardClaimedItems = false;
	public boolean magicShortAttackRewardClaimedItems = false;
	public boolean barrowsCompletedRewardClaimedItems = false;
	public boolean dragonBonesBuriedRewardClaimedItems = false;
	public boolean astralsCraftedRewardClaimedItems = false;
	public boolean diamondsCutRewardClaimedItems = false;
	public boolean mithBarsSmeltedRewardClaimedItems = false;
	public boolean swordfishFishedRewardClaimedItems = false;
	public boolean swordfishCookedRewardClaimedItems = false;
	public boolean wintertodtKillsRewardClaimedItems = false;
	public boolean yewsChoppedRewardClaimedItems = false;
	public boolean mahoganyArmchairsRewardClaimedItems = false;
	public boolean runiteCrossbowFletchedRewardClaimedItems = false;
	public boolean knightsPickpocketedRewardClaimedItems = false;
	public boolean slayerTaskExtendedOrBlockedRewardClaimedItems = false;
	public boolean treeGrownRewardClaimedItems = false;
	public boolean chinchompasCaughtRewardClaimedItems = false;
	public boolean restoresMixedRewardClaimedItems = false;
	public boolean fairyRingUsedRewardClaimedItems = false;
	public boolean brimstoneChestUsedRewardClaimedItems = false;
	public boolean puropuroTravelledToRewardClaimedItems = false;
	public boolean chaosElementalKilledRewardClaimedItems = false;
	public boolean iritGrownRewardClaimedItems = false;
	public boolean torsoEquippedRewardClaimedItems = false;
	public boolean wildernessLapsCompletedRewardClaimedItems = false;
	public boolean mediumCluesCompletedRewardClaimedItems = false;
	public boolean duradelUsed = false;
	public boolean nieveUsed = false;
	public boolean vannakaUsed = false;
	public boolean turaelUsed = false;
	public boolean konarUsed = false;
	public boolean krystaliaUsed = false;
	public boolean tortureSmithed = false;
	public boolean tortureStrung = false;
	public boolean slayerHelmCraftedRewardClaimed = false;
	public boolean lavaDragonsKilledRewardClaimed = false;
	public boolean lavaDragonBonesBuriedRewardClaimed = false;
	public boolean crystalEquipmentWornRewardClaimed = false;
	public boolean chargeCastedRewardClaimed = false;
	public boolean larransChestRewardClaimed = false;
	public boolean magicShortbowsFletchedRewardClaimed = false;
	public boolean revsKilledRewardClaimed = false;
	public boolean heroPickpocketedRewardClaimed = false;
	public boolean magicsChoppedRewardClaimed = false;
	public boolean magicsBurntRewardClaimed = false;
	public boolean adamantOreMinedRewardClaimed = false;
	public boolean adamantBarsSmeltedRewardClaimed = false;
	public boolean anglersOrSharksFishedRewardClaimed = false;
	public boolean anglersOrSharksCookedRewardClaimed = false;
	public boolean bloodsCraftedRewardClaimed = false;
	public boolean hardCluesRewardClaimed = false;
	public boolean motherloadMineUpperRewardClaimed = false;
	public boolean dragonSqSmithedRewardClaimed = false;
	public boolean blowpipeFletchedRewardClaimed = false;
	public boolean rogueChestRewardClaimed = false;
	public boolean gwdBossesKilledRewardClaimed = false;
	public boolean krakenKilledRewardClaimed = false;
	public boolean voidEquippedRewardClaimed = false;
	public boolean allSlayerMastersUsedRewardClaimed = false;
	public boolean prospectorEquippedRewardClaimed = false;
	public boolean slayerHelmCraftedRewardClaimedItems = false;
	public boolean lavaDragonsKilledRewardClaimedItems = false;
	public boolean lavaDragonBonesBuriedRewardClaimedItems = false;
	public boolean crystalEquipmentWornRewardClaimedItems = false;
	public boolean chargeCastedRewardClaimedItems = false;
	public boolean larransChestRewardClaimedItems = false;
	public boolean magicShortbowsFletchedRewardClaimedItems = false;
	public boolean revsKilledRewardClaimedItems = false;
	public boolean heroPickpocketedRewardClaimedItems = false;
	public boolean magicsChoppedRewardClaimedItems = false;
	public boolean magicsBurntRewardClaimedItems = false;
	public boolean adamantOreMinedRewardClaimedItems = false;
	public boolean adamantBarsSmeltedRewardClaimedItems = false;
	public boolean anglersOrSharksFishedRewardClaimedItems = false;
	public boolean anglersOrSharksCookedRewardClaimedItems = false;
	public boolean bloodsCraftedRewardClaimedItems = false;
	public boolean hardCluesRewardClaimedItems = false;
	public boolean motherloadMineUpperRewardClaimedItems = false;
	public boolean dragonSqSmithedRewardClaimedItems = false;
	public boolean blowpipeFletchedRewardClaimedItems = false;
	public boolean rogueChestRewardClaimedItems = false;
	public boolean gwdBossesKilledRewardClaimedItems = false;
	public boolean krakenKilledRewardClaimedItems = false;
	public boolean voidEquippedRewardClaimedItems = false;
	public boolean allSlayerMastersUsedRewardClaimedItems = false;
	public boolean prospectorEquippedRewardClaimedItems = false;
	public boolean redwoodsChoppedRewardClaimed = false;
	public boolean redwoodsBurntRewardClaimed = false;
	public boolean amethystMinedRewardClaimed = false;
	public boolean dragonfireShieldCreatedRewardClaimed = false;
	public boolean darkCrabFishedRewardClaimed = false;
	public boolean darkCrabCookedRewardClaimed = false;
	public boolean dragonDartsFletchedRewardClaimed = false;
	public boolean amethystArrowtipsCraftedRewardClaimed = false;
	public boolean tzhaarMembersPickpocketedRewardClaimed = false;
	public boolean wildernessSlayerTasksCompletedRewardClaimed = false;
	public boolean raidsCompletedRewardClaimed = false;
	public boolean vorkathKilledRewardClaimed = false;
	public boolean galvekKilledRewardClaimed = false;
	public boolean alchemicalHydraKilledRewardClaimed = false;
	public boolean masterCluesCompletedRewardClaimed = false;
	public boolean zulrahKilledRewardClaimed = false;
	public boolean wrathsCraftedRewardClaimed = false;
	public boolean dragonsAnimatedRewardClaimed = false;
	public boolean demonicThroneSatOnRewardClaimed = false;
	public boolean barehandedImplingCatchRewardClaimed = false;
	public boolean tortureCraftedRewardClaimed = false;
	public boolean ardougneLapsCompletedRewardClaimed = false;
	public boolean infernoCompletedRewardClaimed = false;
	public boolean divineSuperCombatsMixedRewardClaimed = false;
	public boolean infernalPickMadeRewardClaimed = false;
	public boolean pohSpiritTreeUsedRewardClaimed = false;
	public boolean redwoodsChoppedRewardClaimedItems = false;
	public boolean redwoodsBurntRewardClaimedItems = false;
	public boolean amethystMinedRewardClaimedItems = false;
	public boolean dragonfireShieldCreatedRewardClaimedItems = false;
	public boolean darkCrabFishedRewardClaimedItems = false;
	public boolean darkCrabCookedRewardClaimedItems = false;
	public boolean dragonDartsFletchedRewardClaimedItems = false;
	public boolean amethystArrowtipsCraftedRewardClaimedItems = false;
	public boolean tzhaarMembersPickpocketedRewardClaimedItems = false;
	public boolean wildernessSlayerTasksCompletedRewardClaimedItems = false;
	public boolean raidsCompletedRewardClaimedItems = false;
	public boolean vorkathKilledRewardClaimedItems = false;
	public boolean galvekKilledRewardClaimedItems = false;
	public boolean alchemicalHydraKilledRewardClaimedItems = false;
	public boolean masterCluesCompletedRewardClaimedItems = false;
	public boolean zulrahKilledRewardClaimedItems = false;
	public boolean wrathsCraftedRewardClaimedItems = false;
	public boolean dragonsAnimatedRewardClaimedItems = false;
	public boolean demonicThroneSatOnRewardClaimedItems = false;
	public boolean barehandedImplingCatchRewardClaimedItems = false;
	public boolean tortureCraftedRewardClaimedItems = false;
	public boolean ardougneLapsCompletedRewardClaimedItems = false;
	public boolean infernoCompletedRewardClaimedItems = false;
	public boolean divineSuperCombatsMixedRewardClaimedItems = false;
	public boolean infernalPickMadeRewardClaimedItems = false;
	public boolean pohSpiritTreeUsedRewardClaimedItems = false;
	public boolean experienceLock;
	public boolean mageArena, resourceArea;
	public boolean obeliskRedirectionScroll;
	public boolean talkedToTzHaarKetKeh;
	public boolean talkedToIgnisia;
	public boolean slayerTaskDangerous = false;
	public boolean vengeanceActive;
	public boolean shadowMute;
	public boolean enteredAbyss;
	public boolean morytaniaFarmAchievement;
	public boolean hidePlayerIcon = false;
	public boolean resting;
	public boolean joinedTournament = false; // Save this in case the server disconnects/restarts during the waiting lobby
	public boolean raidsEntranceWarning = false;
	public boolean ringOfSufferingEffect = true;
	public boolean hasCustomTitle;
	public boolean bestiaryIntro = false;
	public boolean showHitAsExperience = false;
	public boolean firstMysteryBoxReward = true;
	public boolean diceHost = false;
	public boolean supplyChestWarning = true;
	public boolean bloodyKeyWarning = true;
	public boolean hideFreeItems = false;
	public boolean ROWAutoCollectBloodMoney = false;
	public boolean ROWAutoCollectEther = false;
	public boolean ROWAutoCollectBM = false;
	public boolean ROWAutoCollectGold = false;
	public boolean gotChristmasPresent = false;
	public boolean snowballPeltOption = false;
	public boolean bloodyMerchantTradeWarning = true;
	public boolean broadcastBossEvent = true;
	public boolean broadcastCaptureTheFlag = true;
	public boolean broadcastActiveVolcano = true;
	public boolean broadcastHotspot = true;
	public boolean broadcastSupplyChest = true;
	public boolean broadcastBloodyMechant = true;
	public boolean broadcastAnnouncements = true;
	public boolean broadcastTournaments = true;
	public boolean bootsOfLightnessTaken = false;
	public boolean startedEggHunt = false;
	public boolean preventSkippingCourse = false;
	public boolean obtained50KCVorkathHead = false;
	public boolean autoCollectEther = false;
	public boolean unlockedGreenSkin;
	public boolean unlockedBlueSkin;
	public boolean unlockedPurpleSkin;
	public boolean unlockedWhiteSkin;
	public boolean unlockedBlackSkin;
	public boolean bountyHunterOverlay = true;
	public boolean lostCannon = false;
	public boolean isInstanced = false;
	public boolean cerberusMetamorphisis;
	public boolean infernalJadMetamorphisis;
	public boolean abyssalSireMetamorphisis;

	public long xarpusBestTime;
	public long argentavisBestTime;
	public long grotesqueGuardiansBestTime;
	public long leviathanBestTime;
	public long alchemicalHydraBestTime;
	public long zulrahBestTime;
	public long solHereditBestTime;
	public long yamaBestTime;
	public long nightmareBestTime;
	public long soloNightmareBestTime;
	public long phantomMuspahBestTime;
	public long dukeSucellusBestTime;
	public long vardorvisBestTime;
	public long vorkathBestTime;
	public long whispererBestTime;
	public long chambersOfXericSoloBestTime;
	public long chambersOfXericDuoBestTime;
	public long chambersOfXericTrioBestTime;
	public long chambersOfXericFourManBestTime;
	public long chambersOfXericFiveManBestTime;
	public long theatreSoloBestTime;
	public long theatreDuoBestTime;
	public long theatreTrioBestTime;
	public long theatreFourManBestTime;
	public long theatreFiveManBestTime;
	public int chaosFanaticKillsSincePotion;


	public long soloOlmBestTime;
	public long araxxorBestTime;
	public long scurriusBestTime;
	public long moonsOfPerilBestTime;
	public long akkhaBestTime;
	public long kephriBestTime;
	public long babaBestTime;
	public long zebakBestTime;
	public long tumekenBestTime;
	public long elidinisBestTime;
	public long toaBestTime;
	public long loyaltyTimer = System.currentTimeMillis();
	public long loyaltySpreeTimer = System.currentTimeMillis();
	public long rejuvenationPool = 0;
	public long explorerring = 0;
	public long slayertaskskip = 0;
	public long slayertasktimer = 0;
	public long Dslayertask = 0;
	public long Dslayertasktimer = 0;
	public long lastSacrifice;
	public long riskedBloodMoney = 0;
	public long nexAltarDelay = System.currentTimeMillis();
	public long mageSkillcapeSpecial = System.currentTimeMillis();
	public long explorerRingSpecial = System.currentTimeMillis();
	public long faladorShieldSpecial = System.currentTimeMillis();
	public long galvekBestTime;
	public long voteTime;
	public long lastAgilityCapeBoost;
	public long lastTimeKilledDonatorBoss;
	public long discordId;
	public long inviteDelay = 1000;
	public long lastDailyTaskResetInEpoch = 0;
	public long lastVoteInEpoch = 0;
	public long groupLeaveInEpoch = 0;
	public long lastCannonClaimInEpoch = 0;
	public long lastVoteStreakRewardInEpoch = 0;
	public long lastVoteClaimInEpoch = 0;
	public long lastDonationClaimInEpoch = 0;
	public long lastVoteRewardInEpoch = 0;
	public long lastLoginRewardInEpoch = 0;
	public long currentVoteRewardDay;
	public long lastTimeEnteredPlunder = 0;
	public long PyramidtimeRemaining;
	public long temporosstimer;
	public long crystallineHunllefBestTime;
	public long corruptedHunllefBestTime;
	public long lastLoginTime = System.currentTimeMillis();
	public long playTime;
	public long yellDelay;
	public long pickpocketDelay;
	public long fightCavesBestTime;
	public long infernoBestTime;
	public long muteEnd;
	public long nextWildernessBonus;
	public long[] lastVoted = new long[4];
	public long doeBestTime;

	public long delveOneBestTime;
	public long delveTwoBestTime;
	public long delveThreeBestTime;
	public long delveFourBestTime;
	public long delveFiveBestTime;
	public long delveSixBestTime;
	public long delveSevenBestTime;
	public long delveEightBestTime;
	public long delveBestTime;

	public double totalCompletionistProgress = 41621;
	public double chaosAltarBoneChance = 50;
	public double energyUnits = 10000;
	public double currentCompletionistProgress = 0;

	@SerializedName(value = "lastIpAddress")
	public String ipAddress;
	public String password;
	public String bossSlayerName = null;
	public String nameChange = null;
	public String presetNameOne = "Empty";
	public String presetNameTwo = "Empty";
	public String presetNameThree = "Empty";
	public String presetNameFour = "Empty";
	public String presetNameFive = "Empty";
	public String theatreroom = "";
	public String lastHwid;
	public String slayerTaskName;
	public String jailerName;
	public String registeredOn = "";
	public String customTitle;
	public String lastLoginDate;
	public String previousBossSlayerName = "";
	public String hwid;
	public Set<String> hwids = new HashSet<>();

	public HashMap<Integer, Integer> uniqueDrops = new HashMap<>();
	public HashMap<Integer, Integer> mineralBagItems = new HashMap<>();
	public HashMap<String, Boolean> claimedCollectionLogs = new HashMap<>();
	public HashMap<Integer, Integer> activePerks = new HashMap<>();
	public HashMap<Integer, Integer> perkPresetOne = new HashMap<>();
	public HashMap<Integer, Integer> perkPresetTwo = new HashMap<>();
	public HashMap<Integer, Integer> perkPresetThree = new HashMap<>();
	public HashMap<Integer, Integer> perkPresetFour = new HashMap<>();
	public HashMap<Integer, Integer> perkPresetFive = new HashMap<>();
	public HashMap<Integer, Integer> ownedPerks = new HashMap<>();
	public HashMap<Integer, Boolean> combatAchievementStore = new HashMap<>();
	public HashMap<String, Integer> DiaryRecorder = new HashMap<>();
	public HashMap<Integer, Integer> savedConfigs = new HashMap<>();
	public Map<Integer, List<Integer>> toaInvocationFavourites = new HashMap<>();
	public Map<Integer, Integer> weaponAutocastIds = new HashMap<>();

	public List<Integer> recentMysteryBoxRewards = new ArrayList<>();
	public List<Integer> recentArmourMysteryBoxRewards = new ArrayList<>();
	public List<Integer> recentWeaponMysteryBoxRewards = new ArrayList<>();
	public List<Integer> recentHolidayMysteryBoxRewards = new ArrayList<>();

	public final List<Item> doeRewardItems = new ArrayList<>();
	public final List<Item> mokhaiotlRewardItems = new ArrayList<>();

	public TickDelay doubleDropTimer = new TickDelay();
	public TickDelay doubleExpTimer = new TickDelay();
	public TickDelay brewImmunityTimer = new TickDelay();
	public TickDelay dropRateBoostTimer = new TickDelay();
	public TickDelay prayerBoostTimer = new TickDelay();
	public TickDelay damageBoostTimer = new TickDelay();
	public TickDelay damageReductionBoostTimer = new TickDelay();
	public TickDelay crystalMemoryDelay = new TickDelay();
	public TickDelay thrallSpawnDelay = new TickDelay();
	public TickDelay thrallDespawnDelay = new TickDelay();

	public Item[] currentDailyRewards = new Item[5];
	public Item[][] wildernessKeyItems = new Item[5][];
	public Item dailyTasksCompletionReward;
	public ArrayList<Item> unlockedIronmanItems = new ArrayList<>();

	public KillCounter drakeKills = new KillCounter();
	public KillCounter tombsOfAmascutExpertKills = new KillCounter();
	public KillCounter wyrmKills = new KillCounter();
	public KillCounter kreeArraKills = new KillCounter();
	public KillCounter commanderZilyanaKills = new KillCounter();
	public KillCounter generalGraardorKills = new KillCounter();
	public KillCounter taintedUnicornKills = new KillCounter();
	public KillCounter ophidiaKills = new KillCounter();
	public KillCounter grotesqueGuardianKills = new KillCounter();
	public KillCounter catalystBruteKills = new KillCounter();
	public KillCounter catalystRangerKills = new KillCounter();
	public KillCounter catalystMagerKills = new KillCounter();
	public KillCounter elderChaosDruidKills = new KillCounter();
	public KillCounter lizardmanShamanKills = new KillCounter();
	public KillCounter krilTsutsarothKills = new KillCounter();
	public KillCounter araxxorKills = new KillCounter();
	public KillCounter yamaKills = new KillCounter();
	public KillCounter tormentedDemonKills = new KillCounter();
	public KillCounter scurriusKills = new KillCounter();
	public KillCounter dagannothRexKills = new KillCounter();
	public KillCounter dagannothPrimeKills = new KillCounter();
	public KillCounter dagannothSupremeKills = new KillCounter();
	public KillCounter giantMoleKills = new KillCounter();
	public KillCounter kalphiteQueenKills = new KillCounter();
	public KillCounter kingBlackDragonKills = new KillCounter();
	public KillCounter callistoKills = new KillCounter();
	public KillCounter venenatisKills = new KillCounter();
	public KillCounter vetionKills = new KillCounter();
	public KillCounter chaosElementalKills = new KillCounter();
	public KillCounter chaosFanaticKills = new KillCounter();
	public KillCounter crazyArchaeologistKills = new KillCounter();
	public KillCounter scorpiaKills = new KillCounter();
	public KillCounter barrowsChestsLooted = new KillCounter();
	public KillCounter corporealBeastKills = new KillCounter();
	public KillCounter zulrahKills = new KillCounter();
	public KillCounter jadCounter = new KillCounter();
	public KillCounter zukKills = new KillCounter();
	public KillCounter krakenKills = new KillCounter();
	public KillCounter thermonuclearSmokeDevilKills = new KillCounter();
	public KillCounter cerberusKills = new KillCounter();
	public KillCounter abyssalSireKills = new KillCounter();
	public KillCounter skotizoKills = new KillCounter();
	public KillCounter wintertodtKills = new KillCounter();
	public KillCounter oborKills = new KillCounter();
	public KillCounter hydraKills = new KillCounter();
	public KillCounter nightmareofAshihamaKills = new KillCounter();
	public KillCounter leviathanKills = new KillCounter();
	public KillCounter whispererKills = new KillCounter();
	public KillCounter dukeKills = new KillCounter();
	public KillCounter vardorvisKills = new KillCounter();
	public KillCounter sarachnisKills = new KillCounter();
	public KillCounter phantomMuspahKills = new KillCounter();
	public KillCounter nightmareKills = new KillCounter();
	public KillCounter nexKills = new KillCounter();
	public KillCounter chambersofXericKills = new KillCounter();
	public KillCounter olmOnlyKills = new KillCounter();
	public KillCounter derangedArchaeologistKills = new KillCounter();
	public KillCounter elvargKills = new KillCounter();
	public KillCounter vorkathKills = new KillCounter();
	public KillCounter galvekKills = new KillCounter();
	public KillCounter vyrewatchSentinelKills = new KillCounter();
	public KillCounter armouredZombieKills = new KillCounter();
	public KillCounter argentavisKills = new KillCounter();
	public KillCounter demonicGorillaKills = new KillCounter();
	public KillCounter adamantDragonKills = new KillCounter();
	public KillCounter runeDragonKills = new KillCounter();
	public KillCounter jungleDemonKills = new KillCounter();
	public KillCounter torturedGorillaKills = new KillCounter();
	public KillCounter theFightCaveKills = new KillCounter();
	public KillCounter theGauntletKills = new KillCounter();
	public KillCounter theCorruptedGauntletKills = new KillCounter();
	public KillCounter alchemicalHydraKills = new KillCounter();
	public KillCounter bryophytaKills = new KillCounter();
	public KillCounter hesporiKills = new KillCounter();
	public KillCounter zalcanoKills = new KillCounter();
	public KillCounter theatreOfBloodKills = new KillCounter();
	public KillCounter moonsOfPerilKills = new KillCounter();
	public KillCounter tombsOfAmascutKills = new KillCounter();
	public KillCounter dominionOfEchoesKills = new KillCounter();
	public KillCounter crawlingHandKills = new KillCounter();
	public KillCounter caveBugKills = new KillCounter();
	public KillCounter caveCrawlerKills = new KillCounter();
	public KillCounter bansheeKills = new KillCounter();
	public KillCounter caveSlimeKills = new KillCounter();
	public KillCounter rockslugKills = new KillCounter();
	public KillCounter desertLizardKills = new KillCounter();
	public KillCounter cockatriceKills = new KillCounter();
	public KillCounter pyrefiendKills = new KillCounter();
	public KillCounter mogreKills = new KillCounter();
	public KillCounter harpieBugSwarmKills = new KillCounter();
	public KillCounter wallBeastKills = new KillCounter();
	public KillCounter killerwattKills = new KillCounter();
	public KillCounter molaniskKills = new KillCounter();
	public KillCounter basiliskKills = new KillCounter();
	public KillCounter seaSnakeKills = new KillCounter();
	public KillCounter terrorDogKills = new KillCounter();
	public KillCounter feverSpiderKills = new KillCounter();
	public KillCounter infernalMageKills = new KillCounter();
	public KillCounter brineRatKills = new KillCounter();
	public KillCounter bloodveldKills = new KillCounter();
	public KillCounter jellyKills = new KillCounter();
	public KillCounter turothKills = new KillCounter();
	public KillCounter mutatedZygomiteKills = new KillCounter();
	public KillCounter caveHorrorKills = new KillCounter();
	public KillCounter aberrantSpectreKills = new KillCounter();
	public KillCounter voteBossKills = new KillCounter();
	public KillCounter globalBossKills = new KillCounter();
	public KillCounter solHereditKills = new KillCounter();
	public KillCounter malakarKills = new KillCounter();
	public KillCounter spiritualRangerKills = new KillCounter();
	public KillCounter dustDevilKills = new KillCounter();
	public KillCounter spiritualWarriorKills = new KillCounter();
	public KillCounter kuraskKills = new KillCounter();
	public KillCounter skeletalWyvernKills = new KillCounter();
	public KillCounter gargoyleKills = new KillCounter();
	public KillCounter nechryaelKills = new KillCounter();
	public KillCounter spiritualMageKills = new KillCounter();
	public KillCounter abyssalDemonKills = new KillCounter();
	public KillCounter caveKrakenKills = new KillCounter();
	public KillCounter darkBeastKills = new KillCounter();
	public KillCounter smokeDevilKills = new KillCounter();
	public KillCounter superiorCreatureKills = new KillCounter();
	public KillCounter brutalBlackDragonKills = new KillCounter();
	public KillCounter fossilIslandWyvernsKills = new KillCounter();
	public KillCounter recruitwalkerKills = new KillCounter();
	public KillCounter sergeantwalkerKills = new KillCounter();
	public KillCounter commanderwalkerKills = new KillCounter();
	public KillCounter superiorwalkerKills = new KillCounter();
	public KillCounter balanceElementalKills = new KillCounter();

	public BeginnerUpgrades meleeWeapon = BeginnerUpgrades.MELEE_WEAPON;
	public BeginnerUpgrades rangeWeapon = BeginnerUpgrades.RANGE_WEAPON;
	public BeginnerUpgrades meleeHelm = BeginnerUpgrades.MELEE_HELM;
	public BeginnerUpgrades meleeBody = BeginnerUpgrades.MELEE_BODY;
	public BeginnerUpgrades meleeLegs = BeginnerUpgrades.MELEE_LEGS;
	public BeginnerUpgrades rangeHelm = BeginnerUpgrades.RANGE_HAT;
	public BeginnerUpgrades rangeBody = BeginnerUpgrades.RANGE_TOP;
	public BeginnerUpgrades rangeLegs = BeginnerUpgrades.RANGE_LEGS;
	public BeginnerUpgrades mageHelm = BeginnerUpgrades.MAGIC_HAT;
	public BeginnerUpgrades mageBody = BeginnerUpgrades.MAGIC_TOP;
	public BeginnerUpgrades mageLegs = BeginnerUpgrades.MAGIC_BOTTOM;

	public Position cannonPosition;
	public Position bossSlayerPosition;
	public Position crystalMemoryPosition;
	public Position slayerTaskPosition;
	public Position pvpInstancePosition;

	public ItemContainer privateRaidStorage = new ItemContainer();
	public ItemContainer raidRewards = new ItemContainer();

	public Player.CollectionLogLegacy collectionLog;
	public BountyHunter bountyHunter = new BountyHunter();
	public PlayerCombat combat = new PlayerCombat();
	public PlayerPrayer prayer = new PlayerPrayer();
	public StatList stats = new StatList();
	public Farming farming = new Farming();
	public DeathStorage deathStorage = new DeathStorage();
	public RunePouch tournamentRunePouch = new RunePouch();
	public RunePouch runePouch = new RunePouch();
	
	public DivineRunePouch DivinerunePouch = new DivineRunePouch();
	public SeedBox seedBox;
	public SoulBearer soulBearer;
	public BankPin bankPin = new BankPin();

	public final Bank bank = new Bank();
	public final Equipment equipment = new Equipment();
	public final Inventory inventory = new Inventory();
	public final FamiliarStorage familiarStorage = new FamiliarStorage();
	public final LootingBag lootingBag = new LootingBag();
	public final MineralBag mineralBag = new MineralBag();
	public final ScrollSack materialBag = new ScrollSack();

	public Appearance appearance = new Appearance();
	public PlayerMovement movement;
	public PlayerGroup primaryGroup = PlayerGroup.REGISTERED;
	public final boolean[] groups = new boolean[128];
	public SecondaryGroup secondaryGroup = SecondaryGroup.NONE;
	public ServerTeleports lastServerTeleport;
	public BoneCrusher bonecrusher = new BoneCrusher();
	public List<GearPreset> gearPresets = new ArrayList<>();

	/** Zelus Loadout system — up to 10 custom PK gear snapshots (persisted). */
	public List<ZelusLoadout> loadouts = new ArrayList<>();
	public DailyVoteInterface.DailyReward todaysVoteReward;
	public DailyLoginInterface.DailyReward todaysLoginReward;
	public HashMap<NewcomerTasks, Boolean> newcomerTasks = new HashMap<>();
	protected GameModeInterface gameModeInterface;
	public PerkTasks currentPerkTask;
	public DailyTasks[] currentDailyTasks = new DailyTasks[5];
	public Difficulty currentDifficulty;
	public BirdHouseHandler birdHouseHandler = new BirdHouseHandler();
	public EdgevilleBlacklist[] edgevilleBlacklistedUsers = new EdgevilleBlacklist[EdgevilleBlacklist.ENTRIES.length];

	public XpMode xpMode = XpMode.OSRS;
	public KillCounter revenantKills = new KillCounter();
	public KillCounter revenantMaledictusKills = new KillCounter();
	public KillCounter gloughsExperimentKills = new KillCounter();
	public ClueSave beginnerClue;
	public ClueSave easyClue;
	public ClueSave medClue;
	public ClueSave hardClue;
	public ClueSave eliteClue;
	public ClueSave masterClue;
	public BarrowsBrother barrowsChestBrother;
	public FairyRing[] unlockedFairyRingTeleports = new FairyRing[FairyRing.values().length];
	public WildernessObelisk obeliskDestination;
	public List<Integer> favoriteTeleports = new LinkedList<>();
	public FightCaves fightCaves;
	public Inferno inferno;
	public List<String> slayerBlockedTasks;
	public Map<EssencePouch, Integer> runeEssencePouches = new HashMap<>();
	public TimedList bmIpLogs = new TimedList();
	public TimedList bmUserLogs = new TimedList();

	public Pet pet;
	public List<Integer> petItemIdsObtained = new ArrayList<>();
	public Pet familiar;
	public PresetCustom[] customPresets = new PresetCustom[PresetCustom.ENTRIES.length];
	public List<Item> claimedStoreItems;

	public QuestTab journal = null;
	public House house = null;
	public DailyTask[] dailyTasks = new DailyTask[3];

	public Cannon cannon;
	public UpgradeManager upgradeManager = new UpgradeManager();
	public HashMap<Integer, Integer> SuccessfulUpgrades = new HashMap<>();
	public HashMap<Integer, Integer> FailedUpgrades = new HashMap<>();
	public Achievements currentAchievement;
	public ItemExchange itemExchange = new ItemExchange();
	public SlayerTask task;

	public boolean barrowsRunWithZeroPrayer = true;
	public TickDelay guardSpawnCoolDown = new TickDelay();
	public TickDelay elementalConvergenceDelay = new TickDelay();
	public TickDelay soulReaverDelay = new TickDelay();

	public ActivityTimer doeTimer;
	public ActivityTimer delveTimer;

	public boolean varpMigrated = false;
	public String name = null;
	public String uuid = null;

	public void setPermBanned(boolean permBanned) {
		this.permBanned = permBanned;
		this.permBannedReason = "n/a";
	}

	public void setPermBanned(boolean permBanned, String reason) {
		this.permBanned = permBanned;
		this.permBannedReason = reason;
	}

	public boolean isPermBanned() {
		return permBanned;
	}
}
