package io.ruin.model.activities.newshop;

import io.ruin.cache.ItemID;
import io.ruin.model.activities.newcomertasks.NewcomerTasks;

public enum ShopUpgradeItems {
	ELITE_VOID_TOP(ItemID.ELITE_VOID_TOP, ItemID.VOID_KNIGHT_TOP),
	ELITE_VOID_ROBE(ItemID.ELITE_VOID_ROBE, ItemID.VOID_KNIGHT_ROBE),
	KARAMJA_GLOVES_2(ItemID.KARAMJA_GLOVES_2, ItemID.KARAMJA_GLOVES_1),
	KARAMJA_GLOVES_3(ItemID.KARAMJA_GLOVES_3, ItemID.KARAMJA_GLOVES_2),
	KARAMJA_GLOVES_4(ItemID.KARAMJA_GLOVES_4, ItemID.KARAMJA_GLOVES_3),
	FREM_BOOTS_2(ItemID.FREMENNIK_SEA_BOOTS_2, ItemID.FREMENNIK_SEA_BOOTS_1),
	FREM_BOOTS_3(ItemID.FREMENNIK_SEA_BOOTS_3, ItemID.FREMENNIK_SEA_BOOTS_2),
	FREM_BOOTS_4(ItemID.FREMENNIK_SEA_BOOTS_4, ItemID.FREMENNIK_SEA_BOOTS_3),
	DESERT_AMULET_2(ItemID.DESERT_AMULET_2, ItemID.DESERT_AMULET_1),
	DESERT_AMULET_3(ItemID.DESERT_AMULET_3, ItemID.DESERT_AMULET_2),
	DESERT_AMULET_4(ItemID.DESERT_AMULET_4, ItemID.DESERT_AMULET_3),
	KANDARIN_HEAD_2(ItemID.KANDARIN_HEADGEAR_2, ItemID.KANDARIN_HEADGEAR_1),
	KANDARIN_HEAD_3(ItemID.KANDARIN_HEADGEAR_3, ItemID.KANDARIN_HEADGEAR_2),
	KANDARIN_HEAD_4(ItemID.KANDARIN_HEADGEAR_4, ItemID.KANDARIN_HEADGEAR_3),
	ARDOUGNE_CLOAK_2(ItemID.ARDOUGNE_CLOAK_2, ItemID.ARDOUGNE_CLOAK_1),
	ARDOUGNE_CLOAK_3(ItemID.ARDOUGNE_CLOAK_3, ItemID.ARDOUGNE_CLOAK_2),
	ARDOUGNE_CLOAK_4(ItemID.ARDOUGNE_CLOAK_4, ItemID.ARDOUGNE_CLOAK_3),
	MORYTANIA_LEGS_2(ItemID.MORYTANIA_LEGS_2, ItemID.MORYTANIA_LEGS_1),
	MORYTANIA_LEGS_3(ItemID.MORYTANIA_LEGS_3, ItemID.MORYTANIA_LEGS_2),
	MORYTANIA_LEGS_4(ItemID.MORYTANIA_LEGS_4, ItemID.MORYTANIA_LEGS_3),
	VARROCK_BODY_2(ItemID.VARROCK_ARMOUR_2, ItemID.VARROCK_ARMOUR_1),
	VARROCK_BODY_3(ItemID.VARROCK_ARMOUR_2, ItemID.VARROCK_ARMOUR_2),
	VARROCK_BODY_4(ItemID.VARROCK_ARMOUR_2, ItemID.VARROCK_ARMOUR_3),
	RADA_BLESSING_2(ItemID.RADAS_BLESSING_2, ItemID.RADAS_BLESSING_1),
	RADA_BLESSING_3(ItemID.RADAS_BLESSING_3, ItemID.RADAS_BLESSING_2),
	RADA_BLESSING_4(ItemID.RADAS_BLESSING_4, ItemID.RADAS_BLESSING_3),
	EXPLORER_RING_2(ItemID.EXPLORERS_RING_2, ItemID.EXPLORERS_RING_1),
	EXPLORER_RING_3(ItemID.EXPLORERS_RING_3, ItemID.EXPLORERS_RING_2),
	EXPLORER_RING_4(ItemID.EXPLORERS_RING_4, ItemID.EXPLORERS_RING_3),
	FALADOR_SHIELD_2(ItemID.FALADOR_SHIELD_2, ItemID.FALADOR_SHIELD_1),
	FALADOR_SHIELD_3(ItemID.FALADOR_SHIELD_3, ItemID.FALADOR_SHIELD_2),
	FALADOR_SHIELD_4(ItemID.FALADOR_SHIELD_4, ItemID.FALADOR_SHIELD_3),
	WILDERNESS_SWORD_2(ItemID.WILDERNESS_SWORD_2, ItemID.WILDERNESS_SWORD_1),
	WILDERNESS_SWORD_3(ItemID.WILDERNESS_SWORD_3, ItemID.WILDERNESS_SWORD_2),
	WILDERNESS_SWORD_4(ItemID.WILDERNESS_SWORD_4, ItemID.WILDERNESS_SWORD_3),
	WESTERN_BANNER_2(ItemID.WESTERN_BANNER_2, ItemID.WESTERN_BANNER_1),
	WESTERN_BANNER_3(ItemID.WESTERN_BANNER_3, ItemID.WESTERN_BANNER_2),
	WESTERN_BANNER_4(ItemID.WESTERN_BANNER_4, ItemID.WESTERN_BANNER_3),
	;
	int upgradeId;
	int toUpggradeId;

	ShopUpgradeItems(int upgradeId, int toUpggradeId) {
		this.upgradeId = upgradeId;
		this.toUpggradeId = toUpggradeId;
	}


	public int getUpgradeId() {
		return upgradeId;
	}

	public int getToUpggradeId() {
		return toUpggradeId;
	}

	public static final ShopUpgradeItems[] VALUES = values();

}
